lib/phoenix_live_view.ex

Suggested re-wording on re .leex templates summary

Re-wording Suggestions - .leex Section

---

lib/phoenix_live_view/controller.ex
lib/phoenix_live_view/router.ex
lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/router_test.exs
test/support/layout_view.ex

Add requirement for layout to be set for plugs calling live_render

---

README.md

Updated README to point to location of each file needs to be updated for enabling awesome LiveView :)

Super minor README updates to point to location of files

---

lib/phoenix_live_view.ex

fixed typo

---

lib/phoenix_live_view/controller.ex
lib/phoenix_live_view/plug.ex
lib/phoenix_live_view/router.ex
test/phoenix_live_view/plug_test.exs
test/phoenix_live_view/router_test.exs

Extract plug functionality to separate module

---

lib/phoenix_live_view.ex

Fix typo in module docs

---

assets/package-lock.json
assets/package.json

Ref #282 
https://github.com/patrick-steele-idem/morphdom/blob/master/CHANGELOG.md#255

Update morphdom 2.5.5 - solve live_render in tables

---

lib/phoenix_live_view/engine.ex
test/phoenix_live_view/engine_test.exs

Quick Fix for #302 
Probably some tests needed for that, but not feeling competent enough to write them right now

Fix or :restricted

---

lib/phoenix_live_view/router.ex
lib/phoenix_live_view/view.ex

Fix typos & remove a redundant function call

---

README.md

s/Array.prototype.from/Array.from
close #357

Updates README with correct import

---

lib/phoenix_live_view.ex

Docs reference upcoming support for pushState which is already supported.

Remove outdated docs on page and data navigation

---

lib/phoenix_live_view/test/dom.ex

Remove redundant condition

---

lib/phoenix_live_view/view.ex

I believe this was the original intention.
Thanks for reviewing.

Fix variable name

---

lib/phoenix_live_view/view.ex
test/phoenix_live_view/diff_test.exs

Fix minor typos

---

lib/phoenix_live_component.ex

- Fixes some code examples
- Minor re-wording
- Minor corrections

minor corrections and tweaks

---

lib/phoenix_live_view.ex

I am presuming this is what the text was trying to say, but am happy to be wrong.

Fix typo in specialised throttling behaviour section

---

lib/phoenix_live_view.ex

Fix minor typo

---

lib/phoenix_live_view.ex

Spelling fix

---

guides/introduction/installation.md

Update installation.md typo

---

CHANGELOG.md
lib/phoenix_live_view/socket.ex

- provide Socket as the second argument to the LiveSocket constructor
- fix code block indentation
close #515

Fix instructions

---

assets/js/phoenix_live_view.js

close #471 
Very minor concern about performance on large diffs in dev mode.

Detect duplicate ids in html

---

lib/phoenix_live_view.ex

Fix typos in Live Layout docs

---

lib/phoenix_live_view.ex

Fix @moduledoc by using a triple single-quoted heredoc

---

CHANGELOG.md

Render sample code with proper font and syntax highlighting.

Markup sample code in CHANGELOG

---

assets/js/phoenix_live_view.js
assets/test/view_test.js
lib/phoenix_live_view.ex

@josevalim can I get a pass on the docs, pretty please :heart:

Add form recovery

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/socket.ex
lib/phoenix_live_view/static.ex
lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/components_test.exs
test/phoenix_live_view/integrations/live_view_test.exs
test/phoenix_live_view_test.exs
test/support/live_views/components.ex
test/support/live_views/params.ex
test/support/router.ex

@josevalim this came out much more complex than I thought it would, so would love some 👀

Allow redirects from certain child callbacks

---

assets/js/phoenix_live_view.js

Up for discussion...
close #637

[BUG] Take out button as possible form input

---

lib/phoenix_live_view.ex

Fixes for some tiny issues I found while (re)reading the docs.

Tiny doc fixes

---

assets/js/phoenix_live_view.js

adding input types `date` and `type` to white list.

---

assets/js/phoenix_live_view.js

Closes #679
In cases where sibling components are at the same level, they will share
a common parent. In such cases, the parent's markup tree must be pre-computed
against the component HTML diff so we can apply a partial patch. Three
patch is built with empty siblings marked as PHX_SKIP to optimize morphing
siblings that we know will not change.

Fix sibling component patch when component siblings lack a container

---

lib/phoenix_live_view/utils.ex

Clear flash by string key, closes #729

---

test/phoenix_live_view_test.exs

Test clear_flash

---

lib/phoenix_live_view/diff.ex
test/phoenix_live_view/integrations/live_view_test.exs
test/support/live_views/live_in_component.ex

Fixes #725 - allow live views to be rendered inside live components

---

CHANGELOG.md

ngprogress became recommended in: d09d9ff

Add v0.11.0 breaking change for removal of live_view.css

---

test/support/live_views/elements.ex

Fix html tag

---

test/phoenix_live_view/diff_test.exs

Fix word typo

---

lib/phoenix_live_view.ex

Removed extra "LiveView" word that made no sense.

Drop extra word

---

CHANGELOG.md

Minor code formatting, capitalisation and punctuation fixes.

Improve CHANGELOG.md

---

test/phoenix_live_view/integrations/elements_test.exs

Fix spell typo

---

lib/phoenix_live_view.ex

Security docs: Suggest more automatic import of LiveHelpers

---

lib/phoenix_live_view.ex

While reading through the documentation, I noticed a few areas that could be clarified with minor punctuation or word rearrangement. I hope it helps! 💜

Edit documentation for clarity

---

lib/phoenix_live_view.ex

sorry josé, I was already committing while you push a new doc section !!!

small doc improvements

---

guides/introduction/installation.md

Consistent within this file and consistent with how it looks in a new Phoenix app.

installation.md: Consistent JS (lack of) semicolons

---

guides/introduction/installation.md

Hope these small separate doc fix PRs are OK. Figured I could make simple fixes from my phone while I read through the docs on my Kindle :)

installation.md: Typo

---

lib/phoenix_live_view/router.ex

To be updated with current generator and also to help people understand the whole flow.
Let me know if it should contain more info.

Improve live navigation doc

---

lib/phoenix_live_view.ex

Correct grammar

---

lib/phoenix_live_component.ex
lib/phoenix_live_view/diff.ex
lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/diff_test.exs
test/phoenix_live_view/integrations/components_test.exs

See #895.
Thought it could be helpful to see what the proposed fix looks like, and if it's still something you want to go ahead with. (And an opportunity for me to learn LiveView a bit better.)

Make `assigns.myself` a struct to catch mistakes

---

assets/js/phoenix_live_view.js
assets/test/view_test.js

Instead we create a span, similar to what we do for text nodes.
Closes #985.

Do not crash on components without html tags

---

lib/phoenix_live_view/test/live_view_test.ex

Documentation improvement per #988

Improve documentation for test helpers with hidden input fields

---

assets/js/phoenix_live_view.js
lib/phoenix_live_view/socket.ex
lib/phoenix_live_view/static.ex
lib/phoenix_live_view/utils.ex
test/phoenix_live_view/integrations/assigns_test.exs
test/phoenix_live_view/integrations/live_view_test.exs

Fix phx-static not being sent for child views

---

assets/js/phoenix_live_view.js
assets/test/view_test.js

Do not overwrite data-phx-component from nested components

---

lib/phoenix_live_view.ex

Also re-word the following sentence slightly.

More explicit documentation of how to access the event kind

---

assets/js/phoenix_live_view.js

If an event is sent to a component that was removed,
the server will response with an empty diff, so we need
to take that into account.
We also don't notify the server of pruned CIDs in case
of join patches, as any pruned CID will belong to the
previous LiveView.

Better handle missing components

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/utils.ex
test/phoenix_live_view/integrations/flash_test.exs

Track flash keys to fix back-to-back flashes from being discarded

---

.github/workflows/ci.yml

ci.yml: "Setup" -> "Set up"

---

assets/js/phoenix_live_view.js
assets/test/event_test.js
assets/test/view_test.js
lib/phoenix_live_component.ex
lib/phoenix_live_view.ex
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/diff.ex
lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/live_view_test.ex
lib/phoenix_live_view/utils.ex
test/phoenix_live_view/integrations/event_test.exs
test/phoenix_live_view/integrations/live_view_test.exs
test/support/live_views/events.ex
test/support/router.ex

Still working on the JS tests, but there should be plenty to review on the Elixir side in the meantime ❤️

Add ability to push events from server with replies

---

lib/phoenix_live_view/engine.ex

I know a lot of words but I had to look up "intercalating" :D Maybe this is clearer?

engine.ex docs: intercalating -> interlacing

---

guides/introduction/installation.md

a really small typo in guides ;-)

---

assets/js/phoenix_live_view.js

This is a follow up to https://github.com/phoenixframework/phoenix_live_view/pull/638
It closes https://github.com/phoenixframework/phoenix_live_view/issues/946 (see https://github.com/phoenixframework/phoenix_live_view/issues/946#issuecomment-660549980 for a more detailed explanation).

Input tag with type button is no longer form input

---

assets/js/phoenix_live_view.js
assets/test/dom_test.js
assets/test/view_test.js

This is an alternative approach to https://github.com/phoenixframework/phoenix_live_view/pull/1079 as discussed in https://github.com/phoenixframework/phoenix_live_view/pull/1079#discussion_r456942016
It fixes https://github.com/phoenixframework/phoenix_live_view/issues/1078

Fix DOM memory leak (second attempt)

---

guides/client/bindings.md
guides/client/dom-patching.md
guides/server/security-model.md

This PR has some grammar fixes as well as a mini clarification of the section around bebouncing and throttling.  I have them as separate commits in case there are any you don't want to accept.  I'm happy to squash if you are satisfied to merge.

Fix and clarify guides

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/channel.ex

This function is useful when you want the component message itself after some seconds to clean/set some state.

Add Phoenix.LiveView.send_update_after/3

---

lib/phoenix_live_view/test/live_view_test.ex

Found two `@doc`s that were not in sync with their `def`s

Fix test @docs

---

lib/phoenix_live_view.ex

Looks like this is all that was missing for #1160 but I'm kinda new to Elixir etc. so in case I'm missing anything, let me know, thanks :)

Add `handle_cast/2` to list of supported callbacks. (#1160)

---

assets/js/phoenix_live_view.js

Only compute parentCIDs within the same LiveView

---

guides/introduction/installation.md

So cool for the new version, I will have to tried that
kudos to the team !

bump version

---

lib/phoenix_live_component.ex

Fix subject of sentence

---

lib/phoenix_live_view.ex

Fix invalid syntax in documentation

Fix typo in allow_upload/3 doc

---

README.md

Link the CI status badge in README to CI workflows

---

assets/js/phoenix_live_view.js
assets/test/integration/metadata_test.js

Don't bind clicks when disconnected

---

guides/client/uploads-external.md

Update S3 example to correctly report progress

---

guides/introduction/installation.md

typo fix on installation guide

---

lib/phoenix_live_view/test/dom.ex

Many of the function arguments were implying `html` when they should imply `html_tree`. This aligns everything.

Align on html_tree

---

lib/phoenix_live_component.ex

Concerns adding documentation for recommendations by @josevalim and @mcrumm in #1398.

Update documentation to recommend single root element in phoenix_live_component.ex

---

guides/client/dom-patching.md

https://github.com/phoenixframework/phoenix_live_view/issues/1410

Add a note about updating rendered temporary assigns

---

assets/js/phoenix_live_view.js

Fix premature LiveUploader.clearFiles call

---

package.json

Ensure morphdom is a dependency for live view

---

lib/phoenix_live_view/html_engine.ex
lib/phoenix_live_view/html_tokenizer.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/html_tokenizer_test.exs

Closes #1493.
* Handle unmatched tags
* Handle unclosed tags
* FIx line/column of existing errors

More validations for HEEx

---

guides/client/js-interop.md

Alpine.js introduces some breaking changes with their latest version 3. 
This PR adapts the documentation on how to integrate live view with alpine.js.

adapt documentation on how to integrate with alpine.js V3

---

lib/phoenix_live_view/html_tokenizer.ex
test/phoenix_live_view/html_tokenizer_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/1504.

Validate mixed case HTML tags

---

assets/js/phoenix_live_view/hooks.js
assets/js/phoenix_live_view/live_uploader.js
lib/phoenix_live_view/helpers.ex

This is a reimagined version of #1485 up-to-date with the latest changes.
Closes #1481

createObjectURL for live_img_preview/2

---

assets/js/phoenix_live_view/view.js

Currently running into a similar issue as https://github.com/phoenixframework/phoenix_live_view/issues/1301 but in another part of the code.
Fix is in the same vein as https://github.com/phoenixframework/phoenix_live_view/pull/1306/

Use a more robust id query selector

---

lib/phoenix_component.ex

I hope the new sentence structure correctly defines the behaviour.
Thank you for reviewing.

Fix docs sentence structure in Phoenix.Component

---

CHANGELOG.md

Add upgrade for removed `layout` option

---

lib/phoenix_live_view/test/live_view_test.ex

See individual commit messages for details

Remove broken live view test helpers from docs

---

guides/client/js-interop.md
lib/phoenix_live_view.ex

According to https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#breaking-changes

update js snippet for 0.16

---

guides/server/security-model.md

Fix spelling

---

lib/phoenix_live_view/utils.ex
test/support/live_views/lifecycle.ex

Redirect without invoking mount

---

lib/phoenix_live_view/html_engine.ex
test/phoenix_live_view/diff_test.exs
test/phoenix_live_view/html_engine_test.exs

Fix generated self close tag

---

lib/phoenix_component.ex

I had some confusion about assigns in these function components after reading the docs, for my use-case of making some assigns optional. I provided an example for others, I imagine this is a common pattern

Clarify and add example to function component Assigns docs

---

CHANGELOG.md
lib/phoenix_live_view.ex
lib/phoenix_live_view/lifecycle.ex
mix.exs
test/phoenix_live_view/router_test.exs
test/support/live_views/lifecycle.ex

Rename lifecycle default mount callback to on_mount

---

lib/phoenix_live_view.ex

Hello! I'm not sure if you care too much about small things like this, but it stuck out to me so thought I'd submit a PR to fix a small spelling error in the live view doc.
Thanks very much!

Fix spelling error in live_view doc

---

lib/phoenix_live_view/html_engine.ex

Fix crash on invalid tag

---

lib/phoenix_live_view/js.ex

Add description for positional arguments and and improve argument name for `transition`

Improve docs for JS

---

lib/phoenix_component.ex

this PR fix doc in `Named slots with attributes` section

Fix Phoenix.Component module doc

---

lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

Handle JS command target in LV tests

---

guides/introduction/installation.md

- Better delineate which instructions are for new projects, and which are for existing projects.
- Add a link to main LiveView documentation

Clarify installation instructions

---

lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/integrations/flash_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/1741

Make live testing macro return flash as map

---

lib/phoenix_live_view/test/live_view_test.ex

I have changed refute_redirect test example from ``refute_redirect`` to ``refute_redirected``

Update Test example

---

guides/server/security-model.md

This is the only gendered pronoun in the docs.

Change pronoun

---

lib/phoenix_live_view/html_tokenizer.ex
test/phoenix_live_view/html_tokenizer_test.exs

This PR adds a context `[:comment_start]` and `[:comment_end]` to tokens that are HTML comments. Both will be added in case multiple comments start in the same line:
```html
```
In this case we would have `[:comment_start]`, `[:comment_end, :comment_start]`, `[:comment_end]`.

Add context for comments in HTML html_tokenizer

---

lib/phoenix_live_view.ex

Missing parenthesis in doc

---

.github/workflows/ci.yml
lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
mix.exs
test/phoenix_live_view/html_formatter_test.exs
test/phoenix_live_view/integrations/html_formatter_test.exs

Moving https://github.com/feliperenan/heex_formatter to be part of Phoenix Live itself.

Add Phoenix.LiveView.HTMLFormatter

---

lib/phoenix_live_view/html_formatter.ex

The current unformatted eex sample seems a little bit off. Followed the formatted example, change Hello to @user.name

Update HTML Formatter Doc

---

lib/phoenix_live_view/html_engine.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

Related to: https://github.com/phoenixframework/phoenix_live_view/issues/1506

Compile time validations for `phx-update` and `phx-hook`

---

CHANGELOG.md
mix.exs

Other changes:
- fix incorrect markup header
- add missing release date
- add Changelog link to Hex info page

Include CHANGELOG.md to HTML doc

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/html_formatter_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/1950

Handle self close tags as inline

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

closes https://github.com/phoenixframework/phoenix_live_view/issues/1955

Keep text and eex along when there isn't a whitespace

---

lib/phoenix_live_view.ex

"We wil cover" -> "We will cover"

Fix small typo in docs

---

lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/1951

Dot not format when contenteditable is present or when the tag is textarea

---

lib/phoenix_live_view/html_engine.ex
lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/html_formatter_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/1975 and https://github.com/phoenixframework/phoenix_live_view/issues/1976

Fix inline elements within block elements and add phx-no-break

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Related to: https://github.com/phoenixframework/phoenix_live_view/issues/1976#issuecomment-1101528722

Format attrs regargless preserve on HTML formatter

---

lib/phoenix_live_view/html_formatter.ex

Ref https://github.com/phoenixframework/phoenix/pull/4800

HTMLFormatter - update umbrella note

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Refactor the code a bit and fix the case where there isn't text right
after inline element.

Improve HTML formatter inlines elements check

---

lib/phoenix_live_view/html_formatter.ex

HTMLFormatter - add a note about inline comments

---

lib/phoenix_live_view.ex
test/phoenix_live_view_test.exs

Curries fun/2 with assigns for both socket_or_assigns arguments.
Complement to PR#1997

Provide assigns to arity 2 fun in update/3

---

lib/phoenix_live_view/helpers.ex

I felt like the documentation was slightly lacking in explination.

The explanation for assigns_to_attributes should show you what to expect

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Related to https://github.com/phoenixframework/phoenix_live_view/issues/2017

Format 'let' to `:let` and sort attrs that starts with `:`

---

CHANGELOG.md
lib/phoenix_live_view/socket.ex
test/phoenix_live_view/socket_test.exs

This allows an application to share the transport connection with their other regular channels

Allow sharing LiveView Socket with regular channel socket

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Fix https://github.com/phoenixframework/phoenix_live_view/issues/2055

HTML Formatter - respect heex_line_length on inline elments

---

lib/phoenix_component.ex
test/phoenix_component_test.exs

See https://github.com/phoenixframework/phoenix_live_view/issues/2078

Ensure pop_attrs/1 does not raise with nested modules

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

Should fix #2090 as well as #2089

Improve selectedness calculation for select inputs

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2088

Formatter - fix needing to format twice to get the desired format

---

lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2096

Formatter - Fix self close tag attrs within preserve mode

---

lib/phoenix_live_view/helpers.ex

Remove duplicate data-phx-link-state in <.link>

---

lib/phoenix_component.ex
test/phoenix_component_test.exs

See https://github.com/phoenixframework/phoenix_live_view/issues/2128

Declarative slots default to [] unless they are marked as required

---

lib/phoenix_component.ex

See https://github.com/phoenixframework/phoenix_live_view/issues/2128

Update docs for slot/3, attr/2, and Phoenix.Component

---

test/phoenix_component/verify_test.exs

This is a follow on from 92001046e562e3508a976dd04fffecdaf1ff0e38

Use warnings to test slot validation instead of Diagnostic

---

lib/phoenix_live_component.ex

Is there a better way to do this?

Link to Phoenix.Component slot doc

---

lib/phoenix_live_component.ex
test/phoenix_component/verify_test.exs
test/phoenix_live_view/hooks_test.exs

Adds a test case asserting that local components, both public and private, are verified.

Local Component Verification Tests

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Fix https://github.com/phoenixframework/phoenix_live_view/issues/2174

Formatter - Fix eex tag within script tag

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Fix https://github.com/phoenixframework/phoenix_live_view/issues/2182

Formatter - Improve formatter on component attrs

---

lib/phoenix_live_view/html_engine.ex
test/phoenix_live_view/html_engine_test.exs

Still needs docs but ready for review

Support :if for tags

---

CHANGELOG.md
lib/phoenix_component.ex
lib/phoenix_live_view/html_engine.ex
test/phoenix_live_view/html_engine_test.exs

@feliperenan we'll need to decide ordering for the formatter, which I'm thinking will be `:let={} :for={} :if={}`

Cm specials

---

lib/phoenix_component.ex

It took me a while to figure out how slots with attributes can have slot docs. Providing an example in the documentation could make it easier.

Slot attributes doc example

---

lib/phoenix_live_view/upload.ex
test/phoenix_live_view/upload/channel_test.exs

improve error reporting

---

lib/phoenix_component/declarative.ex

Add [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) to globals

Add pattern to globals

---

lib/phoenix_component.ex

Almost feel ashamed to bother you about it but I did copy/paste the snippet.

Fix very minor doc typo

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Fix https://github.com/phoenixframework/phoenix_live_view/issues/2237

Formatter - Fix texts along with tag blocks w/ whitespaces

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/phoenix_component/verify_test.exs

Attr values can be any kind of enum

---

lib/phoenix_component.ex

Fix embed_templates example dir name

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/phoenix_component/verify_test.exs

Resolves https://github.com/phoenixframework/phoenix_live_view/issues/2164

Raise on `:global` slot attributes

---

lib/phoenix_live_view.ex

Minor improvement to docs
Changes suggested:
`At the end of the day,` => Remove
`nothing more than` => `just`

Minor improvement to docs

---

guides/server/security-model.md

`gen.phx.auth` -> `phx.gen.auth`

Fix comment referencing auth generator

---

lib/phoenix_component.ex

docs: use string for :method attr on link examples

---

lib/phoenix_live_view/html_engine.ex
lib/phoenix_live_view/html_tokenizer.ex
test/phoenix_live_view/html_engine_test.exs

Similar to https://github.com/elixir-lang/elixir/commit/f95e5d7e109421a1388841c1ff00833d11fc678f#diff-43695c37a1348db260e0f49802241a45244b8e62c677a3496be3cad93f3cdf5cR500

Improve HTML code snippet to consider indentation

---

lib/phoenix_live_view/js.ex

> The commits are self-explanatory.

Improve docs of JS.show and JS.hide

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs
test/phoenix_live_view/diff_test.exs

fixes phoenixframework/phoenix#5197

fix: add hidden attr to csrf inputs

---

assets/js/phoenix_live_view/live_socket.js

Restore scroll when previous state was patch

---

lib/phoenix_live_view/static.ex
test/phoenix_live_view/integrations/layout_test.exs

Use Phoenix.LiveView layout opt for static render

---

guides/introduction/installation.md

Hi! This came up earlier today when I was helping someone new get set up. I think this is a little bit more clearer because there is a `app_web` folder in Phoenix apps.
Hope this helps, thaks for the awesome work ❤️

Adjust wording in guides

---

lib/phoenix_component.ex

Note handy CSS trick

---

guides/server/uploads.md

Fix a compilation error:
`Routes.static_path/2 is undefined (module Routes is not available or is yet to be defined)`

replace Routes.static_path/2 by sigil_p

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

closes https://github.com/phoenixframework/phoenix_live_view/issues/2436#event-8488991155

Formatter - proper handle heredocs

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2466

Formatter - Fix when there are multiple HTML comments

---

lib/phoenix_live_component.ex
mix.exs

Took me a while to figure out colors for both light and dark. Hopefully it's looking OK for the first iteration.

Add LiveComponent life cycle diagram to docs

---

lib/phoenix_component.ex
lib/phoenix_component/declarative.ex
lib/phoenix_live_view.ex
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/test/live_view_test.ex
lib/phoenix_live_view/utils.ex

Raises if `:uploads` assign is set in `assign/3` and `assign_new/3` functions.

Validate reserved assigns

---

guides/client/bindings.md

Mention default times for phx-debounce and phx-throttle

---

lib/phoenix_live_component.ex
mix.exs

This is an actual edition that @josevalim suggested to make. Additional bonus: dolor scheme more nicely blending with the current ExDoc.

Simplify LiveComponent life cycle diagram

---

lib/phoenix_live_view.ex

I fell into the trap, and so have others. Maybe making it clear upfront would help

Make clear that hooks are not supported in LiveComponents

---

lib/phoenix_component.ex

As per https://github.com/phoenixframework/phoenix_live_view/issues/2514 chats.
Thanks!

Update .link docs to use new ~p sigil

---

README.md

Add missing badges to main readme

---

lib/phoenix_component.ex

Small documentation correction.

Tweak to_form/2 docs

---

lib/phoenix_component.ex
lib/phoenix_live_view/tag_engine.ex
test/phoenix_component/components_test.exs
test/phoenix_live_view/html_engine_test.exs

Don't dasherize dynamic attributes

---

README.md

I took a stab at polishing the feature copy a little.

Feature copy edits

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

DOM render for streams produces an error (https://github.com/phoenixframework/phoenix_live_view/issues/2644). It works fine in browser.
I have updated the tests for this case.

Fix test render for stream updates

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex
test/support/router.ex

Fix stream reset when patching

---

guides/client/form-bindings.md

Add the missing right bracket for the assign.

add missing right bracket

---

assets/js/phoenix_live_view/view.js

I tested this locally to make sure it fixes the issue. Do we have any integration tests that could be augmented to cover an issue like this?

fix for #2752 - inputs is the array we want

---

guides/server/security-model.md
lib/phoenix_live_view/router.ex

1st PR so if there are any mistakes/changes lemme know & sorry in advance

changed some outdated examples in docs

---

guides/introduction/installation.md

Fixes issue #2784 by changing to heex syntax for the example.

Changed to heex syntax for layout example

---

lib/phoenix_live_view.ex

How to redirect to external url.

docs: two examples for redirect/2

---

lib/phoenix_live_view/test/live_view_test.ex

css selector for first child that worked for me.
Aligned to Floki selectors:
https://github.com/philss/floki#supported-selectors

docs: first child navigation using css selector

---

CHANGELOG.md

Hello. Thanks for the new release, excited to try it out !
Found a small typo while reading the changelog.

Fix 0.20.0 changelog typo

---

lib/phoenix_live_view/tokenizer.ex

Phoenex -> Phoenix
behavivour -> behaviour

Fix spelling in tokenizer.ex

---

guides/introduction/welcome.md

Jose already fixed the one above.
Is there anyway we can backport this docs fix to the latest tag? This caused me a bit of confusion and may other newbies as well.

welcome.md callback fix

---

assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/rendered.js
lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/integrations/live_components_test.exs

Always use id as the node key if set

---

assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/view.js

Fix function component element recreation on initial patch

---

lib/phoenix_live_view.ex

A try to clarify the docs a bit. See #2927 
Let me know what you think.

improve assign_async docs

---

CHANGELOG.md

fix changelog-docs

---

guides/client/uploads-external.md

Currently the external uploads guide is not friend for a beginner like myself. There are missing information about where to retrieve information, where to put them and how to debug effectively.
I have tried to be more explicit in describing what the missing pieces of informations are. I have re-arranged the phrasing a little so that it is clearer for me. Hopefully this is clearer for others as well.

External uploads guide improvement

---

assets/js/phoenix_live_view/live_socket.js

fixes: #2161 (see my comment in linked issue)

fix phx-window-focus and phx-window-blur in live_socket.js

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2768

Allow JS.patch and JS.navigate to be tested with render_click

---

test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

Relates to #2975.
Relates to #2960.

add test for stream reset order

---

lib/phoenix_component.ex

Added missing “is” phoenix_component.ex

Added missing “is” phoenix_component.ex

---

assets/js/phoenix_live_view/dom_patch.js

Fixes #2994.
```elixir
server: true,
)
Mix.install([
{:phoenix, "~> 1.7.10", override: true},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
])
end
defmodule Example.HomeLive do
use Phoenix.LiveView, layout: {__MODULE__, :live}
socket
|> stream(:items, [
%{id: "a", name: "A"},
%{id: "b", name: "B"},
%{id: "c", name: "C"},
%{id: "d", name: "D"}
])
|> then(&{:ok, &1})
end
def …
```

refactor stream reset reordering (fixes #2994)

---

guides/server/assigns-eex.md

Relates to https://github.com/phoenixframework/phoenix_live_view/issues/2995.
I'm not really good at writing, so any improvement suggestions are greatly appreciated.

Add section about passing all assigns to pitfalls docs

---

assets/js/phoenix_live_view/dom.js

Fixes #2030.
```elixir
server: true,
secret_key_base: String.duplicate("a", 64),
pubsub_server: Example.PubSub
)
Mix.install([
{:jason, "~> 1.2"},
{:phoenix, "~> 1.7.7"},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}
])
end
defmodule Example.CoreComponents do
use Phoenix.Component
attr(:for, :any, required: true, doc: "the datastructure for the form")
attr(:as, :any, default: nil, doc: "the server side parameter to collect all input under")
attr(:rest, :global,
include: …
```

allow live_file_inputs with form parameter (fixes #2030)

---

assets/js/phoenix_live_view/constants.js

add phx-hook-loading to PHX_EVENT_CLASSES (refs #2941)

---

assets/js/phoenix_live_view/dom.js

only prevent bubbling file inputs on click

---

assets/js/phoenix_live_view/dom.js

Fixes #2984.
Not sure if this is a hot path though, so the extra checking might not be what we want?

only set changed attributes in mergeAttrs (#2984)

---

assets/js/phoenix_live_view/hooks.js

References #2754.
This PR tries to finish what #2754 started. The biggest change is that it also looks at the scroll container when checking if the top / bottom is reached.
Another problem I've encountered is that the scroll position was not maintained when adding the top padding on the first page. Wrapping the scrollTo on a `requestAnimationFrame` fixes this.
```elixir
server: true,
)
Mix.install([
{:phoenix, "~> 1.7.10", override: true},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
])
def render(template, …
```

Custom scroll container support for InfiniteScroll (followup for #2754)

---

assets/js/phoenix_live_view/dom_patch.js

keep existing stream items on join (fixes #2854)

---

assets/js/phoenix_live_view/view.js

set PHX_ROOT_ID on dead DOM

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/test/dom.ex
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

clarify stream bulk insert (#3023)

---

assets/js/phoenix_live_view/rendered.js
assets/js/phoenix_live_view/view.js

Fix optimization failing to re-render components added back to the page after prune.

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/test_helper.exs
test/e2e/tests/issues/3047.spec.js
test/support/e2e/issues/issue_3047.ex

only remove stream items that are owned by the current view

---

assets/js/phoenix_live_view/view.js

Fixes https://github.com/phoenixframework/phoenix_live_view/commit/3b87f87682b55c9c40204f5febebb1044892a434 not properly adding form elements with multiple values (like a multiple select).
I'll add a test later.

Properly serialize fields with multiple values

---

assets/js/phoenix_live_view/view.js
lib/phoenix_component.ex
test/e2e/test_helper.exs
test/e2e/tests/forms.spec.js
test/support/e2e/form_dynamic_inputs_live.ex

Relates to #3056.
Relates to #3067.
Includes some tests.

Refactor form serialization with submitter

---

guides/introduction/welcome.md

welcome.md: fix a few typos

---

assets/js/phoenix_live_view/view.js
assets/test/test_helpers.js
assets/test/view_test.js

fix submitter form attribute (fixes #3092)

---

lib/phoenix_live_view/js.ex

Toggle class was missing from the summary docs

Add missing toggle_class doc to summary

---

assets/js/phoenix_live_view/dom_patch.js

check for feedback in onNodeAdded

---

assets/test/dom_test.js
test/e2e/test_helper.exs
test/e2e/tests/navigation.spec.js
test/support/e2e/navigation.ex

Extracted some tests from https://github.com/phoenixframework/phoenix_live_view/pull/3051

Add tests for live navigation

---

lib/phoenix_live_view/test/dom.ex
test/e2e/test_helper.exs
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex
test/support/router.ex

Extract streams from dynamics (fixes #3129)

---

assets/js/phoenix_live_view/live_uploader.js
assets/js/phoenix_live_view/upload_entry.js
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/upload.ex
lib/phoenix_live_view/upload_config.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/2965.spec.js
test/e2e/tests/uploads.spec.js
test/support/e2e/issues/issue_2965.ex

Fixes #3115.
Relates to #3004.
Please thoroughly review this.

Properly track preflighted uploads on the server

---

guides/server/live-layouts.md

As per https://github.com/phoenixframework/phoenix/blob/546ee2fe67f418e2e1e9886cfa37e7b7e48e0bc5/installer/templates/phx_web/router.ex#L8

use <namespace>.Layouts module in the layouts guide

---

lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/integrations/assign_async_test.exs
test/phoenix_live_view/integrations/assigns_test.exs
test/phoenix_live_view/integrations/collocated_test.exs
test/phoenix_live_view/integrations/connect_test.exs
test/phoenix_live_view/integrations/elements_test.exs
test/phoenix_live_view/integrations/event_test.exs
test/phoenix_live_view/integrations/flash_test.exs
test/phoenix_live_view/integrations/hooks_test.exs
test/phoenix_live_view/integrations/layout_test.exs
test/phoenix_live_view/integrations/live_components_test.exs
test/phoenix_live_view/integrations/live_reload_test.exs
test/phoenix_live_view/integrations/live_view_test.exs
test/phoenix_live_view/integrations/navigation_test.exs
test/phoenix_live_view/integrations/nested_test.exs
test/phoenix_live_view/integrations/params_test.exs
test/phoenix_live_view/integrations/start_async_test.exs
test/phoenix_live_view/integrations/update_test.exs
test/phoenix_live_view/router_test.exs
test/phoenix_live_view/upload/external_test.exs
test/support/live_views/general.ex

I ran all unit tests 100 times without any flakiness 😃

Fix flaky unit tests

---

assets/js/phoenix_live_view/dom_patch.js

Fixes #3188.
I will try to add an e2e test separately.
Related to: https://github.com/phoenixframework/phoenix_live_view/commit/a774138564f01425c43241f51fb4ae77f85c5726

apply isIgnored properly

---

guides/client/js-interop.md

Adding note from https://elixirforum.com/t/liveview-javascript-pushevent-to-myself-not-the-parent-liveview/52872/4 about https://github.com/phoenixframework/phoenix_live_view/pull/1397.

Add note to push event to

---

lib/phoenix_live_view.ex

Specify return values of stream functions

---

guides/client/form-bindings.md

Fix inputs_for code example

---

lib/phoenix_live_view/router.ex
mix.exs

Add note about aliases not expanded in live_session

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js

Fix argument mismatch in toggleClass

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js

I don't see any problems in making it actually work like a stack. But maybe there's a reason for the current behavior?
Closes #3176.

make push/pop focus work like a stack

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs
test/phoenix_live_view/integrations/html_formatter_test.exs

Elixir 1.13 has been set as required some time ago as you can see in the commit below:
https://github.com/phoenixframework/phoenix_live_view/commit/dec101791b5b42978475483dd0f6cfefe0d07936

Remove check for Elixir 1.13

---

lib/phoenix_live_view.ex

To avoid confusion https://elixirforum.com/t/help-understanding-phoenix-liveview-stream-4-limit-option/63837

clarify limit for stream_insert

---

CHANGELOG.md
guides/client/bindings.md
guides/client/uploads-external.md

Another opportunistic docs update.

Refer to CSS and JavaScript with consistent capitalization

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

I came across the same issue as #3170 so thought I'd have a go and see if I could make it work.
And I used Floki directly because I wasn't familiar with the DOM module. Feel free to tweak if you like.

Allow using form/3 with inputs inside and outside the form

---

assets/js/phoenix_live_view/live_socket.js

This fixes an inconsistency between bandit and cowboy. When closing the socket connection and using cowboy, we'd receive a code 1005, but when running with bandit we'd receive code 1000. LiveView currently reacts to code 1000 by doing a failsafe reload, therefore you cannot close the socket when using bandit without reloading the page.
This should be the correct way to do it: removing the server close handler when the reason for closing is the client intentionally disconnecting.

remove server close listener when disconnecting

---

CHANGELOG.md
assets/js/phoenix_live_view/live_socket.js

remove phx-capture-click

---

assets/js/phoenix_live_view/view.js
assets/test/view_test.js

References https://github.com/phoenixframework/phoenix_live_view/issues/3271

allow setting title to an empty string

---

assets/js/phoenix_live_view/view.js

wait for transitions before determining cids_destroyed

---

guides/client/js-interop.md

References
- Implementation: https://github.com/phoenixframework/phoenix_live_view/blob/02bc543fc2602a1de3f53dbfe2bbdfef443806ac/assets/js/phoenix_live_view/view.js#L772-L777
- Test: https://github.com/phoenixframework/phoenix_live_view/blob/02bc543fc2602a1de3f53dbfe2bbdfef443806ac/assets/test/view_test.js#L670-L695

Document "error" kind for phx:page-loading-start event

---

lib/phoenix_live_view/js.ex

Like in the other "toggles" in this file, explicitly mention that classes may be added or removed based on presence.

Improvements to Phoenix.LiveView.JS docs

---

CHANGELOG.md

CHANGELOG: Add a note of a regex for replacing the phx-no-feedback classes

---

lib/phoenix_live_view.ex

Improve docs of put_flash

---

CHANGELOG.md
lib/phoenix_component.ex
test/phoenix_component/components_test.exs

Closes #3341
References: #2833

deprecate dynamic_tag name in favor of tag_name

---

lib/phoenix_live_view/diff.ex

Under some circumstances it could happen that we copy the redirected value from the LV socket to a component socket, call update directly after and then raise an error, even if the component did not cause the redirect.
To reproduce:
```elixir
server: true,
)
Mix.install([
{:phoenix, "~> 1.7"},
{:phoenix_live_view,
github: "phoenixframework/phoenix_live_view", branch: "main", override: true}
])
path = Phoenix.LiveView.__info__(:compile)[:source] |> Path.dirname() |> Path.join("../")
System.cmd("mix", ["deps.get"], cd: path, into: IO.binstream())
System.cmd("npm", ["install"], …
```

Clear redirected when creating component socket

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/helpers.ex
lib/phoenix_live_view/html_formatter.ex
lib/phoenix_live_view/upload_writer.ex
lib/phoenix_live_view/utils.ex

Fix typos and improve language

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

Handle string with escaped quotes as expression

---

lib/phoenix_live_view/engine.ex
test/phoenix_live_view/engine_test.exs

Re-render if field usage changes

---

assets/js/phoenix_live_view/view.js
guides/client/form-bindings.md

Closes #3394.
References #2916.

Warn when input is used outside of a form

---

guides/client/bindings.md

Fix broken internal doc link for scroll events.

---

lib/phoenix_live_view.ex

For context see: https://elixirforum.com/t/whats-the-difference-between-a-parent-and-child-liveview/65853

document that handle_params is only allowed on the root LV

---

assets/js/phoenix_live_view/browser.js
test/e2e/support/navigation.ex
test/e2e/tests/navigation.spec.js

Wait for diff to be applied before scrolling to hash

---

README.md

Hello LiveView team, We recently created 80 Phoenix and Phoenix LiveView components in 43 categories with a generator for everything and no dependencies (in this version) are added to your project and our goal is reaching to 200 components.
The Chelekom library/project has the potential to cover and solve a huge amount of UI deficiencies in LiveView with fresh approach, including a CLI generator.
Our effort was to create a suitable document along with the maximum use of the things that Phoenix provides to the users to advance this project and not force the user to use other ecosystems.
**I hope this project has a chance to be listed in LiveView**
> It should be noted that the library was created with the latest version of LiveView (main branch).
- Forum post: …

Add Mishka Chelekom Phoenix & LiveView UI kit and components into README.md

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/route.ex
test/phoenix_live_view/router_test.exs

Check live_session when patching to same LiveView

---

lib/phoenix_component.ex
lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
lib/phoenix_live_view/tag_engine.ex
lib/phoenix_live_view/tokenizer.ex
test/phoenix_live_view/html_engine_test.exs
test/phoenix_live_view/html_formatter_test.exs
test/phoenix_live_view/tokenizer_test.exs

Allow curly interpolation to be disabled with phx-no-curly-interpolation

---

README.md

Hi,
I wonder if we could mention Elixir WebRTC live components in the README. I am not sure if their quality meets your standards so no worries if you prefer to keep the README as is :slightly_smiling_face:

Mention Elixir WebRTC live components

---

.github/workflows/assets.yml

See https://github.com/phoenixframework/phoenix_live_dashboard/pull/461.

Build assets on CI

---

assets/js/phoenix_live_view/js.js
assets/js/phoenix_live_view/view.js
test/e2e/support/form_live.ex
test/e2e/tests/forms.spec.js

evaluate js commands during form recovery

---

lib/phoenix_component.ex

This issue was also existing at another position in the docs with this pr (https://github.com/phoenixframework/phoenix_live_view/pull/3571 ), but not here yet.

docs: correct example in docs for rendering multiple slots 

---

assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3530.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3530.spec.js

fail early when hook element is not owned by view

---

.github/workflows/docs.yml

inspired by @zachdaniel (https://bsky.app/profile/zachdaniel.dev/post/3lea2llgvcc2j)
@chrismccord you'll need to set the pages source to GitHub actions here: https://github.com/phoenixframework/phoenix_live_view/settings/pages

deploy latest docs to github pages

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js
jest.config.js
setupTestsAfterEnv.js

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3691.
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3675.
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3563.
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3657
Relates to: f06877a607d3a1ceded3473bb75ffe2ba3d2002c

ensure JS.show/hide/toggle work as before, fix focus

---

assets/js/phoenix_live_view/view.js

The current code did lots of unnecessary work that quickly exploded in complexity for large forms.
See: https://elixirforum.com/t/running-into-javascript-timeouts-with-liveview-browser-tab-hangs-and-medium-sized-forms/69664
```elixir
server: true,
)
Mix.install(
[
{:phoenix, "~> 1.7"},
{:phoenix_live_view,
github: "phoenixframework/phoenix_live_view", branch: "sd-optimize-serializeForms-assets", override: true}
]
)
#
end
defmodule Example.HomeLive do
use …
```

Optimize serializeForm

---

assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/view.js
assets/test/live_socket_test.js
test/e2e/support/form_live.ex
test/e2e/tests/forms.spec.js

Relates to: https://elixirforum.com/t/how-to-reduce-impact-of-deployments-on-a-liveview/69660

keep active focus when reconnecting

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3673

allow to skip persistent id generation

---

assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3686.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3686.spec.js

copy join flash when falling back to redirect

---

assets/js/phoenix_live_view/dom_patch.js

Relates to: #3652.
Fixes #3758.
In #3652, we changed to use the regular DOM patching when unlocking cloned trees, but there was an issue if the undoRef was not exactly the lockRef in the DOM, but actually a larger one, which also undoes the lock, but we ended up cloning instead.

don't clone if lock is undone (fixes #3758)

---

lib/phoenix_component.ex
test/phoenix_component_test.exs

allow structs as param values in used_input? check

---

.github/workflows/ci.yml
package-lock.json
package.json

Also updated morphdom to 2.7.5.
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3742.

update js dependencies

---

guides/client/bindings.md
guides/client/js-interop.md
lib/phoenix_live_view/js.ex

Add documentation for liveSocket.js() and hook.js()

---

guides/client/form-bindings.md

Add section for preventing form submission in the form bindings guide

---

lib/phoenix_live_view/test/live_view_test.ex

Add 303 http status code to liveview test error redirect statuses

Add 303 http status code to liveview test

---

assets/js/phoenix_live_view/view.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3780.

don't log in maybePushComponentsDestroyed if already destroyed

---

assets/js/phoenix_live_view/view.js
test/e2e/tests/forms.spec.js

Fix unused input tracking in form recovery

---

guides/server/assigns-eex.md
lib/phoenix_component.ex
lib/phoenix_live_view/engine.ex
lib/phoenix_live_view/keyed_comprehension.ex
lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/diff_test.exs
test/support/live_views/general.ex

follow-up for https://github.com/phoenixframework/phoenix_live_view/pull/3827.

introduce :key-ed :for comprehensions without special syntax

---

CHANGELOG.md

I moved the macro component section to the beginning, as that is probably the biggest new feature.

add portal section to changelog

---

lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/tag_engine_test.exs

@SteffenDE I find this cleaner but it is your call!

Use recursion when marking variables for change tracking

---

lib/phoenix_live_view/colocated_hook.ex

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3883.

add note about compilation order

---

lib/phoenix_live_view/test/live_view_test.ex

Adds requested function in #3863 .
Will gladly add tests, but i am quite unsure where.

add refute_patched

---

lib/phoenix_live_view/test/tree_dom.ex
test/phoenix_live_view/test/tree_dom_test.exs

Fix tree dom main bug

---

lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/tree_dom.ex
test/phoenix_component/components_test.exs
test/phoenix_live_view/integrations/stream_test.exs
test/phoenix_live_view/integrations/update_test.exs

This can be backported to v1.1.

Optimize and unify TreeDOM.all/filter

---

assets/js/phoenix_live_view/view.js
test/e2e/support/portal.ex
test/e2e/tests/portal.spec.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3950.

fix ownsElement to account for portals

---

guides/client/bindings.md
lib/phoenix_live_view/js.ex

Relates to https://github.com/phoenixframework/phoenix_live_view/issues/3943

Add note about phx-mounted limitation to ignore_attributes docs

---

assets/js/phoenix_live_view/view.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3910

add unstructuredError and errorKind to phx:page-loading-start details

---

lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/live_view_test.ex
lib/phoenix_live_view/test/utils.ex
test/phoenix_live_view/integrations/elements_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3975

Account for keyword lists in follow_trigger_action / submit_form

---

lib/phoenix_live_view/test/diff.ex
test/phoenix_live_view/integrations/stream_test.exs
test/phoenix_live_view/test/diff_test.exs
test/support/live_views/streams.ex

fix merging of streams in LiveViewTest

---

assets/js/phoenix_live_view/js.js
assets/test/view_test.ts

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3996.

prevent crash when passing * to ignore_attributes

---

assets/js/phoenix_live_view/view.js
assets/test/test_helpers.ts
assets/test/view_test.ts

Closes https://github.com/phoenixframework/phoenix_live_view/issues/4003.

Only set empty title for main view
