lib/phoenix_component/declarative.ex

This attribute applies to inputs, like [`<input type="button">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button).

Add `type` attribute to globals

---

mix.exs

The `.formatter.exs` file contains an `export` option but the file isn't included in the package. For apps using Phoenix 1.6, the formatter wants to convert `slot :inner_block, required: true` to `slot(:inner_block, required: true)`.

Include `.formatter.exs` in hex package

---

CHANGELOG.md

Documentation fix following up on #2212

Fix module references in 0.18.0 deprecations

---

lib/phoenix_component.ex

It was unclear to me at first that `attr`/`slot` apply to the following function, not on a module scope. At first glance it you're defining "module" attributes, like you might define an ecto schema but this isn't the case.

Document two function components in the same module with different attributes

---

lib/phoenix_live_view.ex

`assign` (used in line 581) is not imported from `Phoenix.LiveView` since 0.18, instead this is available in `Phoenix.Component`.

Fix documentation for router hooks

---

lib/phoenix_live_component.ex
lib/phoenix_live_view.ex

This allows `use Phoenix.LiveComponent, global_prefixes: ~w(x-)` on the caller.
@chrismccord this appears to fix the issue I was seeing with `x-bind:disabled` failing compile checks. The caller in this situation was a LiveComponent so there was no way to set `global_prefixes` on the caller without this change.

Accept global_prefixes option for LiveComponent

---

assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/utils.js
assets/test/utils_test.js

If we define a `phx-click` event on an element with no children and set `disabled` on that element, `phx-click` will not fire. However, if that element has children and we click on those, the event will fire.
Compare:
```heex
<button disabled phx-click="increment">+ 1</button>
```
to
```heex
<button disabled phx-click="toggle">
<span class="material-icon">add</span>
</button>
```
In the first example, the event will not fire. In the second one, the event will fire. This doesn't adhere to standard HTML behavior.
I've tested this on `<button>` elements, but I imagine the behavior is fairly general.

Disabled `phx-click` targets with children should not fire click events.

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs

This fixes a compilation error when the attributes are "wrongly" ordered.
(Also added two test cases for both orderings.)
Example:
```elixir
attr :variant, :string, values: ["normal", "outline"], default: "normal"
```
results in 
```
== Compilation error in file some_file.ex ==
** (FunctionClauseError) no function clause matching in Phoenix.Component.Declarative.validate_attr_default!/6    
The following arguments were given to Phoenix.Component.Declarative.validate_attr_default!/6:
nil
:variant
:string
[values: ["normal", "outline"], default: "normal"]
18
"path/to/some_file.ex"
Attempted function clauses (showing 2 out of 2):
defp validate_attr_default!(slot, name, _type, [default: default, values: values], line, file)
defp validate_attr_default!(slot, name, type, [default: default], …
```

Allow `values` before `default` in `attr`

---

lib/phoenix_component.ex

Sorry for this very minor fix. BTW, I looked for some other errors in the doc and found nothing else.

Fix doc typo

---

lib/phoenix_live_component.ex

These make the docs look a bit funny:
(this was reported by someone else on Slack but they didn't have the time to fix it, and it doesn't look like anyone else has yet)

Fix syntax error typos in docs

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

We should only set href="#" when the user specifies it or href is not included.

Don't set href to # in links with methods

---

CHANGELOG.md

I've noticed that in changelog it mentioned `live_upload_preview` where it should be `live_img_preview`

Fix changelog mentioning live_upload_preview instead of live_img_preview

---

lib/phoenix_component.ex

`intersperse/1` was missing `@doc type: :component`, so it's showing up under the `Funtions` section instead of `Components`.

docs: intersperse/1 should be marked as component

---

lib/phoenix_component.ex
lib/phoenix_live_view/html_engine.ex
test/phoenix_component/declarative_assigns_test.exs
test/phoenix_component/verify_test.exs
test/support/live_views/components.ex

Related to #2226 
Seems that in the current code in master, the `:map` type was already supported, just was not used for value validation.
I don't know if it was on purpose, because I had to do some special handling on this type (see my addition in  `html_engine.ex`)

Validating :map attributes

---

guides/client/bindings.md
guides/client/js-interop.md

Update `live_*` for `<.link>`.
Adds mention of `phx-page-loading` near other "loading states" docs so it can be found a bit more organically. Unsure if that's the correct syntax to link between guides once it's generated.

Guides: replace `live_patch` with `<.link>`, mention `phx-page-loading` with other loading states

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/support/live_views/components.ex

See https://github.com/phoenixframework/phoenix_live_view/issues/2277

docgen: fix rendering of integer lists & omit "and"/"or" for examples/values with only one item

---

lib/phoenix_component.ex

Currently the example in the documentation actually double renders the `href` attribute, as it is statically declared as well as passed in the `@extra` assign as dynamic attributes.
This merely updates it so that the component takes a `to` assign (similar to the old fashioned `link/2` function from `phoenix_html`), and so that the example is is "technically" correct.
I don't think the browser cares at all about the double attribute, but when I noticed it while reading it had me scratching my head for a moment wondering if it automatically de-duped attributes or not.
I had also thought about removed the static href declaration entirely, but i figured since it's necessary for a valid anchor tag, you'd want it to error if the assign isn't present.
Thanks!

Update assigns_to_attributes/2 documentation

---

guides/server/security-model.md

I was following this documentation but unfortunately the `assign_new` function and its friends have recently moved to `Phoenix.Component`. The `only:` is unnecessary but it feels a bit awkward (maybe?) to bring in everything from `Component` into this `on_mount`.
Hoping this is techically correct 🤞 I can also just `import Phoenix.Component` upon request 😛 (or let a maintainer do it)

Update security model documentation

---

lib/phoenix_component.ex

Code example is missing `:` for `:let`

Fix typo in Phoenix.Component @moduledoc

---

guides/server/security-model.md

This fails `%{"user_id" => user_id} = _session` because session does not contain `user_id`, however it does contain `user_token`.
I'm using:
```elixir
defp deps do
[
{:phoenix, "~> 1.6.13"},
{:phoenix_html, "~> 3.0"},
{:phoenix_live_reload, "~> 1.2", only: :dev},
{:phoenix_live_view, "~> 0.18.3"},
]
end
```

Update sample code for on_mount authentication

---

assets/js/phoenix_live_view/live_socket.js

There seems to be a bug when navigating to the sites root via `JS.navigate/1`, and maybe other functions that use `LiveSocket.historyRedirect`
Can be reproduced by performing `JS.navigate("/")`  
The LV server process crashes with this CaseClauseError:
```
** (CaseClauseError) no case clause matching: %Phoenix.LiveView.Route{path: [], view: ComponentsWeb.HomeLive.Index, action: :index, opts: [action: :index, router: ComponentsWeb.Router], live_session: %{extra: %{on_mount: [%{function: &ComponentsWeb.InitAssigns.on_mount/4, id: {ComponentsWeb.InitAssigns, :default}, stage: :mount}], session: %{}}, name: :default, vsn: 1668894584134865752}, params: %{}, uri: %URI{scheme: nil, userinfo: nil, host: nil, port: nil, path: "/", query: nil, fragment: nil}}
(phoenix_live_view 0.18.3) …
```

Relax regex used during js navigation (redirect)

---

lib/phoenix_live_view/channel.ex
mix.exs
test/phoenix_live_view/integrations/assigns_test.exs
test/phoenix_live_view/integrations/collocated_test.exs
test/phoenix_live_view/integrations/connect_test.exs
test/phoenix_live_view/integrations/elements_test.exs
test/phoenix_live_view/integrations/event_test.exs
test/phoenix_live_view/integrations/flash_test.exs
test/phoenix_live_view/integrations/hooks_test.exs
test/phoenix_live_view/integrations/layout_test.exs
test/phoenix_live_view/integrations/live_components_test.exs
test/phoenix_live_view/integrations/live_reload_test.exs
test/phoenix_live_view/integrations/live_view_test.exs
test/phoenix_live_view/integrations/navigation_test.exs
test/phoenix_live_view/integrations/nested_test.exs
test/phoenix_live_view/integrations/telemetry_test.exs
test/phoenix_live_view/integrations/update_test.exs
test/phoenix_live_view/router_test.exs
test/phoenix_live_view/upload/channel_test.exs
test/phoenix_live_view/upload/external_test.exs
test/support/live_reload_test_helpers.ex
test/support/live_views/reload_live.ex
test/support/router.ex

Here are the complementary changes in the [phoenix_live_reload](https://github.com/phoenixframework/phoenix_live_reload/pull/131) Repo.

Live reloading LiveViews without a hard refresh

---

guides/server/using-gettext.md

Fixes the warning
```
unused import Phoenix.LiveView
```
In the given example, the `RestoreLocale` hook is integrated for all live views by default, so it follows after the `use Phoenix.LiveView`.

[docs] Remove unused import from Gettext for I18n code sample

---

CHANGELOG.md

This entry is missing in master and is only present in the v0.17.12 tag

Add missing entry to changelog for v0.17.12

---

CHANGELOG.md
assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/view.js
assets/test/view_test.js

Tracking form submitted state on each input allows new inputs to be added after a form submit without immediately showing their errors.
Closes #2350

Store submitted state on inputs

---

lib/phoenix_component.ex

Tailwindcss jit cannot handle interpolation, so don't use it in the docs
fixes #2352

Don't use interpolation in docs

---

lib/phoenix_live_view/router.ex

I was going through the docs and spotted some possibly ambiguous code in the examples. This PR updates the code example to try and avoid confusion around plug pipelines, scopes, and live sessions.
I added a wrapping `scope` for the `pipe_through` call so developers do not assume `live_session` will implicitly generate a scope to restrict `MyAppWeb.AdminPlugAuth` to the admin live session routes.
The old example code will apply `MyAppWeb.AdminPlugAuth` to any routes defined after the `live_session :admin` block which may be unexpected for some developers. It's easy to see the wrapping `live_session` block and assume the plug pipeline will be restricted to that `do/end` block. If, for example, a developer copy/pasted the example and then cut/pasted the `live_session :default` block below …

Docs: Reduce ambiguity in live_session example code

---

lib/phoenix_live_view/plug.ex
lib/phoenix_live_view/static.ex
test/phoenix_live_view/router_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2376

Use layout defined in live_session during disconnected render

---

assets/js/phoenix_live_view/dom.js

Browsers are capable of rendering pages with no title but LV breaks if it's missing.

Prevent app failure due to missing `<title>` tag

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

This allows for the params parameter to be send trough to `form_for`, neat when the data source is an atom so you don't have to manually set the value of each input field in your form.
I'm not sure i nailed the doc thought. 
Ref. https://github.com/phoenixframework/phoenix_live_view/issues/2388

Add params for the form component

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

I've seen so many people try to use `<%= for finner <- inputs_for(f, :inner) do %>` without accompanying `hidden_inputs_for(finner)` that I think it makes sense to have a function component mimicing `inputs_for/4`, which also did add the hidden inputs automatically in the past - before `inputs_for/3` was added to improve LV change tracking.
Feel free to rip out once the forms overhaul is happening.

Add `<.inputs_for />`

---

assets/js/phoenix_live_view/live_socket.js

I've encountered similar issue to https://github.com/phoenixframework/phoenix_live_view/issues/2311 and https://github.com/phoenixframework/phoenix_live_view/issues/2276. When I was redirecting from live view to dead view, I was seeing a "disconnected" flash error.
Using `unload` instead of `disconnect` fixes the issue.

Unload socket before redirecting

---

lib/phoenix_component.ex

The enum passed doesn't seem to work as it's a plain list and so it raises (KeyError) key :name not found in: "home".

Fix documentation example for intersperse

---

lib/phoenix_live_view.ex

This information has been removed in the past, but is very useful when we need to know a way to force a nested LiveView re-mount. I don't know if that information was transferred elsewhere. But I think this will save us to spend time trying to figure out how we can do this.
https://github.com/phoenixframework/phoenix_live_view/blob/e4c6f7140d5b8c383e584671a63c14e85e9c26e9/lib/phoenix_live_view.ex#L371-L379

Docs - Adds information on how we can force a nested LiveView to be re-mounted

---

lib/phoenix_component.ex
lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs

We are good on the `update` and `assign_new` front because they do not consider the value equality.

Force assign unchanged defaults

---

assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/live_uploader.js

The files property of an input element is an immutable [FileList][1] object that can only be replaced with another FileList. While we are not allowed to make a new FileList object directly (there is no public constructor), the [DataTransfer][2] object provided by the HTML Drag and Drop API also has a files property of the same type.
For future reference, the DataTransfer API could be used to unify more of the upload paths- the [public constructor][3] is generally available.
For completeness, this change has one undesirable effect: if a user drops multiple files, the text next to the file input will eventually get out-of-sync with the number of pending uploads. This may be solvable in a future update.
Tested on Mac OS Chrome 108, Firefox 108, and Safari 16.2.
[1]: …

Copy FileList on drop event when max_entries: 1

---

lib/phoenix_live_view.ex

The example for [updating items](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#stream_insert/4-updating-items) looks off

Fixup example in docs for `stream_insert/4`

---

lib/phoenix_component.ex
lib/phoenix_component/declarative.ex

When I want to define attributes for a function component from a list, like in:
```
@list_of_attributes ~w(attr1 attr2 attr3 ... )a
for attr_name <- @list_of_attributes do 
attr attr_name, :string
end
```
I get the error:
```
** (FunctionClauseError) no function clause matching in Phoenix.Component."MACRO-attr"/4    
The following arguments were given to Phoenix.Component."MACRO-attr"/4:
#Macro.Env<aliases: [{ChangeMsg, LiveSelect.ChangeMsg}], context: nil, context_modules: [LiveSelect], file: "/Users/max/code/live_select/lib/live_select.ex", function: nil, functions: [{Phoenix.Component, [assign: 2, assign: 3, assign_new: 3, assigns_to_attributes: 1, assigns_to_attributes: 2, changed?: 2, dynamic_tag: 1, focus_wrap: 1, form: 1, inputs_for: 1, intersperse: 1, link: 1, live_component: 1, …
```

move guards in attr macro to __attr__!

---

guides/introduction/installation.md

I was having issues updating a project from 0.17 to 0.18. I kept running into this error:
```
[error] #PID<0.6924.0> running MyAppWeb.Endpoint (connection #PID<0.6922.0>, stream id 1) terminated
Server: localhost:4040 (http)
Request: GET /
** (exit) an exception was raised:
** (CaseClauseError) no case clause matching: "live"
(phoenix_live_view 0.18.13) lib/phoenix_live_view/utils.ex:186: Phoenix.LiveView.Utils.to_rendered/2
(phoenix_live_view 0.18.13) lib/phoenix_live_view/static.ex:251: Phoenix.LiveView.Static.to_rendered_content_tag/4
(phoenix_live_view 0.18.13) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
(phoenix_live_view 0.18.13) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
(phoenix 1.6.15) lib/phoenix/router.ex:354: …
```

Adds live_view macro update required to move to latest 0.18

---

guides/server/using-gettext.md

In gettext session example, take locale from `current_user`.

docs: fix minor bug in gettext documentation code

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

This PR fixes the bug described in #2457, which occurrs when running tests while using `fast_html` instead of Floki's default `mochiweb` parser.
Since this parser follow the [whatg spec](https://dom.spec.whatwg.org/) more closely, empty textareas nodes do not have any value (so: `[]` instead of `[""]`), which caused a `FunctionClauseError` when LiveViewTest parses the HTML Tree, for example on `render_change`.
This PR attempts to fix this by checking if there's only zero or one children in the `textarea` and then interpolates the `children` as the `value`, essentially making the default value be `""`.

Fix form_defaults in LiveViewTest for empty textareas when using fast_html instead of Floki's default HTML Parser

---

lib/phoenix_live_component.ex
lib/phoenix_live_view.ex

When I was working on a LiveComponent which persists multiple assigns to the socket, it wasn't clear from the docs that only the new assign(s) would appear in the first arg of `update/2`. Nor was it clear how to access existing assigns. It makes sense in hindsight, but I want to clarify how the callback works a bit with this PR.

Elaborate on New vs Existing Assigns in `update/2`

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

Currently the default `as: nil` overrides `:as` from `to_form`.

Respect to_form :as option in form field access

---

lib/phoenix_component.ex

The relevant portion of the deprecation warning for `to_form/2` displays as follows on the console:
```
You might do:
<.form :let={f} for={%{}} as={:user ...>
```
This PR includes the missing curly brace for the `as` attribute.

Add missing curly brace to `to_form/2` deprecation warning

---

test/phoenix_live_view/html_engine_test.exs

Remove an unused/non-existing module from html_engine_test.

Fix warnings

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Since that's LV common component it is usually wrapper for `a` element, we don't want extra spaces because of formatting.

Formatter - treat .link component as inline

---

guides/client/form-bindings.md

It rendered the literal `{.info}` before, now it renders the admonition block that was presumably intended

Fix admonition block

---

lib/phoenix_live_view/logger.ex
test/phoenix_live_view/integrations/telemetry_test.exs

This PR updates the formatting used by `Phoenix.LiveView.Logger` to write fewer lines per telemetry event logged. This change applies to both Live Views and Live Components. The same data is logged as before but in a more space efficient way 🙂 
Before:
```
HANDLE EVENT
View: FooLive
Event: "validate"
Parameters: %{"foo" => "bar"}
Replied in 250µs
```
After:
```
HANDLE EVENT "validate" in FooLive
Parameters: %{"foo" => "bar"}
Replied in 250µs
```

`Phoenix.LiveView.Logger`: merge lifecycle, view, and event into one line

---

lib/phoenix_component.ex

When updating to use the new `to_form` function with plain maps I found it hard to understand how to add errors.
I think this makes things a little clearer, but happy to adjust if I'm misunderstanding the usecase

Add example of how to pass errors with map `to_form`

---

guides/introduction/installation.md

This makes the loading indicator delay much easier without needing a setTimeout call
From the topbar docs:
```
You can use topbar.show(delayMillis) to delay the progress bar. If hide() is invoked within the delay period, topbar won't show up at all. This can make the user experience feel smoother in some cases.
```
http://buunguyen.github.io/topbar/

Docs update: topbar.show accepts a parameter to delay loading indicator

---

guides/server/deployments.md

changed link to absolute; relative link as written was leading to 404

[Docs] fix broken link to form-bindings doc in Deployment doc

---

CHANGELOG.md

We had a couple of LiveComponents where we were assigning `live_action` which now raises in 0.18.17. Then I found #2441, which is a great addition!

Add reserved assigns validation to changelog

---

lib/phoenix_live_view/js.ex

Fix JS.exec `:to` documention

---

lib/phoenix_live_view/js.ex

I found a few spots in the docs that use `phx-click` on a `div`, and I think it'd probably be better to demonstrate the proper way you should use `phx-click`: ie., it should probably be on an element with the proper aria role.

Update docs to use button tag instead of div

---

guides/server/assigns-eex.md

This is a proposed change to increase the clarity of the section, rearranging sections so all needed definitions hae already been explained, to make this sentence say 
> Those values can be accessed in the LiveView as `socket.assigns.name` but they are accessed inside HEEx templates as `@name`.
instead of 
> Those values can be accessed in the LiveView as `socket.assigns.name` but they are accessed inside LiveView templates as `@name`.
Also, I believe that "socket state" is a more widely understood term for what the assigns object does, so changed the section title accordingly.

[Docs] improve clarity of HEEx docs section

---

lib/phoenix_component.ex

Unsure if this is an oversight or intentional or just something with no nice solution.
Given `:for={a <- 0..10, b <- 0..a}`, we get `syntax error before: ','` because `Code.string_to_quoted` cant handle it.
https://github.com/phoenixframework/phoenix_live_view/blob/b02d7c255f7939c08ad46ac39bc6bbcaa52178bb/lib/phoenix_live_view/tag_engine.ex#L729
https://github.com/phoenixframework/phoenix_live_view/blob/b02d7c255f7939c08ad46ac39bc6bbcaa52178bb/lib/phoenix_live_view/tag_engine.ex#L831-L833
I think it's at least *possible* to construct `"for #{expr}, do: nil"` to send to the parser, then adjust  `validate_quoted_special_attr!` to handle multiple for-generator forms *and* adjust the `handle_special_expr` code to de/reconstruct the parsed expression and replace the `do: nil` with the correct …

document heex :for does not support multiple generators

---

lib/phoenix_component.ex

I had a discussion with two other people about how we all were stuck on getting form validations to show in the new form world.
I noticed there's now a section on covering this but I think it should be included in the `to_form` documentation since 3 of us missed it I imagine others might as well.

Make note on errors in changesets more explicit in Component docs

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs

Make "Global attributes are accepted." less obstructed by turning it into a list item, to the bottom of the list.

Turn global attribute into list item

---

lib/phoenix_live_view.ex

`configure_stream` should be `stream_configure`?

Fix wrong function name in documentation

---

lib/phoenix_live_view.ex
test/phoenix_live_view_test.exs

The new `stream_configure/3` function was not properly using the result of a call to `ensure_streams/1`
This was resulting in an error `(KeyError) key :streams not found %{...}`, during any call to `stream_configure/3`

Ensure that a `streams` struct is assigned, before configuration

---

guides/server/live-layouts.md

Small documentation typo in live layouts guide: `{ok, ...}` => `{:ok, ...}

---

lib/phoenix_live_view/js.ex

Correct the order of the transition CSS classes passed to the `:transition` option (should be opposite to the `JS.show/1`).

[Doc] Correct the example for JS.hide/1

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/event_test.exs
test/support/live_views/events.ex
test/support/router.ex

Currently LiveViewTest can't test views or components with something like:
```html
<button phx-click={JS.push("event_a") |> JS.push("event_b")}/>
```
This PR adds support for that by collecting all events and passing them through a reducer.
This PR retains the slightly unexpected current behaviour of merging `phx-value-x` attributes into `JS.push` data but only for the first `JS.push` event. It also preserves the current behaviour of using `phx-target` if present for `JS.push`, for all events.

RFC: Support multiple JS.push events in LiveViewTest

---

lib/phoenix_live_view/js.ex

`JS.push` will include any `phx-value-*` values from the source element and will also target any `phx-target` on the element if given. These values are overwritten by any value or target given to the actual function.
There are some quirks with forms however, where they never attach any `phx-value` attributes, and they have a particular quirk with `phx-target` where `phx-change=JS.push` requires *both* `phx-target` and `target: t` for the message to be correctly sent.
As such, I have left forms behaviour undocumented as I'm unsure what the intent is.
See reproduction of form behaviour and examples of generic buttons:
<details>
<summary>code</summary>
```elixir
server: true,
live_view: [signing_salt: …
```

Document JS.push's phx-value and phx-target behaviour

---

lib/phoenix_component.ex

Now that attr. is used for the live_img_preview component (from 19b7784dfef956a2daff1b4e6e264d98325ca440) additional code in the live_img_preview appears unnecessary and to be causing #2608 . The validation that there is an entry assign is performed automatically by attr.

Remove more previously deprecated functionality from live_img_preview (#2608)

---

lib/phoenix_live_view.ex

Add an admonition about the perils of not having phx-update="stream" on the immediate parent of a stream.

Copy for admonition for users about the location of phx-update="stream"

---

guides/server/uploads.md
lib/phoenix_live_view.ex

I was working on a file upload functionality today and I noticed my SVG images weren't being rendered (other images were working fine, though).
I started watching the [Phoenix LiveView Uploads Deep Dive](https://www.youtube.com/watch?v=PffpT2eslH8) to see if there was something I was missing and I noticed one thing: Chris was passing the file extension to `dest` there.
I gave it a try to see if this would fix the SVG rendering issue and it did work. So, I'm wondering if there's something I'm missing here or if we should always add the file extension to the path.
I'm adding it to the docs but feel free to close this PR if not having the extension is intentional and/or I'm doing something wrong.

Add file extension example to file upload

---

lib/phoenix_live_view/test/live_view_test.ex
lib/phoenix_live_view/test/structs.ex
test/phoenix_live_view/upload/directory_test.exs
test/support/live_views/upload_live.ex

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2628
Allow the `file_input` test helper to set an upload entry's relative path. This is normally set by browsers when using [the webkitdirectory attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) on a file input, in order to upload an entire directory in one go.
Note that while testing this PR on main, I found [a regression](https://github.com/phoenixframework/phoenix_live_view/issues/2631) that removes support for the `webkitdirectory` attribute in production code.

file_input/4 can set an entry's relative path

---

lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

The `put_submitter/2` test helper makes it possible to declare which element (or selector) will initiate the form's submit event on the client. It is meant to mimic the behavior of the [SubmitEvent: submitter property | MDN](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter).
For example, given a LiveView form with two submit buttons:
```heex
<form id="form" phx-change="change" phx-submit="submit">
<button id="blue" name="btn" value="blue">Blue</button>
<button id="green" name="btn" value="green">Green</button>
</form>
<p :if={@color}>Color: <%= @color %></p>
```
...and the following `handle_event` callback:
```elixir
def handle_event("submit", %{"btn" => color}, socket) when color in ["blue", "green"] do
{:noreply, assign(socket, :color, color)}
end
```
...then one …

Add LiveViewTest.put_submitter/2

---

lib/phoenix_component.ex

Remove unnecessary list.
The original example causes the following error.
```elixir
to_form(%{"search" => nil}, errors: [search: [{"Can't be blank", []}]])
```
```
** (FunctionClauseError) no function clause matching in FalconWeb.ErrorHelpers.translate_error/1
```

[Doc] Correct the usage example in the function doc of to_form/2

---

lib/phoenix_live_view.ex

In [stream/4](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#stream/4) docs, in subsection **Limiting a stream**, there's a link to **scroll events guide**.
The current link is
```
https://hexdocs.pm/phoenix_live_view/bindings.html##scroll-events-and-infinite-stream-pagination
```
And it should be
```
https://hexdocs.pm/phoenix_live_view/bindings.html#scroll-events-and-infinite-stream-pagination
```
(Double ##)

[Docs] Fix link typo

---

lib/phoenix_live_view/test/live_view_test.ex

Per a [brief discussion on Mastodon](https://merveilles.town/@peregrine/110469721567235316), this replaces the hardcoded default timeout of 100 milliseconds on message-receiving test functions (`assert_patch`, `assert_redirect`, `assert_push_event`, and `assert_reply`) with a lookup of ExUnit's `assert_receive_timeout`.
This makes the behavior of `Phoenix.LiveViewTest` more consistent with `Phoenix.ChannelTest`, where `assert_receive`, `assert_push`, `assert_reply`, and `assert_broadcast` all delegate to the ExUnit config for their default timeout.

Use ExUnit's assert_receive_timeout as the default receive timeout

---

guides/introduction/installation.md

Hi:
This just makes the docs agree with what is currently produced by the generators (i.e., from `mix phx.new my_app`)
-- Greg

Minor documentation update

---

lib/phoenix_component.ex

This code is working currently in my project, the input is actually becoming disabled when I write it like this:
```elixir
<.live_file_input
upload={@uploads.image}
disabled={not @can_be_saved}
/>
```
The problem is that I got the compilation warning that says the following:
```
warning: undefined attribute "disabled" for component Phoenix.Component.live_file_input/1
lib/quiz_arena_web/live/quiz_live/steps/questions.html.heex:127: (file)
```
The warning appears after I switched to the newest live_view:
```elixir
{:phoenix_live_view, "~> 0.19.1"}
```

 Add 'disabled' to accepted file input attributes

---

lib/phoenix_live_view/router.ex

See https://github.com/phoenixframework/phoenix_live_view/pull/2654
Think this might help address confusion myself and others have had about how to solve a particular use case. When I originally read these docs it wasn't clear to me it could be accessed in the LiveView. Not sure if it should also specifically reference Phoenix.Router.routes/route_info?

Elaborate use case for route metadata in live/4 docs

---

lib/phoenix_live_view/test/client_proxy.ex

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2693
I processed a situation, where "from" value is invalid for using by `GenServer.reply/2`.
I have also explicitly used `:missing_from` for such cases.
Should I replace it back with `nil`, or create a module attribute, like `@missing_from :missing_from`?
I was not able to reliably reproduce the issue, so did not create any tests for it.

Process case when "from" is missing for proxy callback

---

lib/phoenix_live_view/test/live_view_test.ex

brought about by: https://github.com/phoenixframework/phoenix/pull/5488
Removing the 3rd argument is backwards compatible since `connect_info` still defaults to `%{}`.

Fix Phoenix.ChannelTest.connect/3 warning

---

lib/phoenix_live_view.ex

Fix a missing bracket in the documentation for `stream_configure`.

[fix] add missing bracket to stream_configure

---

lib/phoenix_live_view/test/client_proxy.ex
test/support/live_views/elements.ex

From [hexdocs.pm/phoenix_live_view/live-layouts.html#updating-document-title](https://hexdocs.pm/phoenix_live_view/live-layouts.html#updating-document-title)
> Because the root layout from the Plug pipeline is rendered outside of LiveView, the contents cannot be dynamically changed. The one exception is the <title> of the HTML document. Phoenix LiveView special cases the @page_title assign to allow dynamically updating the title of the page, which is useful when using live navigation, or annotating the browser tab with a notification.
The current implementation of `Phoenix.LiveViewTest.page_title/1` searches only for a single <title> tag.
The assumption that only one `<title>` tag exists on the page does not hold if the page also includes a title tag within an `<svg>` element. The …

Fix Phoenix.LiveViewTest.page_title/1 to allow for <title> within <svg>

---

lib/phoenix_component/declarative.ex

Add [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) according to [the list of global HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#inert).

Add 'inert' to the list of global HTML attributes

---

lib/phoenix_live_view/socket.ex

Hello,
This is a small docs update in reference to the following patch: https://github.com/RiverFinancial/phoenix/commit/bb9a0a4030c61bfb51a4de2b91677b3652926afa
Apologies if this is documented elsewhere, I've been struggling to find it.
Thanks

Document socket session options at runtime

---

assets/js/phoenix_live_view/dom.js
assets/test/dom_test.js

Hi there,
I recently chased down a bug in our repo where clicking on a link in a modal which opened a new tab caused the live socket to disconnect, and the modal could not be dismissed. It turned out that I had copy-pasted from a stack overflow answer about making a link open in a new tab which had `target=_BLANK`, where currently the code only checks for the lowercase `target=_blank`.
Sorry to jump straight to a PR with no issue, but it seemed like the same amount of work to write an issue as to submit a PR.
Thanks!
edit: A link to the spec, specifying that that the target value should be a case-insensitive match: https://html.spec.whatwg.org/multipage/document-sequences.html#valid-navigable-target-name-or-keyword

Fix wantsNewTab with uppercase target

---

lib/phoenix_live_view.ex

Update docs for `stream` to make it clear that this function can be used to insert items into an existing stream in addition to assigning a new stream.

Update docs for `stream`

---

assets/js/phoenix_live_view/live_socket.js

Fixes issue https://github.com/phoenixframework/phoenix_live_view/issues/2615
If you navigate from one live view to another, and that liveview immediately does a patch redirect, the navigate will override the patch because it runs its browser history pushes in a browser animation frame that runs on the next repaint.
This change simply checks if the linkRef has changed by the time the animation frame runs, and if it has, we don't need to run the browser updates. We still call the "onDone" from the withPageLoading wrapper to make sure the events get fired successfully.
Image shows that it directs from second page directly to home with the query param set
```elixir
server: true,
live_view: [signing_salt: …
```

fix: navigate callback running after patch

---

lib/phoenix_component.ex

Just noticed these as I was reading through the source.

Fixes typos in phoenix_component.ex docs

---

lib/phoenix_live_view/router.ex

I think this is quite important info, so it'd be awesome to have it in the docs. 🙃 
This is the rendered docs:

Add docs about request method to live/4

---

assets/js/phoenix_live_view/view.js

I have a form using phx-change with a single hidden input in (the input's value is updated by a hook), and getting `ReferenceError: Cannot access 'input' before initialization` on reconnects. I think this should fix it
I'm not sure on what the best way to write a test for this is - I can't see an existing one for pushFormRecovery and couldn't figure out the proper way to trigger/assert the function

Correctly pick first non-hidden input in pushFormRecovery

---

guides/client/bindings.md

There was a syntax error in the infinite scroll code -- A variable was hanging out where it shouldn't be.

Get rid of error in Scroll Bindings Guide

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/support/live_views/components.ex

The codebase contains code that clearly shows there was intent to support both `doc` and `include` options for an attribute of type `:global`, but after adding some test coverage, it became evident it wasn't being reached.
After coverage was added and the bug was fixed, I took the liberty to refactor the code a bit.
Fixes #2709

Fix @doc generation for :global attribute type (fixes #2709)

---

lib/phoenix_component.ex

This is to help other dummies like me: 
I just got stuck for some time trying to use `inputs_for/1`, because I missed the fact that the `list` in `list[emails_sort][]` etc. referred to the parent schema's name.

Use less generic name for parent `inputs_for/1` example

---

lib/phoenix_live_view.ex

noticed a typo; this is my first PR, so please feel free to contact me if needed

Changed 'render' to 'renders' because 'renders' agrees with the singular 'a process'

---

lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/integrations/navigation_test.exs
test/support/router.ex

This fixes the problem described in #2798.

Allow Phoenix.LiveViewTest.live_redirect to navigate to nested paths

---

assets/js/phoenix_live_view/view.js
assets/test/view_test.js

When using the `JS` module to set `phx-change`, the call to `formsForRecovery` on frontend will fail due to not passing the attribute value correctly into a css selector.
Escaping is necessary for the css selector to become valid.
`CSS.escape` would be a more foolproof approach but jest does not support it in node env in which it runs. Not sure if it supports it in jsdom.
In that case, our best bet would be to stub `CSS.escape` and spy on it.
If that is the preferred approach here, I would be happy to do it some time tomorrow.
Resolves #2252

Sanitize phx-change attribute in formsForRecovery (#2252)

---

assets/js/phoenix_live_view/live_socket.js

This fixes a potential bug whereby a `phx-change` could be skipped, for example in the following scenario:
* some javascript code in the application triggers a `change` event without a prior `input` event. This triggers the `phx-change` hook (good)
* user then types a single letter. The `input` event would be ignored and `phx-change` is not triggered.

Tweak binding of "phx-change".

---

lib/phoenix_live_view.ex

I just noticed this small typo when I was looking through the docs. Excited to use the async assigns!

fix typo in async docs

---

lib/phoenix_live_view.ex

From our slack discussion, here is a PR to warn folks about stream limits not being enforced on the first render.
Let me know if you see any issues.
Cheers.

Add note about not enforcing stream limit on first mount.

---

lib/phoenix_component.ex

When needing to use this component multiple times, we need a way to override the id.

Add id attribute for live_img_preview

---

assets/js/phoenix_live_view/dom.js

If a link is inside of a `<div contenteditable="true">`, clicking on it will simply focus the `contenteditable`, not navigate to the link, however live_socket behaves as if we are about to navigate to that link and unloads the socket.
(see issue #2670)

Don't unload if the click occured inside of a contenteditable

---

lib/phoenix_live_view/channel.ex
test/phoenix_live_view/integrations/params_test.exs

I was recently updating my project from 0.17.5 and noticed that the fragment never gets stripped from a URI on redirects, so it ends up appended to the last of the query params, breaking some of my tests. I must be the last person on Earth to be using fragments, but they're part of the spec, so this should be supported :)
I added a unit test, but I'm not sure it's adequate or in the right place, so please let me know if there's something that needs changing.

Remove fragment part from query on redirects

---

lib/phoenix_live_view/test/upload_client.ex

I didn't find a good place to test those changes. 
This should prevent surprises, where `render_upload(…, percentage)` results in a different percentage of actually uploaded file.

Improve effort in keeping render_upload provided percentage

---

assets/js/phoenix_live_view/dom_patch.js

From MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit
> A form control (such as a submit button) with a `name` or `id` of `submit` will mask the form's submit method. Trying to call `myForm.submit();` throws an error "submit is not a function" because in this case `submit` refers to the form control which has a `name` or `id` of submit.
We can fix this by bypassing the form's `submit` method and instead using the `submit` method from the form's prototype.

Allow inputs/buttons with id="submit" when using phx-trigger-action

---

lib/phoenix_live_component.ex
lib/phoenix_live_view.ex

Update_many is used in favor of preload which has been deprecated.

Remove references to the deprecated preload callback

---

lib/phoenix_live_view.ex

Fix missing brackets in the implementation of `assign_async` examples.

Fix missing brackets in the documentation examples

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Resolves #2838 
`HTMLFormatter` is adding a newline between `<textarea>` tags, which adds unexpected whitespace to the rendered output.  This can be reproduced by setting the line length on the following test:
```elixir
assert_formatter_doesnt_change(
"""
<textarea></textarea>
""",
line_length: 5
)
```
The culprit is a check for `buffer != []` which fails the test when present but passes when the check is removed.

Fix HTMLFormatter for textarea

---

lib/phoenix_live_view/router.ex

I got quite confused about the fact that my two live routes defined in a router without any `live_session` were able to live redirect between each other without an additional HTTP request.
I think this docs improvement could help further readers/users.
Also, I can add similar sentence to the https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#link/1 docs if you think it could help even more.

Improve Router.live_session/3 docs

---

assets/js/phoenix_live_view/view.js
assets/js/phoenix_live_view/view_hook.js

Currently calling `this.uploadTo(phxTarget, "file", ...)` looks up upload input with `name="file"` in the whole LV and fails if there are many. This changes the lookup to respect `phxTarget`, so that multiple LC on the page can use the same name.

Scope upload input lookup in uploadTo

---

lib/phoenix_component.ex

I noticed a small typo when I was recently reading “The default slot” section in the Phoenix.Component docs and it causes me a tiny confusion whether I skip something in the reading or not. Great docs so far though!

fix typo in phoenix component default slot docs

---

assets/js/phoenix_live_view/view.js

This fixes an issue we discovered at Felt, which was introduced in #2490.
The symptoms were as follows:
- Given a form with an image upload, if you waited until the upload completed before submitting the form, the submission would work as expected.
- However, if you submitted before the upload completed, you'd see the submission correctly wait until the upload hit 100%, then you'd get a JavaScript crash and the app would go dead.
The JavaScript console produced an error like this in release:
```
TypeError: r.hasAttribute is not a function. (In 'r.hasAttribute("name")', 'r.hasAttribute' is undefined)
```
The error in dev, of course, was more descriptive:
```
submitter.hasAttribute is not a function
Call Stack
 serializeForm  node_modules/phoenix_live_view/priv/static/phoenix_live_view.esm.j …
```

Fix frontend crash on form submissions that wait for uploads to complete

---

lib/phoenix_component.ex

I was looking for the `async_result/1` docs and was surprised to find it under the section Functions rather than Components in the [`Phoenix.Component` module docs](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#async_result/1). After investigating, it seems like that's because there's a missing `@doc` attribute with `type` metadata i.e. `@doc type: :component`.

Specify doc type as component for async_result/1

---

lib/phoenix_live_component.ex

When working with start_async inside a live component, I get the following error
```elixir
warning: got "@impl Phoenix.LiveComponent" for function handle_async/3 but this behaviour does not specify such callback. The known callbacks are:
* Phoenix.LiveComponent.handle_event/3 (function)
* Phoenix.LiveComponent.mount/1 (function)
* Phoenix.LiveComponent.render/1 (function)
* Phoenix.LiveComponent.update/2 (function)
* Phoenix.LiveComponent.update_many/1 (function)
```
As the code itself works just fine, I assume that it's just the behaviour callback missing, so this PR adds it.

add handle_async as callback to live component behaviour

---

lib/phoenix_live_component.ex

Funny enough, I was preparing a presentation about phoenix performance and my N+1 example was almost exactly the same here and when I realised it I tried copying the code and then realised the minor typo.

Minor typo in update_many documentation

---

lib/phoenix_live_view/live_stream.ex

Since are configured separately with `configure_stream/3`, the warning message about a missing `:id` key when using the default DOM id should explain that a bit more precisely. Just a small thing.

Better error msg on missing default id in streams

---

lib/phoenix_live_view.ex

The function docs all reference "songs" but these 2 examples use "posts".

Update stream/4 doc example reference, posts -> songs

---

assets/js/phoenix_live_view/rendered.js

Follow up to #2891. We don't want to assume id is the first attribute (693497d9fa49247c8739830dbe81eb7cc57c4e37), so we skip other attributes.

Generalize DOM id parsing on patch

---

guides/client/js-interop.md

In JS interp guide, add `javascript` to JS code block. And use `"` instead of backquote (`) for event string.

Add language to javascript code block

---

guides/server/uploads.md

Some confusion around uploads surfaced on the forums again recently so I improved the docs a bit to cover it better.  There was already a note about it but there was a typo, it didn't quite follow the style already there, and I felt it needed a bit more prominence.
I also added a note about live reload picking up the `uploads/` directory as that was a cause of frustration for me recently.  I actually didn't figure it out until someone asked a similar question on the forums and I realized this was my problem when I thought I just had a small bug somewhere 😅
I also reiterated the note about creating `priv/static/uploads` in the appendix.

Improve live upload docs

---

test/phoenix_live_view/tokenizer_test.exs

I was investigating a bug and realized there's no test for components in the tokenizer. Seems like it would be helpful to add those tests.

Tokenizer - add tests for local and remote components

---

lib/phoenix_live_view/channel.ex
test/phoenix_live_view/integrations/telemetry_test.exs

As discussed in [this thread](https://elixirforum.com/t/more-telemetry-events-for-liveview/59388) this PR introduces a new telemetry span for the LiveView render cycle.
The update/update_many span will be added in another PR.
I haven't added any docs on that yet, wanted to start with the core code changes to allow us to continue with the discussion. If we think this makes sense I can put some effort in the  docs for this new telemetry events.
I included force? and changed? metadata because is low hanging fruit and it can be interesting (maybe to count how many forced renders are there for each live view.
I also included the diffs, so one could, for example, count how many non-forced events that params have changed resulted in empty diffs.
By wrapping the calls to `Diff.render`, we make …

Emit live_view render telemetry span events

---

lib/phoenix_live_view/diff.ex
test/phoenix_live_view/integrations/telemetry_test.exs
test/support/live_views/components.ex

The second part of what was discussed on [this thread](https://elixirforum.com/t/more-telemetry-events-for-liveview/59388). This together with #2907 will already give good hooks for traces to be able to correlate nested component renders.
For this one, I decided to group cid, socket, assigns and whether the component is new or not in a list of maps to make life easier for whoever is consuming this.
I took the opportunity to do a slightly refactor to make the "shape" of `assigns_sockets` uniform regardless of whether the component have `update_many` exported or not. This was done simply by just adding `{new_assigns, socket}` to the assigns_sockets in the inner reduce and then calling update after inside a `map` call.

Add live_component update telemetry event

---

CHANGELOG.md

In #2546 HTML attributes stopped being dasherized. This is a breaking change that was released on Phoenix LiveView 0.19.0 but not documented in the CHANGESET. 
As [suggested](https://github.com/phoenixframework/phoenix_live_view/issues/2545#issuecomment-1810330291) by @jose this PR updates the CHANGELOG to document this change so it won't caught others as a surprise.

Document HTML attrs dasherization breaking change in CHANGESET

---

guides/server/telemetry.md

This adds to the Telemetry docs information about the new events introduced in #2907 and #2914.

Add docs about new telemetry events

---

lib/phoenix_live_view/router.ex

Got tripped up by the wording a bit.

Small wording change for 'live_session' docs

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/diff.ex
test/phoenix_live_view/integrations/event_test.exs

Previously, there was no way to handle both `push_event` and `push_redirect` occuring in the same callback. The redirect would prevent the events from being sent. This commit checks the diff for any new events, and if they exist, sends them over the channel.

Push pending events before redirecting

---

lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/html_engine_test.exs

Effectively rewrites all of these:
```heex
<div {["data-counter": @counter, "data-static": "static"]}>
<%= @counter %>
</div>
<div {[{"data-counter", @counter}, {"data-static", "static"}]}>
<%= @counter %>
</div>
<div {%{"data-counter": @counter, "data-static": "static"}}>
<%= @counter %>
</div>
<div {%{"data-counter" => @counter, "data-static" => "static"}}>
<%= @counter %>
</div>
```
into
```heex
<div data-counter={@counter} data-static={"static"}>
<%= @counter %>
</div>
```
so that diffs are sent for individual attributes.

Inline dynamic attributes at compilation time if possible

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/async.ex
test/phoenix_live_view/integrations/start_async_test.exs
test/support/live_views/general.ex

I'm in the process of migrating a LV that currently starts async tasks using Task.async to `start_async`, but stumbled across the requirement for the key to be an atom. When starting tasks dynamically, e.g. one task for a list of users, I'd like to name these tasks with more complex keys like `{:user, USER_ID}`. Currently one would need to create new atoms (that's a no go), but still would not be able to pattern match in `handle_async`.
I created this PR to allow arbitrary keys when using `start_async` and it seems to work just fine. Code like this is possible now:
```elixir
defmodule MyLiveView do
use Phoenix.LiveView
users = [1, 2, 3]
socket = Enum.reduce(users, socket, fn user, socket ->
start_async(socket, {:user_details, user}, fn ->
end)
end) …
```

relax key requirements for start_async

---

assets/js/phoenix_live_view/rendered.js
assets/test/modify_root_test.js

So, I had a very weird bug with a live component that got destroyed on updates in some cirumstances (lv latest main). After morphdom applied the patches, the wrapping div of the live component that contains the `data-phx-component` attribute was replaced with the inner element. Consequently, any events targeting the live component failed client side with the error `no component found matching phx-target of 3`.
I dug very deep to find out that it relates to https://github.com/phoenixframework/phoenix_live_view/pull/2891. It would not happen when the PHX_MAGIC_ID is checked first.
But this was not to root cause. Actually, `modifyRoot` would move the inner elements id to the parent element when phx-skip is true. This PR tries to fix this by first checking if the HTML tag is already closed …

fix live components being destroyed in some circumstances

---

lib/phoenix_live_view.ex

https://elixirforum.com/t/push-event-followed-by-push-redirect-does-not-call-the-javascript-hook/35184
As per this thread the `push_event` won't work if there's a push_navigate on the socket.

Update docs, to show the edge case for push_event

---

assets/js/phoenix_live_view/js.js
assets/js/phoenix_live_view/live_socket.js

Augments the `phx-click-away` feature to account for elements outside the viewport (see https://codepen.io/sevensidedmarble/pen/LYqmGzp?editors=1111) and [associated issue](https://github.com/phoenixframework/phoenix_live_view/issues/2929) for more details. Closes #2929.

Add viewport check to click away

---

assets/js/phoenix_live_view/aria.js

This PR solves [this](https://github.com/phoenixframework/phoenix_live_view/issues/2917) issue. Basically, it seems the code was taking tabindex to mean something it doesn't. Negative tabindexes are programatically focusable, and they should be treated as such by isFocusable.
There's a secondary issue here which is that this code also seems to be considering all elements with positive tabindexes interactive, which is not what a positive tabindex means. I've chosen not to change that as it is outside the scope of my original issue, but I do think the `el.tabIndex > 0` check should be removed as it is, in my opinion, a bug.

fix negative tabindex handling when determining focusability

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

This should fix #2816. 
Let me know if there is a better way to solve this. After poking around and investigating #2816, I found that the reason why streams wouldn't properly reset was actually because the `data-phx-stream` attribute wasn't set. 
Because the reset functionality in tests depended on this, it meant if you streamed more content after adding stuff, it could never be reset again. Instead, I added a check so that items that are being appended will make sure to have their `data-phx-stream` attribute set to the correct stream ref.

Set `data-phx-stream` attribute on appended stream items in test cases

---

lib/phoenix_component.ex

> **Note**
> Edit: its a feature, not a bug. So I'll just clarify the docs
---
`<.async_result />` component displays the stale result instead of the `<:loading/>` slot after calling `assign_async/2` more than once
- The `async_result` component prioritizes rendering the result (or stale result) if the `ok?` key is `true` 
- `AsyncResult.loading(existing, keys)` doesn't reset the `ok?` key to `false`.
Therefore the loading state is never shown after re-calling `assign_async`.
Loading a heavy report based on a filter form. The current behaviour of showing only the first loading leads to a bad experience because the user will just see the stale data until the new data replaces abruptly.
```elixir
def handle_event("filter",  params, socket) do
case Filter.validate(params) do 
{:error, …
```

docs: clarify <.async_result/> rendering precedence of stale result over loading and failed states

---

assets/js/phoenix_live_view/live_socket.js

Handle `href` not being a string in all cases when using `link` component

---

guides/client/uploads-external.md
lib/phoenix_live_view.ex

I recently ran into an issue where I wanted to return an error from my presign_url function when doing external uploads, and the only way I figured out how to do so was to find where it was executed inside of the upload channel.
This could certainly be more clear how it wires into an actual live view, but at the bare minimum explains the two return values that won't crash the channel.

Clarify return values of :external upload functions

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/dom_patch.js

This PR optimizes the initial page render for pages containing thousands of inputs; instead of calling `DOM.all` for each input, we build a selector to match all inputs and query the DOM.
From my testing, this has reduced the page rendering time from over 30 seconds to 4-5 seconds.

Optimize maybeHideFeedback for initial page render

---

lib/phoenix_live_view/test/dom.ex

Today when running tests, render_diff parses each live component with Floki to add the data-phx-component attribute. This parse has a significant cost on tests with a lot of live components. 
The project I'm working on has some pages with a large number of nested live components used to dynamically create a form, and all of this components get rerendered on every form change (someday we'll fix this 🤞). 
This PR modifies this diff rendering to use Regex.replace instead of Floki to add the data-phx-component attribute.
With this change the time to run the test for the page mentioned above went from 12.3 seconds to 5.2 seconds, and the full test suite with `--max-cases 1` went from 192 seconds to 170 seconds.

Avoid parsing components on test render_diff

---

assets/js/phoenix_live_view/rendered.js
lib/phoenix_live_view/test/dom.ex

We also use the regex on the JavaScript side,
so it provides better validation it works as
desired.

Sync and improve regex

---

lib/phoenix_live_view/channel.ex
test/phoenix_live_view/integrations/start_async_test.exs
test/support/live_views/general.ex

Fixes #2878
Fixes #2875 
Hi there,
I tried to implement support for redirects and put_flash in `handle_async`. I'm not quite sure if I did everything correct. Basically, I first tried to understand the flow of the `handle_event` callback and then tried to adapt it for `handle_async`.
I added some tests and everything seems to be alright.

support redirects and put_flash in handle_async/3

---

assets/js/phoenix_live_view/view.js

This PR fixes the InfiniteScroll hook (phx-viewport-top/bottom) not being applied after a LiveView patch navigation.
As I'm not really into the LiveView Javascript code, I'm not sure if that is the correct way to fix this, so please feel free to close this PR if it's wrong :)
Fixes #2667
Fixes #2896

Add InfiniteScroll hook after patch, fixes #2667

---

assets/js/phoenix_live_view/js.js

By checking if the push target is connected, instead of the executing view, we allow dead views to push events to their embedded live views.
The JS.push `:target` option must be given, otherwise the effect is a noop.
I am afraid I could not see how to test a deadview-with-liveview in the existing framework.

Support JS.push(target: lv) from deadviews to embedded liveviews

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/view.js

The `data-phx-ref` and `data-phx-ref-src` attributes were removed from live file input elements, therefore the `phx-change-loading` class was never removed.
Fixes #1609
Disclaimer: I'm not sure if this is the correct solution.

Try to fix `phx-change-loading` from sticking to live file inputs

---

assets/js/phoenix_live_view/dom_patch.js

Hi there, this PR should address #2895.
I added a single file script to reproduce:
```elixir
server: true,
)
Mix.install([
{:phoenix, "~> 1.7.10", override: true},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
])
end
defmodule Example.HomeLive do
use Phoenix.LiveView, layout: {__MODULE__, :live}
socket
|> stream(:items, [%{id: "a", name: "A"}, %{id: "b", name: "B"}, %{id: "c", name: …
```

Fix order of stream elements when using stream reset (fixes #2895)

---

assets/js/phoenix_live_view/dom.js

When a select input has the focus, such as when an user is changing a values of a select, then we want to apply the changes that come from the server. This was initially disabled specifically for FF as Brian's comment but that might not be an issue anymore. We just installed a new version of FF and it works ok now.
context: We started this investigation as we have a form with a regular `phx-change` validation with a required constraint and the css classes on errors were not applying on the select. We saw that the server was sending those changes but the js part was not applying those because of condition on the `mergeFocusedInput`.
We initially tried to just apply a new `id` to the select (based on the select value) but that did not work nice as the `phx-no-feedback` class was not being …

Allow select html tags to apply diff changes on focus

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js
lib/phoenix_live_view/js.ex
test/phoenix_live_view/js_test.exs

I've been implementing a live view app and came across an instance where I wanted to toggle a class, not simply add or remove it. 
I _could_ simply store the state in a live view component or on the html tag itself (to decide if I want to remove or add), but it seemed like maybe a toggle would be nice to have.
~~**I haven't added any function @doc comments-- yet**. If `toggle_classes` isn't the direction the live view team wants to go with, then feel free to close this PR. Otherwise, if it looks good then I'll also add the documentation too (something similar to add_classes or remove_classes)~~ 👍 
Here's a simple use case where toggle adds or removes a class "dark" which could be used for darkmode:
https://user-images.githubusercontent.com/3220620/139871078-3f4f5f6c-a53b-4ef8-944c-a5a8b291 …

feat: toggle_classes (updated 2021/01/08)

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

`Phoenix.HTML.FormData.to_form/4` allows for arbitrary protocol-specific options to be passed in the fourth argument. `Phoenix.Component.inputs_for/1` currently only supports options specific to the protocol implementation for `Ecto.Changeset`. This PR adds a new `options` attribute that can be used to pass any additional options for other implementations.
Context: `Flop.Phoenix` implements the `FormData` protocol for the `Flop.Meta` struct and relies on a `fields` option to be passed. This is currently only possible with the `inputs_for/4` function that was moved to `PhoenixHTMLHelpers`, but not with the `inputs_for` component.
Relates to https://github.com/woylie/flop_phoenix/issues/299.

add options attribute to inputs_for/1

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/live_socket.js

Fixes #2756
@chrismccord Grabbed this one for me as it seemed very simple to fix
Let me know what you think. Glad to iterate towards a better patch
I don't like passing null to `this.transitionRemoves` but it should be ok.

Fix issue with sticky remove transitions on push_navigate

---

lib/phoenix_live_view/test/live_view_test.ex

This is the first piece that needs to change to allow LiveView Native to utilize the LiveView test harness.
The format, after the LV render is complete, is being asserted as `html`. This PR changes that presumed format and will assert the content type based upon the format that the `conn` is set to.
However, there is a larger issue: `Phoenix.LiveViewTest.DOM` is forcing a downcase of all tag names. Whereas LiveView Native templates adhere to a type sensitive casing that matches the upstream UI framework it is targeting. For example, in SwiftUI:
```swift
ZStack {
Text("Hello, world!")
}
```
in LVN ends up being:
```html
<ZStack>
<Text>Hello, world!</Text>
</ZStack>
```
But when testing using `Phoenix.LiveViewTest` if we do:
```elixir
{:ok, lv, _markup} =
conn
|> …
```

Don't assert HTML in LiveViewTest

---

assets/js/phoenix_live_view/dom.js

In cases where an event is dispatched to  `live_file_input` the event keeps triggering until a call stack error is raised:
Uncaught RangeError: Maximum call stack size exceeded.
This can be triggered with something like:
<div phx-click={Phoenix.LiveView.JS.dispatch("click", to: "##{@uploads.image.ref}")}>
Upload
</div>
<form style="display: none;" id="upload-form" phx-submit="save" phx-change="validate">
<.live_file_input upload={@uploads.image} />
<button type="submit">Upload</button>
</form>
To fix this, we set bubble to false if the event target is a file input.

Prevent event bubbling on file upload targets

---

lib/phoenix_component.ex
lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/phoenix_component/verify_test.exs

Based on the discussion in #2331, this PR introduces a new slot attribute `validate_attrs` that can be set to false to prevent slots without any attrs defined from emitting a warning when attributes are passed.
Relates to #2331.
Relates to #2811.

add validate_attrs: false to slots

---

assets/js/phoenix_live_view/view.js

Fixes #2993
Fixes #1759
Hey there @chrismccord, while working on #1759 I noticed that your recent fix for #2993 actually breaks submit buttons in forms (as seen in the repro below) from restoring their disabled state. You can see this when changing the script src to LV main:
```elixir
server: true,
secret_key_base: String.duplicate("a", 64),
pubsub_server: MyPubSub
)
Mix.install([
{:phoenix, "~> 1.7.10", override: true},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
])
def render(template, _), do: …
```

Fix readonly and disabled state not resetting properly

---

assets/js/phoenix_live_view/dom.js

Fixes #2317.
Only apply phx-no-feedback if no other element with the same name has received focus yet.
Because the default core components checkbox renders a hidden input with the same name, we'd always reapply phx-no-feedback because the hidden input never receives focus.

handle multiple inputs with the same name (fixes #2317)

---

assets/js/phoenix_live_view/live_socket.js

I ran into this bug with nested LiveViews. If you're in a LiveView that is inside the root and click anywhere, this can trigger `phx-click-away` events to fire from the root view but be handled in the nested view that may not have handlers defined, causing the app to crash.

Ensure phx-click-away bindings are handled in the view or component they're defined.

---

lib/phoenix_live_component.ex
lib/phoenix_live_view.ex

Actualy, the `name` argument in `Phoenix.LiveView.start_async/3` and `cancel_async/3` can use values other than atoms. However, in the `handle_async` callback for `Phoenix.LiveView` and `Phoenix.LiveComponent`, the `name` argument is typed as `atom`. Therefore, I propose modifying the callback to assign the `term` type to `name`.
```ex
@callback handle_async(
name :: atom,  # <<<<<<<<<<<<<<<<< This type should be term
async_fun_result :: {:ok, term} | {:exit, term},
socket :: Socket.t()
) ::
{:noreply, Socket.t()}
```
I think #2935 overlooked this.

Fix handle_async callback typing

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/live_uploader.js
assets/js/phoenix_live_view/upload_entry.js

Fixes #2965 
```elixir
server: true,
secret_key_base: String.duplicate("a", 64),
pubsub_server: Example.PubSub
)
Mix.install([
{:jason, "~> 1.2"},
{:phoenix, "~> 1.7.7"},
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}
])
end
defmodule Example.NoOpWriter do
@behaviour Phoenix.LiveView.UploadWriter
@impl true
def init(opts) do
{:ok, %{parts: [], part_number: 1}}
end
@impl true
def meta(state), do: state
@impl true
def write_chunk(data, state) do
%{part_number: part_number} = …
```

track in-progress preflights (fixes #2965)

---

lib/phoenix_component.ex
lib/phoenix_live_view.ex

Just a small change to avoid confusion with the `async_result` `:failed` slot let binding.
[The docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-async-assigns) suggest returning `{:error, reason}` for failures, which implies that the `reason` in the binding is the same thing you returned. In fact it's the entire failure- one of `{:error, reason} | {:exit, reason} | reason`.
Follow up to #2991

Rename async_result failure slot let binding in docs

---

assets/js/phoenix_live_view/live_socket.js

A form may be reset directly by `HTMLFormElement.prototype.reset()` meaning it may not always contain a `<button type="reset"/>` element. Only dispatch to the reset element if it exists.

Check for reset element when resetting form (#2505)

---

assets/js/phoenix_live_view/constants.js
assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/live_socket.js
assets/test/view_test.js

This PR introduces `phx-feedback-group`. Setting this attribute on an input will set the `phx-no-feedback` class to elements with the corresponding `phx-feedback-for` attribute only if all inputs in the same `phx-feedback-group` did not receive any inputs yet.
References #2968.
Code adapted from #2968:
```elixir
Application.put_env(:composite_input, CompositeInput.Endpoint,
http: [ip: {127, 0, 0, 1}, port: 4001],
server: true,
render_errors: [
formats: [html: CompositeInput.ErrorHTML],
layout: false
],
)
Application.put_env(:ex_money, :default_cldr_backend, CompositeInput.Cldr)
Mix.install([
{:plug_cowboy, "~> 2.6"},
{:phoenix, "~> 1.7.10"},
{:phoenix_live_view, "~> 0.20.2"}, …
```

Add phx-feedback-group

---

assets/js/phoenix_live_view/view.js
assets/package-lock.json
assets/package.json
assets/setupTests.js

add CSS.escape polyfill for nodejs, as new jsdom is more strict with invalid CSS selectors

update javascript dependencies

---

assets/js/phoenix_live_view/rendered.js
test/e2e/test_helper.exs
test/e2e/tests/issues/3026.spec.js
test/support/e2e/issues/issue_3026.ex

There was an issue with `resetRender` where we tried to set the `reset` property on undefined if the component was actually already destroyed. This fixes that by adding another check.
The PR also adds a specific e2e test for #3026.
Fixes #3026.

add tests for #3026, check if component exists

---

guides/server/telemetry.md

Corrects `assigns_sockets` and `sockets` structure based on input from @rhcarvalho in #3036.
For reference metadata sample inspected from: https://github.com/phoenixframework/phoenix_live_view/blob/2d573f7e2fc02f04869568b00b05fd869e51abfd/test/phoenix_live_view/integrations/telemetry_test.exs#L298-L299
%{
socket: #Phoenix.LiveView.Socket<
id: "phx-F6x_rk-dj4e2Pi2E",
endpoint: Phoenix.LiveViewTest.Endpoint,
view: Phoenix.LiveViewTest.WithMultipleTargets,
parent_pid: nil,
root_pid: nil,
router: Phoenix.LiveViewTest.Router,
assigns: %{
disabled: [],
message: nil,
names: ["chris", "jose"],
from: nil,
live_action: nil,
__changed__: %{
disabled: true,
message: true,
names: true,
from: true,
parent_selector: true
},
flash: %{},
parent_selector: "#parent_id"
},
transport_pid: nil,
...
>,
sockets: …

Update Telemetry guide. Closes #3036

---

assets/js/phoenix_live_view/live_socket.js
test/e2e/test_helper.exs
test/e2e/tests/issues/3040.spec.js
test/support/e2e/issues/issue_3040.ex

Fixes #3040
When pressing enter inside a form, a click event is dispatched on the corresponding submit button. Because we only set the clickStartedAtTarget on mousedown, we would wrongly dispatch a click away.

check for synthetic click event before dispatching click away

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/async.ex
test/phoenix_live_view/integrations/assign_async_test.exs
test/support/live_views/general.ex

Sometimes it is desirable to clear the results during an assign_async
- for example when performing an async search, if the term has changed but the results are still loading, it doesn't make contextual sense when the term doesn't match the results. In these cases it's better to clear out the old results during loading.
This commit adds a `reset` flag to assign_async that will ignore previous results if set to true resulting in the liveview rendering with a default %AsyncResult{} struct.

Add reset option to assign_async/4 to clear previous results

---

assets/js/phoenix_live_view/view.js

fixes an issue introduced by myself..
https://github.com/phoenixframework/phoenix_live_view/pull/3017
And that's why we have nearly 700 end to end tests at work 😅

fix calling setAttribute on undefined

---

.formatter.exs
CHANGELOG.md
assets/js/phoenix_live_view/js.js
assets/test/js_test.js
lib/phoenix_live_view/js.ex
test/e2e/test_helper.exs
test/e2e/tests/js.spec.js
test/phoenix_live_view/js_test.exs
test/support/e2e/js_live.ex

This builds upon #2004 and expands toggle_attribute to also support toggling between two values. It also adds an end to end test.
Closes #2004.

Implement toggle_attribute (refs #2004)

---

assets/js/phoenix_live_view/dom_patch.js
lib/phoenix_live_view.ex
lib/phoenix_live_view/test/dom.ex
test/e2e/test_helper.exs
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex
test/support/router.ex

https://github.com/phoenixframework/phoenix_live_view/commit/997f15cadc86703134b1755f1fa2a3808ff91b2a introduces an issue where limits were not correctly enforced when adding items in bulk, this PR addresses this.
It also fixes an issue with limits being applied differently on resets, because we previously did not remove stream elements when they were being re-added later. I think this was initially introduced to avoid issues with live components not being correctly rendered because of the PHX_SKIP optimization. To counteract this, we now remove all elements on reset to force them being added in the correct order, but also store the live component DOM nodes to correctly restore them.
References #2686.

fix various issues with limiting streams

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js
lib/phoenix_live_view/js.ex
test/phoenix_live_view/js_test.exs

Closes #2600.
Removing all nil values should work fine as the values on the client are just going to be undefined instead of null then.
Maybe I should add some e2e tests as well? Wdyt?

Reduce JS.commands payload by moving defaults to client

---

assets/js/phoenix_live_view/live_socket.js
lib/phoenix_component.ex
test/e2e/tests/forms.spec.js
test/support/e2e/form_live.ex

To fix https://github.com/phoenixframework/phoenix_live_view/issues/3056 https://github.com/phoenixframework/phoenix_live_view/commit/fbe2226611511c89e9a61661f425e9d471cbbcb0 introduced a check that prevents submit buttons from submitting the form when phx-click is set. This change is not necessary, because for buttons that should not submit the form, the `type="button"` attribute should be used instead.
Adjusts the documentation to reflect this.

Do not prevent submitting form when phx-click is set

---

assets/js/phoenix_live_view/live_socket.js

Fixes #2293.
https://github.com/phoenixframework/phoenix_live_view/pull/2097 wrapped the join callback in an animation frame, therefore delaying the history push until the DOM is already patched. This causes relative file paths to be incorrectly resolved. Because #2173 adds the animation frame to the scroll function, this should still work as expected and at least in my manual tests it does.
Adding some E2E tests for the scroll restoration is on my todo list for https://github.com/phoenixframework/phoenix_live_view/issues/3034.

Revert #2097

---

assets/js/phoenix_live_view/dom_patch.js

When fixing stream limits I added a component restore functionality, but this was only working with LiveComponent that were skipped and only if they were the direct stream children. It could still happen that nested elements inside the stream child were skipped and not restored.
This PR solves this by storing all stream child elements children with a PHX_MAGIC_ID and restoring them later in case they were skipped.

fix skipped children on stream reset

---

CHANGELOG.md
assets/js/phoenix_live_view/dom_patch.js
lib/phoenix_live_view.ex
lib/phoenix_live_view/test/dom.ex
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

This is kind of a breaking change, so I already see the bug reports incoming when people update to 0.20.4. It is how it should work according to https://github.com/phoenixframework/phoenix_live_view/pull/3021#issuecomment-1899181366 though.
References #3021.
References #2904.
Relates to https://github.com/phoenixframework/phoenix_live_view/commit/b4fe85eb245c232449740427728a1c13b09406c1

do not reorder stream items if they already exist

---

guides/client/uploads-external.md

Matches the type signature for what ExAws expects with presigning the upload URL.

Update example to use types that ExAws expects

---

assets/js/phoenix_live_view/js.js

This adjusts isInViewport to only return false when the whole element is outside the viewport.
Fixes #3091.
Relates to #2928.
Relates to #2929.

fix isInViewport

---

lib/phoenix_live_view/test/live_view_test.ex

- Fixes #3063
- I am not sure why `cmd.exe` check was done for `unix` condition (could find it was added here https://github.com/phoenixframework/phoenix_live_view/commit/a6494c579d4750da9b437f35907d7e87aa5cf579 by @josevalim). But even if it is for the WSL case, it is not working. I think the better way is to treat WSL as another variant of Linux and use the same flow.

Fix open_browser not working on WSL for project under unix FS

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex
test/support/router.ex

This PR refactors the handling of streams in LiveViewTest to make it easier to understand. I mirrored the handling of streams in the JavaScript client, minus the morphdom related stuff.
It also adds a clause that *should*  handle the case of nested LiveViews where the LV parent updates. Currently, streams inside the child LV would be cleared. This *may* be a solution for that, although I'm not sure.

Refactor stream handling in LiveViewTest

---

lib/phoenix_component.ex

When getting documentation served by an IDE, the first line is particularly important. I felt the difference wasn't clear at a glance as it was only the word "entry" in the middle of the sentence, hard to spot.
Reworded to make the distinction stand out and included a reverse note on `upload_errors/2` pointing back to `upload_errors/1` for symmetry.
Also noted that the output is always a list and not individual errors -- which felt particularly relevant to `upload_errors/1` as it documents only one possible error.

Clarify distinction between upload_errors/1 and upload_errors/2

---

guides/server/uploads.md

The appendix defines `error_to_string/1` as a private function, so this does the same for the earlier appearance of that function.

Update Uploads guide code example for consistency

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/layout_test.exs

Today on each test client startup, Phoenix does a search to get the page title. To avoid this cost when the test doesn't need the title, this PR moves the page title search to be done only when the this value gets requested, and if the value hasn't been set by the LiveView.

Lazily initialize page_title on test client

---

guides/client/bindings.md
lib/phoenix_live_view.ex

Some links were correctly pointing to `#client-hooks-via-phx-hook`, some
not.

Fix links to phx-hook docs

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/test_helper.exs
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex
test/support/router.ex

This is a followup to #3070 and #3035.
When adjusting the stream component restore functionality in #3070, I accidentally broke live components in streams, but the tests did not detect this because they only checked the id of the stream items and not their content. Therefore, this commit also adjusts the tests.
Another problem that was introduced in #3035 by not leaving re-inserted items in the DOM is that nested streams inside live components inside streams would not be restored properly. This commit addresses this by recursively running morphdom on the restored stream items.
The added LiveViewTest test relies on #3104, therefore it is currently skipped.

Morph DOM nodes when restoring stream items

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/tests/streams.spec.js
test/support/live_views/streams.ex

This would throw otherwise while trying to reorder an element that is not in the DOM.
We also had a bug where stream items with phx-remove were removed, despite re-adding them in a stream reset.

skip reordering elements with no parent, fix phx-remove on re-added stream items

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/test/dom_test.exs

Fixes #3119 
Patch data attributes consistently, but not others.
a774138
> The "ignore" behaviour is frequently used when you need to integrate with another JS library. Updates from the server to the element's content and attributes are ignored, *except for data attributes*. Changes, additions, and removals from the server to data attributes are merged with the ignored element which can be used to pass data to the JS handler.

Align LiveViewTest with JS DOM patching for phx-update="ignore"

---

assets/js/phoenix_live_view/view.js

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3052
The existing code will create new `LiveUploader`s for input elements that have no entries to be uploaded. As currently written, the `LiveUploader` never calls the provided callback when there are no entries to process and thus never decrements `numFileInputsInProgress`.
This change does not create new `LiveUploader`s for inputs with no new entries and updates the closed over counter to reflect that fact. I don't love this solution but there are a lot of moving parts in here and I wasn't confident about making a bigger change.
Additionally, I deleted line 1047 because it doesn't appear to do anything useful. It is using an object as a key which doesn't seem right to me. It sets `this.uploaders` to `{[object …

Don't create new uploaders for inputs with no new entries

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

A tag containing no lines is now converted to a single `line()` instead of `empty()` to preserve compatibility with existing tests and formatted code.
Fixes #3134

Dont insert newlines around script/style tag content if phx-no-format

---

lib/phoenix_live_view/test/dom.ex

Should fix #3141
I didn't expect structs in the rendered tree? If someone has an idea how to force this I could add a test as well...

prevent reducing structs in extract_streams

---

guides/client/js-interop.md

The doc did not mention scoping here, this was only mentioned in the documentation for `push_event`. I added a similar passage here and an example based on the one above.

Docs: Add example for scoped `push_event` and hook

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/async.ex
test/phoenix_component/verify_test.exs
test/phoenix_live_view_test.exs

This PR only focuses on the async ops part of #3157. I'm not that knowledgeable when it comes to macros, but this seems to work fine and does not rely on runtime checks.

warn if socket is used in start_async / assign_async

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/lifecycle.ex
test/phoenix_live_view/integrations/hooks_test.exs
test/support/live_views/lifecycle.ex
test/support/router.ex

LiveComponents can now attach `:handle_event` hooks. The previous tests have been updated to use `handle_info` which will likely not be supported by LiveComponents as they don't have a `:handle_info`.

Support handle_event hooks on LiveComponents

---

lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

I have discovered that `mix format` is adding a new line to empty `.heex` files. This PR ensures that the final new line is added only when the output is not empty. Otherwise, the file remains unchanged.

Do not format when empty

---

assets/js/phoenix_live_view/dom.js

Currently opening a link with `target="name"` unloads live_socket because phoenix thinks it opens in the current tab, when in reality it doesn't. 
This change fixes it by checking if target is a named tab. These are valid values:
Value | Description
-- | --
_blank | Opens the linked document in a new window or tab
_self | Opens the linked document in the same frame as it was clicked (this is default)
_parent | Opens the linked document in the parent frame
_top | Opens the linked document in the full body of the window
framename | Opens the linked document in the named iframe
Check is a bit naive, I'm simply comparing if "target" doesn't start with underscore and adding it to previous checks. Should be enough?
Closes #3184

DOM.wantsNewTab(e) returns true for target="namedTab"

---

lib/phoenix_component.ex

This allows to put this `<input>` outside of a particular `<form>`

Add support for `form` attribute in `live_file_input/1`

---

assets/js/phoenix_live_view/dom.js

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3164.
As mentioned in the issue, I'm not sure what the original intention is behind blurring readonly elements when restoring focus. Since the original logic is explicitly checking for readonly elements to be blurred, it's possible this breaks some expected behaviour that I am unaware of.

Do not blur readOnly elements when restoring focus

---

assets/js/phoenix_live_view/dom.js

Hello, I found that when I try to render nested components I got this kind of errors in my browser console.
This happens because each component is surrounded by an HTML comment. In this PR I just skip the comment nodes I found.
The error disappears in my project and everything is working properly but let me know if I have to take into account anything else.

Ignore HTML comments

---

lib/phoenix_live_view.ex

Makes the example match a newly generated app.

Update `static_changed?/1` docs to use verified routes

---

guides/client/uploads-external.md

The prose says we are changing the `presign_url` function, but really it means to to `presign_upload`.  This becomes evident when reading through the whole context, but can be very confusing if you don't.  I suspect the function was originally called `presign_url` but got refactored to `presign_upload` and the prose got missed.

Fix bug in client file upload guide

---

assets/js/phoenix_live_view/hooks.js

When the root element has the overflowY as "auto" or "auto", this element will be returned.
As it never scroll, the event will never be launched. 
We want to always return null if the scrollContainer is the root (HTML) element.

Fix scroll hook when the root element has overflow Y as "scroll" or "auto"

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

Fixes #3216.
Initially reported here: https://elixirforum.com/t/updating-a-stream-with-reset-true-does-not-update-element-attributes/63011
Also fixes #3223.

do not use childrenOnly when patching stream items

---

lib/phoenix_live_view/test/live_view_test.ex

- 78c24a5a4, changed the return from :ok to path but it wasn't changed in the doc.

Fix assert_patch/3 doc to return path instead of :ok

---

guides/cheatsheets/html-attrs.cheatmd
mix.exs

This is a first attempt at condensing and organizing information around phx-* in a way that fits printed A4 pages or a screenful for quick reference.
Based on forum conversation at https://elixirforum.com/t/inconsistent-naming-of-liveview-dom-patching-binding-attributes/60901/6.
---
---
---
---

Add cheatsheet for special phx-* HTML attributes

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/async.ex
test/phoenix_live_view/integrations/assign_async_test.exs
test/support/live_views/general.ex

In circumstances where `assign_async/4` is being used to async assign multiple results, it is possible that some of the results should persist during loading, and others should not.
In this case, a list of keys can be passed to the `reset` option, and only those keys will be reset during the async operation.

Allow partially resetting an async result when using multiple assign

---

lib/phoenix_live_view/js.ex

Class name passed to `element.classList.add(name)` must not be empty in JavaScript.
This change will handle cases like this correctly:
```elixir
JS.show(transition: {"transition", "opacity-0", ""})
```

reject empty string in class_names

---

lib/phoenix_component.ex

I believe it should've been `user[header]` instead of `user[:header]`

Fix typo in documentation

---

guides/server/security-model.md
lib/phoenix_component.ex

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3205
Hopefully, this is enough of a hint to avoid the confusion that assigns could be shared across root LiveViews.
I also considered mentioning that assigns can be shared between `conn` and LiveViews in `security-model.md`, but opted for the minimal change instead.

clarify that assigns can only be shared across parent-child LiveViews

---

assets/js/phoenix_live_view/view.js
test/phoenix_live_view/integrations/event_test.exs

This fixes an issue where a hidden input with the same name as another input element leads to fields always being sent as `_unused_field`. Now, every input element with the given name must be unused.

consider any touched input as not _unused_

---

assets/js/phoenix_live_view/view.js

Based on a message in the Elixir Slack. With large forms that contains multiple hidden inputs, the payload size increases unnecessarily because of the `_unused` parameters. I currently don't see a reason to send thoses for fields that are only based on hidden inputs. If there are any, please correct me :)

don't add _unused fields for hidden inputs

---

lib/phoenix_live_view.ex

There's an extra "to" in "used to directly to update", but instead of simply removing it I thought a small rewording would make the sentence clearer.
Note that in the paragraph preceeding the code example we already said "For this, you can use ... and the AsyncResult module directly:"

Fix typo in 'Arbitrary async operations' section

---

lib/phoenix_live_view.ex

I suspect the reference to "name" might be part of how the implementation evolved (see #2763), but was not part of the final version.

Fix docs for `assign_async/3`

---

lib/phoenix_component.ex

There's a little typo here if I understand it right.

[Doc improvement] Fix a typo in the doc of used_input?/1

---

lib/phoenix_live_view.ex

Update the docs to make it clear that in the case where the item already exists in the parent DOM container, it's position will not be changed regardless of the value of the `:at` option. In particular, I removed the phrase, "while also moving it to the top of the collection", which was inaccurate.

Doc update for `Phoenix.LiveView.stream_insert/4`

---

lib/phoenix_component.ex

Add a working example of overriding the `data-confirm` behaviour

Overriding the default confirm behaviour - Make the example work

---

guides/cheatsheets/html-attrs.cheatmd
guides/client/js-interop.md
guides/client/uploads-external.md
guides/introduction/welcome.md
guides/server/uploads.md
mix.exs

This PR:
* fix dead links of dom patching related docs
* adjust link names in `Welcome.md` to match the ones in sidebar
* fix ex_doc warnings - `warning: :groups_for_functions is deprecated, please use :groups_for_docs instead`
* sync link name of uploads-external.md

[Doc improvement] Fix dead links, adjust link names

---

lib/phoenix_component.ex

Minor docs update.
I was reading the docs and I noticed `Routes.comment_path(:create, @comment)`. Since this isn't really the current way, I thought it might be potentially confusing to a new user.

[docs] Use ~p instead of Routes in the example.

---

lib/phoenix_live_view/test/structs.ex
test/phoenix_live_view/upload/external_test.exs

`Phoenix.LiveViewTest.file_input/4` is ignoring the option `last_modified`, so it's impossible to populate `entry.client_last_modified` with this test function as the documentation says.
```elixir
[test/phoenix_live_view/upload/external_test.exs:233: Phoenix.LiveView.UploadExternalTest."test consume_uploaded_entries"/1]
file_input(lv, "form", :avatar, [
%{name: "foo.jpeg", content: String.duplicate("ok", 100), last_modified: 1_594_171_879_000}
]) #=> #Phoenix.LiveViewTest.Upload<
selector: nil,
entries: [
%{
"content" => "okokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokok",
"name" => "foo.jpeg",
"ref" => "9417",
"relative_path" => nil, …
```

Fix `Phoenix.LiveViewTest.file_input/4` ignoring `last_modified` option

---

assets/js/phoenix_live_view/dom_patch.js
lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/html_engine_test.exs

This only works when writing `<input name="id">` directly, as it's a compile time check only. If the name is in an assign, it won't warn because we don't know the value of the assign until runtime (correct me if I'm wrong).
Maybe we should add a warning in the LiveView JS, like the duplicate ID warning.
@josevalim

Warn if using `<input name="id">`

---

guides/client/bindings.md

In the given context, `phx-connect` and `phx-disconnected` are bindings (a.k.a. "event bindings") and not events themselves, which could confuse readers thinking about JavaScript events or LiveView socket events.

Update socket lifecycle docs s/events/bindings

---

guides/server/assigns-eex.md

I was under the impression that using `assign/3` and friends inside of a function would break change tracking, which is *not* the case.
A quick note to clarify this behavior

Clarify that using assign/3 will not break change tracking

---

lib/phoenix_live_view/js.ex

`Phoenix.LiveView.JS.t` is already exposed as a struct by the `CoreComponents` generator: https://github.com/phoenixframework/phoenix/blob/2e06455a4041965da133cd23a650245f53d6800c/priv/templates/phx.gen.live/core_components.ex#L602.
This PR makes the struct type itself transparent while keeping its fields opaque so that functions operating on `Phoenix.LiveView.JS.t` can be properly specced. Otherwise, speccing the `CoreComponents` JS functions as such:
```elixir
@spec show(String.t()) :: Phoenix.LiveView.JS.t()
@spec show(Phoenix.LiveView.JS.t(), String.t()) :: Phoenix.LiveView.JS.t()
def show(js \\ %JS{}, selector) do
```
causes the following Dialyzer error:
```
The @spec for WebWeb.CoreComponents.show/1 has an opaque
subtype Phoenix.LiveView.JS.t() which is violated by the success …
```

fix: make Phoenix.LiveView.JS.t transparent

---

assets/js/phoenix_live_view/view.js

> Even though `-` is rarely used as key in Elixir, there are instances when it is used, so it's better to consider it.
[Current implementation of `prependFormDataKey`](https://github.com/phoenixframework/phoenix_live_view/blob/02bc543fc2602a1de3f53dbfe2bbdfef443806ac/assets/js/phoenix_live_view/view.js#L58) fails to handle the key containing `-`:
```
prependFormDataKey('en', '_unused_')    // '_unused_en'    - good
prependFormDataKey('en-US', '_unused_') // 'en-_unused_US' - bad
```
This PR aims to fix above issue by considering more possible characters. The result:
```
prependFormDataKey('en', '_unused_')    // '_unused_en'    - good
prependFormDataKey('en-US', '_unused_') // '_unused_en-US' - good
```

Consider more possible characters when prefixing unused form data key

---

lib/phoenix_component.ex
lib/phoenix_live_view.ex
lib/phoenix_live_view/router.ex

I was looking at this pattern of usage for addressing https://github.com/phoenixframework/phoenix_live_view/pull/3267#discussion_r1618643137, and uncovered a handful more places where the change makes sense. Decided for a separate PR to keep the noise low, diff smaller and easier to review.
Added a couple of opportunistic changes while reading surrounding docs:
- "Defaults XXX" -> "Defaults to XXX"
- Phoenix.LiveView.UploadWriter behaviour

Review the/a usage across docs

---

guides/client/form-bindings.md

Update the code example (4+ years old) to set the form/changeset action to a conventional name unrelated to database operations, as suggested elsewhere in the docs [1].
Also use the new `:action` option added to `to_form` in v1.0 [2].
[1]: https://github.com/phoenixframework/phoenix_live_view/blame/6648f774354e308efc26d7e44e6e68d5a1b12fe1/lib/phoenix_component.ex#L2188-L2193
[2]: https://github.com/phoenixframework/phoenix_live_view/commit/d9124684fbc41f39abf9b5e37014f53b03e7ef46#diff-8a399cc9a3e142ef2ff2b7437ba397cb3affa4ed0346b53eb087d4d303b0f781
---
Notes:
1. I've also reviewed other places where `to_form` is used, this was the only occurrence that seemed to deserve an update.
2. I'm not strong about using the new option `to_form(..., action: :validate)`; if we want to keep the example …

Update to_form action in 'Form bindings' guide

---

lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3289
So that Formatter doesn't force `<%=`. It should relies on `opt` metadata ommited by EEx tokenizer instead.

Formatter | Doesn't convert <%= to <%

---

lib/phoenix_live_view.ex
lib/phoenix_live_view/test/dom.ex
test/e2e/test_helper.exs
test/e2e/tests/streams.spec.js
test/e2e/utils.js
test/phoenix_live_view/integrations/stream_test.exs
test/support/live_views/streams.ex

This change allows for foreign items to be rendered in a stream container. It is mainly useful for having a simple way to show an empty state, by doing something like
```html
<div id="users" phx-update="stream">
<div id="users-empty" class="only:block hidden">Empty!</div>
<div :for={{id, user} <- @streams.users} id={id}><%= user.name %></div>
</div>
```
Closes #3260.
Non-stream items **must still have a unique id**.

Allow foreign items in stream containers

---

assets/js/phoenix_live_view/dom.js
test/e2e/test_helper.exs
test/e2e/tests/issues/3194.spec.js
test/support/e2e/issues/issue_3194.ex

When submitting a form with phx-debounce="blur" without ever leaving the field, the blur event would be fired twice on the input, as the browser would trigger a second blur event when the view is patched by morphdom and the currently focused input is removed, sending the event to the new LiveView.
My fix here is to check for the asyncFilter introduced in https://github.com/phoenixframework/phoenix_live_view/commit/5a62253004abc4617c51e3f7c2cbb68245d2f86d, which already checks if the view is destroyed or the element not in the DOM.
Fixes #3194.

check asyncFilter on blur (closes #3194)

---

lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

I created a bug in #3298 if you used put_submitter with a button outside the form.
```
** (FunctionClauseError) no function clause matching in Phoenix.LiveViewTest.ClientProxy.form_defaults/3
{"button", [...], [...]}...
```
So this fixes using `put_submitter/2` with named inputs because before I included buttons in `maybe_submitter/2`.
I'll try and write some extra tests for error/failure cases next week. I've run out of time this weekend.

Fix using named form inputs with put_submitter/2

---

CHANGELOG.md
guides/introduction/welcome.md
lib/phoenix_component.ex
lib/phoenix_live_component.ex
lib/phoenix_live_view.ex
lib/phoenix_live_view/test/live_view_test.ex

I found most of "LiveView" and "LiveComponent" in the doc is not wrapped by ``. 
This PR:
+ remove the `` around LiveView and LiveComponent, to keep their format consistent.
+ fix small typos, such as:
- `Log` -> `log`

Remove unecessary `` around LiveView and LiveComponent from docs

---

guides/client/js-interop.md
lib/phoenix_live_view.ex

@chrismccord, reopened this which was previously incorporated into #2892 PR
--- 
I've added JSDoc annotations to the Hook usage examples in order to enhance IDE autocomplete functionality. Often, developers find themselves referring back to the documentation to recall a Hook's structure and its associated functions. Embedding type documentation directly within the code streamlines this process, offering a more efficient development experience.

Add JSDoc for hook examples

---

lib/phoenix_component/declarative.ex

Error message didn't mention valid option `include:`

Fix error message

---

lib/phoenix_component.ex

Uses `for` instead of `:let` for the form function component

Update docs for `Phoenix.Component.inputs_for`

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/tests/streams.spec.js
test/support/live_views/streams.ex

This ensures JS commands are properly re-applied when a LV reconnects.
Originally reported in Slack (https://elixir-lang.slack.com/archives/CD594E0UU/p1721248736382849):
> I'm having a heck of a time converting a UI pattern from React to LiveView, which is inline edit of content within a list view, ideally using LiveView streams. I also want to ensure that only one row can be edited at a time. I was able to get all of this working wonderfully using JS commands to add/remove classes, but anytime the user loses connection (mobile device or a server deployment) and reconnects, the stream ends up re-rendering and we lose which item user was editing which is not a great UX.
> If I don't use streams, the JS command changes seem to persist across reconnects, but updating a single row when …

keep stream items on rejoin

---

assets/js/phoenix_live_view/view.js
test/e2e/tests/navigation.spec.js

Initially reported here: https://elixirforum.com/t/navigating-using-patch-causes-liveview-to-re-mount-when-using-browser-back-button/62595
In the popstate event LV compares the id in the history with the id of the main view id. But on the initial navigation, the history state is never set, so navigating all the way back causes an unnecessary remount.
This is fixed by using replaceRootHistory when joining the main view.

Fix unnecessary remount when navigating back

---

assets/js/phoenix_live_view/live_socket.js

Using `JS.dispatch` to trigger an input event only works when targeting an input element (input, select, textarea), not the form element itself. This commit throws a useful error in the case of an invalid target.
References #3328

Throw error when dispatching input on invalid targets

---

lib/phoenix_live_view.ex

Add the comment to suggest to use : 
`# In Phoenix v1.6+ apps, the line is typically: use MyAppWeb, :live_view
`
in the live_view doc

Fix doc to suggest to use "use MyAppWeb, :live_view".

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs

Previously, having a typo when defining slot options did not warn, so you could write `slot :myslot, requird: true` and it would be silently ignored. This PR adds a compile time warning if any other option than `required`, `doc`, or `validate_attrs` is passed to `slot`.

validate slot options

---

assets/js/phoenix_live_view/live_socket.js

Since https://github.com/phoenixframework/phoenix_live_view/commit/db841e39f8fdeebce93d8978aea4a3d7683a1445 LV uses the mousedown target as the target for the actual click event.
This causes an issue with how clicks are usually handled, for example when clicking on a button but then moving the mouse away. Always using the event target should be the correct way.
Fixes #3363.

don't use mousedown target for click event

---

lib/phoenix_live_view/js.ex

Add example where `duration-300` and `time:` are the same otherwise the transition will be cut short as the default `time:` is 200 milliseconds.

[docs] JS.transition/1-2-3 `duration-300` matches `time: 300` example

---

lib/phoenix_live_view.ex

In our project, we have a bit of a corner case when using `on_mount/1`. It's used like that:
```
on_mount {MyAppWeb.EnsureFeature, features: [FeatureTypes.my_feature()]}
```
`FeatureTypes.my_feature()` is a macro, we use macro as constants so we can use then in pattern-matching and other place - I know that's a bit unexpected, but well, it works 😄
The problem here is that this macro call makes the whole expression not a quoted literal, preventing LiveView from expanding it (see [on_mount](https://github.com/phoenixframework/phoenix_live_view/blob/f778e5bb1a4b0a29f8d688bbc6c0b7182dea51ca/lib/phoenix_live_view.ex#L538) implementation), creating a compile dependency to both `MyAppWeb.EnsureFeature` and `FeatureTypes.my_feature()`.
The dependency to `FeatureTypes.my_feature()` is expected, …

avoid compile dependency in some cases on `on_mount`

---

guides/server/uploads.md
lib/phoenix_live_view.ex

1. Document return value for consume_uploaded_entries/3 explicitly
2. Demystify the magic variable `uploaded_files` in the uploads guide

Upload documentation improvements

---

lib/phoenix_live_view/test/live_view_test.ex

PR #3250 added more explicit pattern matching to the `element` function, but didn't handle the missing text filter case.
Closes #3250

Clarify options to LiveViewTest.element

---

lib/phoenix_live_view/utils.ex
test/phoenix_component_test.exs

This PR is a prerequisite to perform nested change tracking of other types of data than maps, eg. lists or tuples. It was mentioned in a discussed with @josevalim on [Elixir forum](https://elixirforum.com/t/possible-payload-size-improvement-to-heex-list-comprehensions/64986) and on Twitter DM 
The end goal is to optimize lists payload and enable nested change tracking. 
Currently `socket.assigns.__changed__` keep old versions of maps for nested change tracking and `true` for all other types of props. This PR introduces a small change to keep old versions of all the props regardless of type. 
IMO this is not a breaking change. `changed?/2` is simply checking if key is in the `__changed__` map, value itself is not used. And structure of `__changed__` is a private api.
I also though if it …

Keep all old values in `__changed__` when using `assign/3` instead of only maps

---

guides/server/live-navigation.md

The call to [`path/2`](https://hexdocs.pm/phoenix/Phoenix.VerifiedRoutes.html#path/2) does not work in the current version of Elixir. This commit replaces it with `sigil_p`, passing the query parameter as a keyword list.

Docs: replace call to `path/2` with `sigil_p`

---

lib/phoenix_live_component.ex

Fixes the code example so `@id` is rendered instead of being escaped.

Fix code example: `#` should not be escaped

---

assets/js/phoenix_live_view/aria.js

I can't find it used anywhere in the project and no references online, so it doesn't seem to be used by applications, as far as I can tell

Remove focusMain from aria.js because it doesn't seem to be used

---

lib/phoenix_component.ex

Better description of what is returned by the `used_input?/1` function. It _doesn't_ return the errors as such, but rather indicates whether the input field is being used (which can then be used to control whether to show errors or not).

Improve docs of used_input?/1 (returns a boolean, not the errors)

---

lib/phoenix_component.ex

The docs for the `<.form>` component currently state "If an :action is given with no method, the method will default to post". However, this is incorrect because if `Phoenix.HTML.FormData.to_form/2` can also return `:put`. This PR updates the doc to make it more clear that `Phoenix.HTML.FormData.to_form/2` determines the default.
Here is what it looks like rendered in html:
Background: I just spent a bunch of time trying to determine why when I changed my changeset, suddenly when my form resulted in a `no route found for POST` exception. It turns out it's because `phoenix_html`'s `Phoenix.HTML.FormData.to_form/2` calls `phoenix_ecto`'s `defimpl Phoenix.HTML.FormData, for: Ecto.Changeset` which looks for `state: :loaded` in the changeset data. Hopefully this documentation fix will make it …

document form method default

---

lib/phoenix_component/declarative.ex
lib/phoenix_live_view/tag_engine.ex
test/phoenix_component/verify_test.exs

This commit introduces compile time warnings for component attributes that are defined using `{:fun, arity}`. In the cases that we can detect the arity at compile time, we will warn the user if the arity of the passed function does not match the arity declared for the attribute.
Relates to #3355.

Add compile time warnings for attr arity mismatch

---

guides/client/bindings.md

Hi folks 💜 
I was confused about the role of `phx-update` earlier. Because of how it's presented in the documentation, I thought it was a counterpart to `phx-mounted` and `phx-remove` and didn't understand why I couldn't do e.g.
```html
<div id="my-div" phx-update={JS.transition(...)}>
```
To address this, I've changed the order of bindings listed under DOM Patching to mirror the explanation and avoid implying a life-cycle. I've also added a note at the bottom of the explanation to explicitly direct people to use `phx-hook` instead. Both of these would have helped me avoid confusion. 🙂 
Hope this helps!

Clarify the role of `phx-update`

---

lib/phoenix_component.ex
test/phoenix_component/components_test.exs

The HTML form method attribute is case insensitive, so if we get a get / post we always use the downcased version.
Fixes #3422.

Downcase form method in <.form>

---

README.md

A component system is often on the top of the list of required LiveView features, so let's list them in the README.
We can add new systems as well. If any system is no longer developer, we can remove it. I probably want to duplicate this list in Phoenix docs later on.
/cc @chrisgreg @woylie @nhobes @ArthurClemens @mitkins @bluzky

List component systems on README

---

assets/js/phoenix_live_view/hooks.js

In zoomed viewports (from doing `⌘` or `Ctrl` + `+`), `phx-viewport-*` events do not fire when scrolled to bottom/top under certain screen/viewport/row height combinations.
That is because `Element.getBoundingClientRect()` may return coordinates with decimal places when the viewport is zoomed. When compared to viewport coordinates which are always whole numbers, the bounds check may fail.
I inserted logs into `isAtViewportBottom` and this is the lowest `rect.bottom` can get after scrolling to the bottom.
This pull request rounds them with `Math.floor` and `Math.ceil` to increase the odds of falling within bounds, which in my tests, totally fixes the issue.
**To Reproduce**
1. Create an infinite loading `<table>`.
2. Zoom in twice or more in the browser.
3. Scrolling to the end does not …

Fix infinite loading streams in zoomed viewports

---

lib/phoenix_live_view.ex

While fixing a bug in the day job I realised that:
- `start_async` manages concurrent tasks for you. If you reuse a `name` for `start_async`, then the last one wins and the previous one(s)’ results are ignored. It doesn’t terminate them it just safely ignores the results.
- The `name` is not restricted to being an atom, it can be any term AFAIK, say a tuple.
This PR documents these things. I’m sure it can be worded better so open to some editing!
BTW at the day job we use a `name` of a tuple with an atom and a list of Dates: `{:load_times, dates}` so the richness in being able to use terms was really appreciated.

Document `start_async` ignores previous with same `name`

---

lib/phoenix_live_view/router.ex

Some tests would be nice. I'm also not 100% sure if this is the correct way to do it. Should we raise if someone uses `:as` when helpers are disabled?
Closes #3418

Do not define as :as helper if helpers are disabled

---

assets/js/phoenix_live_view/view.js
test/e2e/test_helper.exs
test/e2e/tests/issues/3378.spec.js
test/support/e2e/issues/issue_3378.ex

Fixes #3378
@chrismccord I'm not 100% sure on this one. Because of the fallback here
https://github.com/phoenixframework/phoenix_live_view/blob/2bb4564ec872e6e544b997a0f38151c58b696827/assets/js/phoenix_live_view/live_socket.js#L474
it can happen that we return the main view instead of the actual owner when a nested LV is not yet joined. Maybe it's not a problem?

check if child id exists in children list

---

lib/phoenix_live_view.ex

Recently ran into a Mox problem due to using assign_async and forgetting to use `render_async/2` in my tests. The documentation for assign_async did not mention anything, so i thought of adding it.

Adding documention for implications assign_async might have in testing

---

guides/introduction/welcome.md

I was following the example in the welcome, and it wasn't working because the root layout wasn't getting loaded, which means the `<head>` section that loads `app.js` was missing. The example is incomplete without the browser pipeline being used.
Also, Phoenix 1.5 is no longer supported, so updating the `use` line in the example to only show the new way.

add browser pipeline to example router so the root layout and JS get loaded

---

lib/phoenix_component.ex

When using `<.inputs_for>`, accessing the raw value of the nested field and doing calculations on it has some pitfalls, because the value can be changesets, data or even raw parameters, depending on what is currently happening in the form. This leads to complex code that can be avoided by doing such calculations on the changeset instead. This commit adds a warning adomonition block mentioning this together with a small example.
Closes #3461.
@josevalim not 100% sure about this. It's a little longer than I anticipated, but I couldn't come up with a shorter explanation that I was satisfied with. Feel free to modify as you see fit.
I didn't add anything to the `Phoenix.Component.form/1` docs, as it is generally only a problem with complex fields, such as those used with `inputs_for`.

Add doc section on accessing a nested field's value

---

lib/phoenix_live_view/js.ex
test/phoenix_live_view/js_test.exs

This commit introduces a new function `JS.concat/2` to concatenate two JS commands together. Previously, you could only append new commands at the back, now you can also prepend commands by doing something like `JS.concat(JS.dispatch("my_event"), existing_js)`.
Closes #3233.

Add JS.concat/2

---

lib/phoenix_component/declarative.ex
test/phoenix_component/verify_test.exs

After https://github.com/phoenixframework/phoenix_live_view/pull/3419, warnings were introduced for arity and type mismatches for component attributes, but the warning was rendered incorrectly for non-function attributes or attributes with `values` set.
This fixes
```
warning: ... must be a :string, got: 1
```
to instead render
```
warning: ... must be a :string, got: a function of arity 1
```

Fix warning when passing a function to a component attribute

---

assets/js/phoenix_live_view/view_hook.js
assets/test/event_test.js
assets/test/js_test.js
assets/test/view_test.js

This is a breaking change. Until now, pushEvent always returned the ref, but with this change it returns a promise by default, if no onReply function is given.
Relates to: #1937
I don't really like the code as is, but if we want to support this, now would be the time I'd say, pre 1.0.
@chrismccord

support pushEvent returning a promise

---

lib/phoenix_live_view/html_algebra.ex
lib/phoenix_live_view/html_formatter.ex
test/phoenix_live_view/html_formatter_test.exs
test/phoenix_live_view/integrations/html_formatter_test.exs

This PR improves the HTML formatter so that it keeps at least one line (which usually are lines we want to keep intentionally) when formatting comments.

Formatter - Keep intentional newlines when formatting comments

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/support/issues/issue_3448.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3448.spec.js

The simplified morphdom call used to patch cloned trees did not restore focus to the previously focused element. This commit applies the same restoreFocus logic used in the normal morphdom call.
Fixes #3448.

restore focus after patching cloned tree

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/view.js
assets/test/dom_test.js
assets/test/test_helpers.js
assets/test/view_test.js
lib/phoenix_component.ex
test/phoenix_component/components_test.exs

Support default title attribute

---

guides/introduction/welcome.md
lib/phoenix_live_component.ex

This commit makes some small tweaks to the language used in the welcome guide, specifically under the "Compartmentalize state, markup, and events" section.  The primary goal is to be a little more explicit when talking about function components vs live components vs nested LiveViews.  There are a few small grammar tweaks as well as renaming a lone reference to "functional components" to "function component."  I've always been a bit confused as to the proper name but it seems that it's "function component" everywhere except this one place.  There is actually one more place but it's in the changelog and it feels odd changing that—I can, though!
Question: should LiveComponent always be written like that when not explicitly talking about the module, or is "live component" the right way?  I …

Tweak language in the welcome guide

---

guides/client/form-bindings.md

Was perusing the number input portion of the form-bindings.md guide, and I followed the CanIUse link to find that browser support for `inputmode` is in a far better place than it was back in 2021

Update form-bindings guide with up-to-date `inputmode` browser support

---

guides/client/js-interop.md

[The docs](https://hexdocs.pm/phoenix_live_view/1.0.0-rc.6/js-interop.html#simulating-latency) for `liveSocket.enableLatencySim` seem misleading if not outright wrong:
> The `enableLatencySim` function accepts an integer in milliseconds for the **round-trip-time** to the server.
"Round-trip time" means the total time taken for the signal to go from client to server then back again. I.e. if I set the latency sim to `5000` ms, I would expect that when I e.g. when I change something in an `<input>` it would take 5 seconds to see the result (e.g. error messages appearing on the form.)
But experimenting with this feature, it seems that the argument I submit to `enableLatencySim` is actually the one-way time, not the round-trip time. I.e. if I set it to `5000` ms then it takes 10 seconds to see …

fix misleading docs for enableLatencySim

---

lib/phoenix_live_view.ex

As described in https://github.com/phoenixframework/phoenix_live_view/issues/3481, I added a line concerning the fact that it makes sense to `render_async` in general before finishing the test.
Not 100% sure if you want the example error message in the docs. Most people would probably bump into a Postgres variant of this.

Extend documentation concering assign_async/3 and tests

---

lib/phoenix_component.ex

Just a simple fix in the docs. This confused me for a bit when I went to `cast/4`'s docs instead of `cast_assoc/3`'s.

Fix reference to wrong Changeset function, should be cast_assoc

---

lib/phoenix_live_view/js.ex

When using [hide](https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view/js.ex#L413) and [show](https://github.com/phoenixframework/phoenix_live_view/blob/bb991f5a188bd1486b8de2ca4768c05f9f4aa7e4/lib/phoenix_live_view/js.ex#L362) functions, I noticed that elements that weren't visible to the users weren't being hidden by adding the `display: none` style. 
After looking at the JS code, I saw that the corresponding js functions check if the [element is visible](https://github.com/phoenixframework/phoenix_live_view/blob/bb991f5a188bd1486b8de2ca4768c05f9f4aa7e4/assets/js/phoenix_live_view/js.js#L160) or not before applying the style. IMO this is not trivial and should be added to the documentation.

Add a note to the JS hide/1 and show/1 functions for clarifying targeted elements

---

assets/js/phoenix_live_view/view.js
test/e2e/tests/navigation.spec.js

Reverts phoenixframework/phoenix_live_view#3335
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3508.
The history API is the worst...
replaceRootHistory sets the initial type to "patch". Now assuming the following events:
1. initial navigation to /page1
History:
```
==> /page1, type patch
```
2. Navigating to /page2 (navigate, no patch)
```
/page1, type patch
==> /page2, type redirect
```
Then we'd call replaceRootHistory after the new join:
```
/page1, type patch
==> /page2, type patch
```
If we now use the back button, the browser would send us a popstate event including the previous state (type=patch). Instead of a navigate, we'd do a patch.
We could change replaceRootHistory to not assume type=patch, but then the initial PR would be useless as well, as there would …

Revert "Fix unnecessary remount when navigating back"

---

lib/phoenix_component.ex

Contents curtesy of @SteffenDE having posted those on slack

Document having curly braces text literals in heex

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/event_test.exs
test/phoenix_live_view/integrations/nested_test.exs
test/support/live_views/events.ex

When there are duplicate IDs in the DOM, morphdom will not be able to correctly patch the DOM. This PR tries to catch those cases early by walking the HTML tree in LiveViewTest and raising if there are any duplicate IDs. Walking the tree is extra work, but it might be worth it.
If we think raising might be too drastic, we could also just warn instead.

raise on duplicate ids in LiveViewTest

---

assets/js/phoenix_live_view/live_socket.js
test/e2e/support/navigation.ex
test/e2e/test_helper.exs
test/e2e/tests/navigation.spec.js

In the past, when navigating back from an external or dead page to a live page, the scroll position would not be restored.

restore scroll position on initial navigation

---

lib/phoenix_component.ex

Generate a `th`, instead of a `tr`, for each `col`.

fix doc: Slot Attributes example table/1 code

---

guides/client/form-bindings.md

Removes deprecated error handling code that was left over from before the `phx-feedback-for` migration.

doc: Form bindings > Error Feedback: Remove legacy error example

---

lib/phoenix_live_view/test/live_view_test.ex

Closes https://github.com/phoenixframework/phoenix_live_view/pull/3581.
@josevalim I didn't try it, but if I understand the generated stuff correctly, this should prevent type warnings when the case clause cannot match, right?

mark follow_redirect AST as generated

---

lib/phoenix_live_view/live_stream.ex
test/phoenix_live_view/live_stream_test.exs

Also adjusts stream_insert to prepend the insert instead of expensively appending it.
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/2689. Closes https://github.com/phoenixframework/phoenix_live_view/pull/3596. Closes https://github.com/phoenixframework/phoenix_live_view/pull/3598.

deduplicate stream inserts

---

lib/phoenix_component.ex

The suffix should contain a space before the separator to render as expected.
The example separators were different characters; update to be the same as used in the phx.new root template.

Update live_title examples for consistent spacing

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/dom_patch.js
assets/test/dom_test.js

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3591.

phx-trigger-action: check for cloned tree

---

lib/phoenix_live_view/engine.ex
test/phoenix_live_view/engine_test.exs

This prevents `@mymap[:foo]` from re-rendering when the map does not contain the key `:foo`, is changed, and then still does not contain `:foo`.

change-track non existing keys in maps

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/nested_test.exs
test/phoenix_live_view/test/dom_test.exs
test/phoenix_live_view/test/dom_warn_test.exs

Relates to #3588.
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3560.
cc @josevalim

actually warn, don't raise on duplicate ids in LiveViewTest

---

assets/js/phoenix_live_view/dom.js
assets/test/dom_test.js

findExistingParentCIDs did not ignore CIDs in child LiveViews, causing updates to be ignored in certain cases.
Fixes #3626.

properly scope findExistingParentCIDs

---

assets/js/phoenix_live_view/view.js
assets/test/view_test.js

Relates to: #3496
Fixes: #3623
In #3496, I cleared the hookId on the element in destroyed, but the view's destroyHook function actually relied on the hookId to clean up the view's viewHooks object. This would cause hooks' destroy function to be called multiple times, as the view was not able to remove old hooks.

properly clear viewHooks when destroying a hook

---

lib/phoenix_component.ex

Document functionality introduced by https://github.com/phoenixframework/phoenix_live_view/pull/3419
eg.
```elixir
attr :on_complete, {:fun, 2}
```

Document `:fun` and `{:fun, arity}` type supported by `attr/3`

---

lib/phoenix_live_view.ex

That was the only module  using `%Socket{}`, in every other place the pattern is to use `socket :: Socket.t()`
Before:
After:

fix(spec): use Socket.t() instead of %Socket{}

---

assets/js/phoenix_live_view/hooks.js

When FocusWrap was used, but the previous focus was outside of the wrapped element, the browser would try to focus the boundary element, causing us to focus the last element instead. This is fixed by checking the relatedTarget of the event, and specially handling focus coming from outside.
Fixes #3636.

Handle entering FocusWrap from outside

---

assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/utils.js

This logs an error to the JS console when debug mode is enabled to warn users when they forgot to add phx-update="stream" to the direct parent of an inserted stream item.

warn when phx-update="stream" is missing

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/element_ref.js
assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3647.ex
test/e2e/support/issues/issue_3651.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3647.spec.js
test/e2e/tests/issues/3651.spec.js

Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3647.
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/3651.
Relates to: https://github.com/phoenixframework/phoenix_live_view/issues/3591.
Issue https://github.com/phoenixframework/phoenix_live_view/issues/3647 was caused by LV uploads relying on DOM attributes like
data-phx-active-refs="1,2,3" being in the DOM to track uploads. The problem
arises when the upload input is inside a form that is locked due to another,
unrelated change. The following would happen:
1. User clicks on a button to upload a file
2. A hook calls this.uploadTo(), which triggers a validate event and
locks the form
3. The hook also changes another input in ANOTHER form, which also
triggers a separate validate event and locks the …

use regular DOM patching when unlocking cloned trees

---

CHANGELOG.md
assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3529.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3529.spec.js

Relates to: #3529
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3624
`replaceRootHistory` was initially added by @chrismccord in https://github.com/phoenixframework/phoenix_live_view/commit/36edb4883a51fbf786e32aad91cc29d302679438, but lost its purpose after less than three months with https://github.com/phoenixframework/phoenix_live_view/commit/04aaedcd1fe70d21e5e41147d6859cb5e77fb0f7 removing the only call that would actually set `root: true` in the history state.
Me not knowing what `root: true` is supposed to do reused replaceRootHistory in https://github.com/phoenixframework/phoenix_live_view/pull/3335, reintroducing the case where `root: true` is set in the history state. While #3335 was reverted later due to issues …

remove replaceRootHistory

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/diff.ex
lib/phoenix_live_view/socket.ex
lib/phoenix_live_view/static.ex
lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/diff_test.exs

`fingerprints` is a private field that is not actually required to be tracked on the `socket`, so we moved it to the channel state.

Remove fingerprints from socket and track it in state

---

assets/js/phoenix_live_view/hooks.js
assets/js/phoenix_live_view/js.js

This ensures that JS.focus works on iOS.
Fixes: #3563
Relates to: https://github.com/phoenixframework/phoenix_live_view/issues/1826

don't overuse requestAnimationFrame

---

assets/js/phoenix_live_view/dom_patch.js
assets/js/phoenix_live_view/live_socket.js
test/e2e/support/issues/issue_3656.ex
test/e2e/support/issues/issue_3658.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3656.spec.js
test/e2e/tests/issues/3658.spec.js

fix phx-remove and phx-click-loading in sticky LVs

---

lib/phoenix_live_view/test/dom.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex

Goal: Make it easier to find an element by text (`element/3`, `has_element?/3`) if there is nested markup.
Example input:
```
<span>
Text
<span>with whitespace</span>
</span>
```
Status quo:
- `element(view, "span", "Text\n  with whitespace")`
- `element(view, "span", ~r/Text\n.*with whitespace/)`
With this PR:
- `element(view, "span", "Text with whitespace")`
Solution: Normalize whitespace (convert different whitespace characters to regular space, collapse consecutive whitespace).
Breaking change: This PR changes the default behaviour. Maybe this should be opt-in instead?
To feature test libraries, which of course can't be compared 1:1.
Wallaby
>  Matches any element by its inner text.
`~s{.//*[contains(normalize-space(text()), "#{selector}")]}` …

Element text selector: Normalize whitespace

---

lib/phoenix_live_view/router.ex

Remove reference to live_path
Use VerifiedRoutes instead of named route helpers, as explained in: https://hexdocs.pm/phoenix/Phoenix.VerifiedRoutes.html#module-what-about-named-routes
Fixes #3666

Update router.ex doc

---

lib/phoenix_live_view/channel.ex
test/e2e/support/navigation.ex
test/e2e/test_helper.exs
test/e2e/tests/navigation.spec.js

In circumstances where handle_params does a patch redirect, it is possible for a user to get stuck in an infinite loop. This can be expensive if the application performs any querying inside of handle_params/3
For a dead render, the browser will handle this, as it will give an `ERR_TOO_MANY_REDIRECTS` - however for a patch, the browser never actually handles the redirect.
This commit simply stores a counter every time a patch occurs, and if there's no render between patches, then it will raise, giving the developer a clue where to look for the loop.
```
Mix.install([
{:phoenix_playground, "~> 0.1.6"},
{:phoenix_live_view, "~> 1.0.4"}
])
defmodule DemoLive do
use Phoenix.LiveView
{:ok, assign(socket, permitted: true, count: 0)}
end
def …
```

Raise if there are too many redirects without a render

---

lib/phoenix_live_view/test/client_proxy.ex
lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/upload/channel_test.exs

When someone does a push_navigate in the progress callback of an upload, the render_upload function of LiveViewTest sometimes did not properly return the live_redirect error tuple. This happened because the UploadChannel closes as soon as an upload is consumed. When this happens in the progress callback, the test code and the channel code raced:
The channel sends a redirect message to itself (or the root view) which shuts down once it receives it. The test code triggers a new render through the ClientProxy. Now it could happen that:
1. the test process can successfully call the ClientProxy, but the ClientProxy then crashed while pinging the channel
2. or the ClientProxy succeeds in pinging and actually returns the new HTML while the test expects the redirect error tuple
3. or the channel …

fix race conditions when upload progress redirects

---

assets/js/phoenix_live_view/js.js
assets/test/js_test.js

When `JS.exec` is used with the scope selector it throws an error complaining bad selector.
> Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.
This PR updates the JS code to execute the command for elements that have already been filtered by `to` option.

Fix JS.exec with scope selector

---

lib/phoenix_component/declarative.ex

Popover API is now "Newly available" so it's supported in the latest browsers
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

Add `popover` to global attributes list

---

lib/phoenix_component.ex

Dynamic attributes need to have atom keys. String keys can work but fail in certain cases, like `<.form ... {attrs_with_string_keys()}>` because the form component checks for atom keys in `assigns.rest`
This update makes the requirement explicit.

Doc change to make atom keys explicit for dynamic attributes

---

assets/js/phoenix_live_view/dom_patch.js
lib/phoenix_live_view.ex
test/e2e/support/issues/issue_3681.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3681.spec.js
test/phoenix_live_view/integrations/live_view_test.exs

Fixes #3681.
Child LiveViews would use the same data-phx-stream-ref, so it could happen that they were cleared unexpectedly because we did not always check the owner of the stream element when pruning.
There was another issue at play though: because we used assign_new to set the streams, nested LiveViews would copy a parent's streams, instead of creating a fresh one. This would lead to mixed up streams in the dead render.

fix streams in sticky LV being reset when same ref

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/support/issues/issue_3684.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3684.spec.js

Fixes: https://github.com/phoenixframework/phoenix_live_view/issues/3684.
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3652
The issue was that when we locked a form with an input inside where the input changed, the form was cloned and then later the input inside was cloned as well, stored inside the already cloned parent. When undoing, previously the simple patch copied over the PHX_PRIVATE of the cloned elements, but with the full DOMPatch, the privates of the source element were copied, discarding the clone of the input. With this change, we check if we are undoing locks and manually copy over nested clones to ensure that they can be correctly applied afterwards.

recursively undo cloned trees

---

lib/phoenix_live_view/js.ex

`<div>` tag in example didn't have a closing tag.

JS.transition example html tag fix

---

assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3709.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3709.spec.js

applyPendingDiffs had a race condition where updates were silently dropped if when trying to apply them there was already a new pending link. We fix this by skipping applyPendingDiffs when a link is still pending.
Fixes #3709.
Bug originally reported by @Gazler:
https://gist.github.com/Gazler/80dac42d3134ff55219853f1cb105e78

Fix pending link update race condition

---

assets/js/phoenix_live_view/constants.js
assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/view.js
assets/test/view_test.js

See https://elixirforum.com/t/delaying-liveview-js-commands-avoid-quick-flash-of-trying-to-reconnect/64035.
Relates to: https://github.com/phoenixframework/phoenix/pull/5735
Closes: https://github.com/phoenixframework/phoenix/issues/6031
Maybe we need to tweak the timeout or make it configurable?

delay phx-disconnected to prevent reconnect flash

---

lib/phoenix_live_view/channel.ex

If a LiveView implements `code_change/3`, it returns an updated socket. The channel should return an updated state with the updated socket instead of the updated socket itself.

Return updated state instead of updated socket

---

assets/js/phoenix_live_view/view.js
assets/test/js_test.js
assets/test/view_test.js
lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/js.ex

Alternative implementation for #3674.
Closes #3674.

Send JS command values on phx-submit

---

lib/phoenix_component.ex

I had a problem with nested live view testing where the test helpers did not understand where to send the click events.
This was discussed in issue #3393 and a subsequent read of the code makes it clear to me that there is no obvious way to have the test infrastructure walk up the DOM or process tree looking for the correct child to send clicks to (if someone knows a way to fix that I would love to encourage you to look into it).
So barring that, and informed by a separate conversation in the forums, here are some bits of advice gleaned from those two conversations. I think if the core Phoenix crew believes that Nested LiveViews are something you should use very sparingly, then the docs should warn new users that they are flying into the proverbial terrain.
There are some old SO threads …

Clarifications about nested live views and their appropriate use

---

lib/phoenix_live_view/channel.ex
test/e2e/support/issues/issue_3719.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3719.spec.js

After #3688, the _target parameter was decoded too early, as it is now sent in the extra values that are merged into the form values.
Fixes #3719.

Fix _target not being correctly decoded

---

assets/js/phoenix_live_view/view.js
assets/test/view_test.js

Fixes #3727.
In LV <= 1.0.5 we sent the `_target` as part of the url encoded form values, but in 1.0.6 we switched to sending the meta values directly in the form event to support `JS.push`'s value parameter for nested values. Since the event itself is JSON encoded, this meant that any keys with undefined value would be dropped by JS. To be backwards compatible, we now ensure that the `_target` is always sent and restore the old behavior of it being the string `"undefined"`, although that seems a bit ugly. It is what it is now...

Ensure `_target` is sent as `"undefined"` when it doesn't exist

---

lib/phoenix_live_view/test/live_view_test.ex
test/phoenix_live_view/integrations/nested_test.exs

I'd like to be able to assert that a redirection happened no matter the path.
So if my paths change I don't have to change them on the tests too.
Usually if I don't want one redirection to happen I don't want any.
Looking at the code I saw that the private function refute_navigation supports `to` being `nil` and does exactly what I want, so the change should be this easy :)

fix: allow refute_redirect to refute any redirections

---

lib/phoenix_component.ex

I think the docs for `live_file_upload`, when demonstrating the usage of the drag and drop feature, should really do so using a `label` rather than a `div`. This makes the most semantic/a11y sense. To make it flow best, we should also introduce the concept of using the label in that manner in a little more detail in the paragraph above.
I also removed the class and placeholder comment from the second example. I think it adds more noise then it does really inform--anyone reading this should know they can add a class on there or add other markup inside the label.

Tweak file upload docs

---

assets/test/view_test.js
guides/client/bindings.md
guides/client/syncing-changes.md

`phx-page-loading` attribute was removed by 622f72d, but the docs still contain outdated code examples.

Update docs to remove mentions of phx-page-loading

---

lib/phoenix_live_view/test/dom.ex
lib/phoenix_live_view/test/tree_dom.ex
mix.exs

we cannot directly reference the LazyHTML struct, as it might not be available.

ensure LazyHTML is actually optional

---

guides/server/assigns-eex.md

~I noticed~ A colleague of mine noticed that some extra sneaky `>` were present in these two small `:for` examples.

Fix :for examples in documentation

---

guides/client/js-interop.md
lib/phoenix_live_view.ex

After recent updates to [@types/phoenix_live_view](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/phoenix_live_view), the existing JSDoc examples became outdated and no longer worked as intended. This PR updates those examples to align with the latest type definitions.
Note: Due to changes in the typings, autocomplete may be less helpful in some areas—for example, it works for lifecycle methods (like mounted, updated, etc.) but not for hook properties such as el, liveSocket, and others.

Update JSDoc for hook examples

---

lib/phoenix_component/declarative.ex
test/phoenix_component/declarative_assigns_test.exs
test/support/live_views/components.ex

Hello! I was struggling to effectively document a function component attribute's list of values or examples, and realized that the pattern-matching used in these lines doesn't quite work if there are any other keys present in `opt` (in my case, a `:default`).
https://github.com/phoenixframework/phoenix_live_view/blob/84c9aff10d7c25672c7b5143742bb9ede66c9507/lib/phoenix_component/declarative.ex#L985-L991
This PR adds support for documenting those component attributes which have both a default and a list of values or examples, along with a few test cases for verification.

document `attr` values/examples even when there is a default

---

assets/js/phoenix_live_view/view.js

Modify instances where `Promise.reject()` was called with non-Error values (e.g., strings, plain objects) to consistently use `Promise.reject(new Error(...))` instead.
The main motivation is debugging where errors are coming from:
1. Stack Traces: Error objects automatically capture a stack trace when created. This trace shows exactly where in the code the rejection originated. Rejecting with strings or other primitives loses this vital information.
2. Consistent Error Handling: Downstream .catch() blocks or async/await try...catch blocks can reliably expect an object with standard error properties (.message, .stack, .name). Handling arbitrary rejected types (strings, numbers, objects) complicates error handling logic and can lead to runtime errors if code tries to access properties that …

Ensure Promise rejections include stack traces

---

guides/client/bindings.md
lib/phoenix_live_view/test/client_proxy.ex
test/phoenix_live_view/integrations/elements_test.exs
test/support/live_views/elements.ex
test/support/live_views/general.ex
test/support/router.ex

At the moment, `phx-viewport-top` and `phx-viewport-bottom` can't really be tested in LiveViewTest when targeting a specific element. One can use `render_hook` targeting a view, because it skips the `phx-hook` validation, but when the events should target a LiveComponent, this doesn't work, as the specific element must be passed to render_hook.
As the phx-viewport bindings are implemented as a private hook on the client, it might make sense to specifically allow `render_hook` to work in that case as well. Another option would be to have a generalized `render_event` function that skips any validation, but @chrismccord didn't like that.
See also: https://elixirforum.com/t/testing-phx-viewport-bindings-in-liveview/68237

allow testing phx-viewport bindings with render_hook

---

assets/js/phoenix_live_view/view.js

https://github.com/phoenixframework/phoenix_live_view/pull/3443 changed the pushWithReply function to use promises instead. Previously, if we did not handle the timeout, it was just ignored, but now we reject the promise, which will cause unhandled promise rejections.
This PR adds catch clauses to all cases where we previously did not handle the timeout. At the moment, these log an error, but we can also silently drop if we want. cc @chrismccord
Supersedes https://github.com/phoenixframework/phoenix_live_view/pull/3760.

Catch promise rejections from pushWithReply

---

assets/js/phoenix_live_view/hooks.js
assets/js/phoenix_live_view/js_commands.js
assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/view_hook.js
assets/test/js_test.js
assets/test/live_socket_test.js

* expose js commands not only to hooks, but also as `liveSocket.js().show(el, opts)` etc.
* add navigate, patch and push commands

expose js commands through `liveSocket.js()`

---

guides/server/live-layouts.md

Hi all,
I realize this is in flux now with 1.8 RC, however, assuming the thrust of how root/app works isn't changing I'd like to propose the removal of the line documenting that root is used 'for both live views and controller rendered pages'.
I think this kind of *implies* that app layout can't be used in dead views, which is not the case. So I think this line does more harm then good.

Change line in layout docs about root/app difference

---

guides/server/telemetry.md
lib/phoenix_live_view/channel.ex
test/phoenix_live_view/integrations/live_components_test.exs

The people from [LiveDebugger](https://github.com/software-mansion/live-debugger) mentioned that they struggle to react to live components that are removed from a page. A new telemetry event should help.

add telemetry event after destroying a live component

---

assets/js/phoenix_live_view/aria.js
assets/test/js_test.js

MDN recommends that divs with tabindex of 0 should be focusable, and also recommends that tabindex should only ever be -1 or 0.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
This should allow `JS.focus_first/1` to work on divs with a tabindex of 0.

Allow 0 tabindex to be focusable

---

assets/js/phoenix_live_view/js.js
assets/js/phoenix_live_view/js_commands.js
assets/js/phoenix_live_view/view.js
assets/test/view_test.js
lib/phoenix_live_view/js.ex
test/e2e/support/js_live.ex
test/e2e/tests/js.spec.js

Sometimes it is useful to ignore updates to specific attributes. One famous example is the "new"-ish HTML `dialog` element that relies on an `open` attribute to determine if it is open or closed. The same applies to `details` elements. Importantly, when opened by a user, the browser sets this attribute by itself and LiveView should not overwrite it on patches, otherwise it would accidentally close it again.
Previously, the recommended way to handle such cases was to add a function to the `onBeforeElUpdated` dom option of the `liveSocket`. This is cumbersome though and especially for libraries leads to more friction, as more steps are necessary to install them.
Now, one can use `JS.ignore_attributes` in instead, for example:
```heex
<details phx-mounted={JS.ignore_attributes(["open"])}> …
```

Add `JS.ignore_attributes`

---

CHANGELOG.md

Highlight that the deduplication can result in different output.
One of my projects were implicitely depending on (which was not good),
but it was a bit long to find the version where this changed because the change is a bit "hidden" in the Enhancement section.

Update CHANGELOG for 1.0.2

---

lib/phoenix_live_view/channel.ex
lib/phoenix_live_view/debug.ex
test/phoenix_live_view/debug_test.exs

The BEAM provides us with all the tools we need for introspecting out runtime. Tools like [LiveDebugger](https://github.com/software-mansion/live-debugger) use this information for providing a rich UI to look into the inner workings of LiveView pages. At the moment, this requires knowledge about the internals of LiveView, using private APIs, some of which could break at any moment.
The idea behind `Phoenix.LiveView.Debug` is to provide a public API with functions for introspecting LiveViews (and LiveComponents, etc.) that can help tools like LiveDebugger, but also regular developers, for example when debugging inside a remote IEx console.
This is a first draft with limited functionality to get some feedback on what functionality would be useful.

Phoenix.LiveView.Debug

---

lib/phoenix_component.ex
lib/phoenix_live_view.ex

I've stumbled across the docs for `async_result` and was missing an example where an `AsyncResult` was coming from and added a simplified `mount` function from the `assign_async/4` docs and added some links between the two.
Also converted the reference to the moduledoc with an actual link you can click on.
The last commit i'm not sure of. All the other code examples in this module use code with indentation. When i change them to fenced code blocks (which the formatter can now use BTW), i get better syntax highlighting in my editor. Should i keep this change or propose that in another PR?

Improve doc links betweens `async result/1` and `assign_async/4`

---

assets/js/phoenix_live_view/view.js
assets/test/live_socket_test.ts
assets/test/test_helpers.ts
assets/test/view_test.ts

This could happen when a project's app.js is loaded twice.
See https://elixirforum.com/t/how-do-you-debug-state-changes-using-liveviews/70044/21.
Supersedes https://github.com/phoenixframework/phoenix_live_view/pull/3721.

complain when trying to bind an element to a second view

---

assets/js/phoenix_live_view/js.js
assets/js/phoenix_live_view/live_socket.js
assets/test/js_test.ts
lib/phoenix_live_view/js.ex
test/phoenix_live_view/js_test.exs

Relates to: https://github.com/phoenixframework/phoenix_live_view/issues/3516
When integrating external animation libraries like motion.dev, the existing JS functions are not sufficient. Instead, the third party library needs to be triggered via JS. This has the downside of not being able to block the DOM until the animation is complete, which prevents this from working when elements are removed using `phx-remove`.
This commit introduces a new `blocking: true` option to `JS.dispatch/3`, which injects a `done` function into the event's `detail` object.
Using this with motion could look like this:
```elixir
def render(assigns) do
~H"""
<div :if={@show} phx-remove={JS.dispatch("motion:rotate", blocking: true)}>
...
</div>
"""
end
```
```javascript
const { animate } = Motion …
```

Add blocking: true to JS.dispatch

---

assets/js/phoenix_live_view/dom_patch.js
lib/phoenix_live_view.ex
lib/phoenix_live_view/engine.ex
lib/phoenix_live_view/live_stream.ex
lib/phoenix_live_view/test/tree_dom.ex
test/e2e/tests/streams.spec.js
test/phoenix_live_view/integrations/stream_test.exs
test/phoenix_live_view/live_stream_test.exs
test/support/live_views/streams.ex

Fixes #2690.
Relates to: https://elixirforum.com/t/add-stream-update-to-liveview-streams/68107
Work in progress, no tests yet.
Please see the attached links and let's decide if this is something we now want to support.

stream_insert update_only aka stream_update

---

assets/js/phoenix_live_view/view.js
test/e2e/support/issues/issue_3819.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3819.spec.js

Supersedes https://github.com/phoenixframework/phoenix_live_view/issues/3819.
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3818.
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3819.

abort form recovery when there are no inputs

---

assets/js/phoenix_live_view/dom.js
assets/js/phoenix_live_view/live_socket.js
assets/js/phoenix_live_view/view.js
test/e2e/tests/streams.spec.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3784.
Because stream nodes are not indexed by morphdom,
new nodes that do not have an ID are just appended to the stream container. This leads to linear growth of text nodes.
There's a critical problem though as soon as locked trees are involved. When unlocking, the number of text nodes would double, leading to exponential growth of (in most cases empty) text nodes.
We already handled this problem for phx-update "append" / "prepend", but apparently forgot that this also happens in streams.

fix accumulation of empty text nodes in streams

---

lib/phoenix_live_view.ex

Fix documentation example using `:only-child` selector, with `block` that break table structure, using `table-row` instead, fixing the issue.
with block you won't have the cell that span over the whole row, even with `colspan="2"`.

only:block break table structure, table-row is a valid table context.

---

assets/js/phoenix_live_view/dom_patch.js
assets/test/integration/portal_test.ts
lib/phoenix_component.ex
test/e2e/support/portal.ex
test/e2e/tests/portal.spec.js

This allows someone to directly teleport into the `<body>`, for example.

allow any selector as portal target

---

guides/server/assigns-eex.md
lib/phoenix_component.ex
lib/phoenix_live_view/engine.ex
lib/phoenix_live_view/keyed_comprehension.ex
lib/phoenix_live_view/tag_engine.ex
test/phoenix_live_view/diff_test.exs
test/phoenix_live_view/tag_engine_test.exs

A keyed for comprehension works by transforming the comprehension's content into a LiveComponent, which will perform change-tracking and optimizes the payload over the wire:
```heex
<ul>
<li :for={%{id: id, name: name} <- @items} :key={id}>
Count: <span>{@count}</span>,
item: {name}
</li>
</ul>
```
Because they use live components under the hood, keyed comprehensions come with the limitation of only being supported on HTML tags, so while you can use a regular `:for` comprehension on `<.function_components>`, and `<:slots>`, this is not supported keyed comprehensions and will raise an exception at compile time.

introduce `:key`-ed `:for` comprehensions

---

CHANGELOG.md
lib/phoenix_component/macro_component.ex
lib/phoenix_live_view/colocated_hook.ex
lib/phoenix_live_view/colocated_js.ex

We're exploring a more powerful approach to macro components (see https://github.com/phoenixframework/phoenix_live_view/pull/3846), therefore, to prevent breaking changes, we do not want to make the current interface public for the LiveView 1.1 release. Instead, we just expose colocated hooks and colocated JS for now.

make macro components private for now

---

guides/client/js-interop.md

Someone asked about this today in discord which I realized I had not seen myself. 
I was left looking for more info after reading the docs I then found this. 
https://elixirforum.com/t/use-case-for-returning-reply-map-socket-in-handle-event-callback/42917/2
So I thought to give a better example in the docs.

update: add an example of using :reply in the handle_event callback

---

assets/js/phoenix_live_view/view_hook.ts
assets/test/view_test.ts

This is required for backwards compatibility. When re-writing the code to support giving classes, I added a check to prevent overwriting the hook's own properties, but this is actually used by hooks in the wild, so we only log a warning instead.

allow overwriting hook properties

---

lib/phoenix_live_view/tag_engine.ex
test/phoenix_component/macro_component_integration_test.exs

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3877.
I'm not sure though if we want this, since it would still fail if you do
```elixir
def render(assigns) do
~H"""
<script :type={ColocatedHook} ...>...</script>
<div>
...
</div>
"""
end
```
because the extra whitespace between the colocated hook and the div counts as text that sets root to false.
So in practice, this may not help much.

root tracking for macro components

---

lib/phoenix_live_view/html_formatter.ex

- Update stale links to MDN documentation
- Spell out inline elements as the list has since been removed from MDN
- Clarify the distinction between block and inline elements at the first mention
- (Code-level comment) Call out `<script>` as a notable omission from the inline elements list
Closes #3870.

Update inline/block element considerations in HTML formatter docs

---

package.json

Without something like this, we get the following when using moduleResolution "bundler":
```
js/app.ts:3:34 - error TS7016: Could not find a declaration file for module 'phoenix_live_view'.
'[...]/node_modules/phoenix_live_view/priv/static/phoenix_live_view.esm.js' implicitly has an 'any' type.
There are types at '[...]/node_modules/phoenix_live_view/assets/js/types/index.d.ts', but this result
could not be resolved when respecting package.json "exports". The 'phoenix_live_view' library may need
to update its package.json or typings.
3 import { Hook, LiveSocket } from "phoenix_live_view"
~~~~~~~~~~~~~~~~~~~
```
I'm not confident this is the correct solution for all cases, but I do confirm it means my types resolve correctly!

package.json: list type exports.

---

lib/phoenix_live_view/engine.ex
test/e2e/support/issues/issue_3919.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3919.spec.js
test/phoenix_component/rendering_test.exs

Closes #3919.
Supersedes https://github.com/phoenixframework/phoenix_live_view/pull/3922.
When passing dynamic assigns to a component, we cannot make any assumptions about what keys are considered changed, therefore we need to disable change tracking.
Consider this example:
When a component is called and it receives dynamic attributes
```heex
<.my_component {@action[:attrs] || %{}}>{@action.text}</.my_component>
```
defined as
```elixir
attr :special, :boolean, default: false
defp my_component(assigns) do
~H"""
<div style={if(@special, do: "background-color: red;")}>
{render_slot(@inner_block)}
</div>
"""
end
```
Now assuming it is rendered first with `@action` as `%{text: "No red"}` and then toggling between that and `%{text: "Red", attrs: %{special: true}`:
Previously, once toggled, the …

Disable change tracking when passing dynamic assigns

---

assets/js/phoenix_live_view/view.js
test/e2e/support/form_dynamic_inputs_live.ex
test/e2e/support/form_live.ex
test/e2e/tests/forms.spec.js

The previous algorithm had a flaw:
```javascript
const clonedForm = form.cloneNode(false);
DOM.copyPrivates(clonedForm, form);
Array.from(form.elements).forEach((el) => {
morphdom(clonedEl, el);
DOM.copyPrivates(clonedEl, el);
clonedForm.appendChild(clonedEl);
}
```
While this kept the size of the clonedForm minimal and includes all elements, it did not consider `<fieldset>` elements. If you had something like this:
```html
<form>
<fieldset>
<input name="foo" value="bar">
</fieldset>
</form>
```
`form.elements` would return `[fieldset, input]`, thus we would actually include the input twice.
Furthermore, imagine someone did `<fieldset disabled>` which disables all inputs inside and should exclude them from the form payload. But with the old code, LiveView would copy the input separately. …

Deep clone form for form recovery

---

lib/phoenix_live_view/engine.ex
test/e2e/support/issues/issue_3931.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3931.spec.js

To fully disable change tracking, we need to force `__changed__` to nil.
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3931.

Ensure __changed__ is reset when using dynamic assigns

---

assets/js/phoenix_live_view/dom_patch.js
test/e2e/support/issues/issue_3941.ex
test/e2e/test_helper.exs
test/e2e/tests/issues/3941.spec.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3941. Possibly related to https://github.com/phoenixframework/phoenix_live_view/issues/3614.
When a component-only diff was applied, we did not account for the component being part of a locked tree. Thus, when the tree was unlocked, the component content was unintentionally restored to a previous state.
We solve this by checking for a locked tree and applying the patch to that instead.

Ensure component only patches are not lost due to locked tree

---

assets/js/phoenix_live_view/view_hook.ts

closes #3955 
using [covariant](https://www.typescriptlang.org/docs/handbook/2/generics.html#:~:text=//%20Covariant%20annotation) notation for hook generics.

Use Covariant Notation For Hook Generic 

---

lib/phoenix_live_view/test/diff.ex
test/phoenix_live_view/test/diff_test.exs

[Example liveivew app](https://github.com/achempion/comprehensions_demo/commit/65e7c70cf38d8355a9aaec47abccadf80050fd74)
[Related PR that added comprehension support](https://github.com/phoenixframework/phoenix_live_view/pull/3865)
When changing order of items that liveview renders with comprehensions, it raises an error: ` expected a map, got: [1, %{1 => %{0 => "test2"}}]`. It happens only in test ENV.
This PR adds support for `ClientProxy` to resolve moved comprehensions, mimicking the js logic added in [related PR](https://github.com/phoenixframework/phoenix_live_view/pull/3865/files#diff-9f139357c1e651029d78dab584420ff07bb7d67349814662aba368fc590cc985R257).
<details>
<summary>Full error from the liveview app</summary>
```elixir
** (BadMapError) expected a map, got: [1, %{1 => %{0 => …
```

Resolve moved comprehensions in test client proxy

---

lib/phoenix_live_view.ex

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3352.

Add note about redirect channel shutdown

---

assets/js/phoenix_live_view/view.js
test/e2e/support/form_live.ex
test/e2e/tests/forms.spec.js

Closes https://github.com/phoenixframework/phoenix_live_view/issues/3964.
When a LiveView is not fully mounted, pending events are pushed into pendingJoinOps. In case of a rejoin, pendingJoinOps were never executed though, so a push_patch during form recovery would get lost.
This is caused by us special casing the first join from rejoins.
On the first join, quoting the code:
> In order to provide a better experience, we want to join all LiveViews
> first and only then apply their patches.
All child LiveViews are joined and report their status to the root view. During that time, pending events are pushed into the root view's pendingJoinOps. The second join skips the acknowledgements and immediately applies the patches. Previously, pending events (most likely only due to form recovery as …

Ensure pending ops run after form recovery

---

CHANGELOG.md

Fix incorrect heading level for one of the versions in the CHANGELOG
Here's what is looks like in hexdocs right now:

Fix heading in CHANGELOG

---

lib/phoenix_component.ex
lib/phoenix_live_view/colocated_js.ex
test/phoenix_live_view/colocated_js_test.exs

and document node_modules handling
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3985.

allow auto-symlinking node_modules for ColocatedJS

---

lib/phoenix_live_view/html_algebra.ex
test/phoenix_live_view/html_formatter_test.exs

In the case where an inline tag has a nested inline tag, and there are spaces before and after text in the parent tag, extra spaces are continually appended each time HTML is formatted (ie if formatting on autosave in an editor, this keeps pumping on spaces every time a template is saved)
This is funny when you spam save in neovim, and you see a little HTML tag crawl across the buffer like a worm 😆 - but ends up in way too much git diff spam
https://github.com/user-attachments/assets/1cebe23f-083c-4e66-88b4-4ad26529b354
e.g.
```elixir
str = "<a> foo <b>bar</b></a>"
str
|> Phoenix.LiveView.HTMLFormatter.format([])
str
|> Phoenix.LiveView.HTMLFormatter.format([])
|> Phoenix.LiveView.HTMLFormatter.format([])
"<a> foo   <b>bar</b></a>\n"
str
|> Phoenix.LiveView.HTMLFormatter.format([])
|> …
```

Fix extra spaces being continually added when formatting nested inline tags

---

lib/phoenix_live_view.ex

This sentence could be understood that the socket assigns was inside `Phoenix.LiveView.AsyncResult`.

Adjust wording about async operations for better clarity

---

lib/phoenix_live_view/colocated_js.ex

This example provides a simple LiveComponent which clarifies where the imports should go when using a `ColocatedHook`.

Improve example for importing code from dependencies in colocated hooks

---

assets/js/phoenix_live_view/view.js
test/e2e/support/form_live.ex
test/e2e/tests/forms.spec.js

This won't work if the form is part of a nested LiveView, since we clean up any teleported elements when the owner view is destroyed and it is when the parent view disconnects. I don't think this is really necessary, but too much work to change right now.

Recover teleported forms

---

lib/phoenix_live_view/channel.ex
test/phoenix_live_view/integrations/hooks_test.exs
test/support/live_views/lifecycle.ex

As noted in the documentation for `Phoenix.LiveView.attach_hook/4`:
> Hooks attached to the `:handle_event` stage are able to reply to client events by returning `{:halt, reply, socket}`.
However, doing so from within a LiveComponent, where `:handle_event` hooks are supported, resulted in an error (see below for a minimal app reproducing the bug):
```
** (ArgumentError) invalid return from PhoenixPlayground.Router.DelegateLive.handle_event/3 callback.
Expected one of:
{:noreply, %Socket{}}
{:reply, map, %Socket{}}
Got: {:halt, %{"hello" => "world"}, #Phoenix.LiveView.Socket<...>}
```
Looking through the source of the functions in the stack trace, I noticed that `Phoenix.LiveView.Channel.inner_component_handle_event/4` was missing a case for `{:halt, reply, socket}` return values from …

Enable `:handle_event` hooks to reply from LiveComponents

---

lib/phoenix_live_view/igniter/upgrade_to_1_1.ex
test/phoenix_live_view/igniter/upgrade_to_1_1_test.exs

This PR is a proposal to upgrade `:esbuild` to the minimum version `0.10` while running Igniter in order to avoid errors on [joining environment variables](https://github.com/phoenixframework/esbuild/blob/main/CHANGELOG.md#v0100-2025-05-27).
Please check my main concern about showing an unclear message because of the usage of `quote`.

Upgrade :esbuild to minimum version when upgrading to 1.1
