lib/phoenix_live_view.ex
Fix little typo. Great work btw!
=> Fix typo in documentation in phoenix_live_view.ex

assets/js/phoenix_live_view.js, lib/phoenix_live_view.ex
The docs refer to `keyCode`, but the actual Javascript grabs the `key` value off the event.
=> Corrects mentioned JS attribute to reflect code

README.md
💁 The project build location had changed to the OSS instance of Travis CI but the URL for the build status image remained unchanged.
=> Fix build status image

mix.exs
Run `mix docs` then `open docs/index.html` for local hex docs while the hex package isn't published.
=> Add ex_doc so docs can be generated with mix

README.md
The README.md files installation guide uses MyApp, Demo and App in the guide this pull request changes all the app references to MyApp.
=> Update README.md to consistently use MyApp

lib/phoenix_live_view/test/live_view_test.ex
The `render_keyup` event was calling `render_event` with an incorrect second parameter.
=> Corrects typo in render_event helper

lib/phoenix_live_view.ex
Currently the example will allow any key other than the `@up_key` to decrement the temperature. Because there is also a catch-all keypress handler defined, I think this is supposed to pattern match on the `@down_key`.
If it really should allow for any key, the catch-all definition should be removed since this one is currently a catch-all.
=> Use @down_key in example

README.md
and add code formatting to nearby filenames
=> Consistently use “file:” in the README’s suggested package.json

lib/phoenix_live_view/view.ex
Fixes #97 
The correct config should be at `MyAppWeb.Endpoint`, not `MyApp.Endpoint`.
=> Fix arg error for configured_signing_salt!

lib/phoenix_live_view/engine.ex
code, generated by `~L` sigil contains chunks of code like this: 
```elixir
case(
if(Phoenix.LiveView.Engine.fetch_assign!(assigns, :tick) == 200) do
"selected"
else
""
end
) do
%{__struct__: Phoenix.LiveView.Rendered} = other ->
other
{:safe, data} ->
data
bin when is_binary(bin) ->
Plug.HTML.html_escape_to_iodata(bin)
other ->
Phoenix.HTML.Safe.to_iodata(other)
end
```
and for Dialyzer it's obvious that first clause here will never match. This is valid warning, and this PR just suppress it, because currently it's too hard to infer case expression argument type in compile time.
=> suppress dialyzer wanrings in generated code for ~L sigil

lib/phoenix_live_view.ex
Removing a duplicate line, the first of which had a type with a space in "LiveView"
=> Typo Correction - Duplicate Line

lib/phoenix_live_view.ex
Correcting typo with missing letter 'n' on the word button
=> Typo Correction "Butto"

README.md
First, awesome.
Second, as I was going through the installation, I forgot to pull in the new NPM library.  I thoughts others might benefit from the friendly reminder so here's a PR to add some notes about it.
I added an explicit note in the action instructions, as well as a troubleshooting with the exact error you will see for the forgotten step.
If there is something I am missing to have the npm libs automatically managed, then please let me know as I usually forget to update my NPM libs locally.
=> I forgot to `npm install`, I added an explicit note to the README

lib/phoenix_live_view/controller.ex
The existing example for `Phoenix.LiveView.Controller.live_render/3` didn't look like valid elixir code. This updates the example to look like the one in `Phoenix.LiveView`'s moduledoc:
https://github.com/phoenixframework/phoenix_live_view/blob/92e4fd9fe15dcf639c97e7daef80f3cf30505dc3/lib/phoenix_live_view.ex#L215-L225
If you have other changes you'd like to see in this example, I'd be happy to make additional updates.
=> Update example for Controller.live_render/3

lib/phoenix_live_view.ex
From all of the LiveView modules in `test/support` it looks like we're supposed to add `use Phoenix.LiveView` to our modules as well. This updates the examples accordingly.
=> Add "use Phoenix.LiveView" in examples

README.md
The formatter was moved to Phoenix itself and this info is no longer correct
=> Remove formatter info from README

lib/phoenix_live_view/channel.ex
If the live process monitors another process, down message is not correctly forwarded, because the channel always assumes that the parent process has terminated. As a result, the channel process will crash if a down message from a non-parent is received.
This commit switches to pattern matching which resolves the crash, and also properly forwards down messages to callback handle_info.
=> properly handle down messages

assets/package.json
Since patching elements like Select && Option happen at the end of the morphing phase, there was an issue updating the html with new options that came from the server.  This fixed it.
(note can you push up an updated lockfile?  I don't know how to pin it without updating all the other deps)
https://github.com/patrick-steele-idem/morphdom/pull/117
https://github.com/patrick-steele-idem/morphdom/blob/master/CHANGELOG.md#252
=> Morphdom 2.5.2 containing fix for wrong select option getting selected

README.md
Based on question posed here
https://github.com/phoenixframework/phoenix/pull/3376#discussion_r275772263
I am updating the documentation to suggest that the controller also get the `live_render` method directly available in the controller.
=> Include documentation on importing the live_render in the controller

lib/phoenix_live_view.ex
It wasn't obvious to me that I could pass session values in the router,
so I expanded the router example here to show that and linked to the
module for more options.
I also wanted to show usage from within a template, since I think it's
really cool to be able to casually drop in a live section. 😎
=> Expand router example and add template example

assets/js/phoenix_live_view.js
Edge doesn't seem to like receiving a FormData object in the
constructor for the URLSearchParams class.
I haven't attempted to fix the IsPersonal error, or compatibility
with IE11.
Fixes #191.
=> Fix URLSearchParams constructor call on Edge

assets/js/phoenix_live_view.js, assets/test/view_test.js
**Problem**
1) #170: Previously when users defined their own container element to use as the Phoenix Live container, any class attribute defined would be overridden by the JS client library on connection, disconnection and error.
2) #179: `element.classList` is a [read-only property](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList), and we write to it in multiple places causing issues for some browsers.
**Solution**
With this change, the client library only controls classes it "owns" and thus any existing defined classes are left untouched by the lifecycle process. On top of that, `classList` is never written to directly.
Solves #170 and (partially) #179.
=> Fix JS to respect user implemented container classes

README.md
I believe because the version isn't changing, you have to force an install to get the latest javascript.  Note that I could not get the `--prefix` to work so instead opted for (`cd assets && ... `)
The output should look similar to
```
$ (cd assets && npm install --force phoenix_live_view)
npm WARN using --force I sure hope you know what you are doing.
/Users/aforward/sin/projects/current/payday/dividends/assets
└── phoenix_live_view@0.1.0-dev 
npm WARN assets No description
```
=> Force an upgrade of the 'same' version

lib/phoenix_live_view.ex
* Update docs to send user_id in session from template in `Phoenix.LiveView.live_render/3`
* Consistent with recommendation elsewhere to only send integers, strings, etc. in session
=> Update docs to send user_id in session from template

lib/phoenix_live_view/test/live_view_test.ex
Should be `assert_remove` instead of `assert_removed`
=> Update assert_remove/3 typo in documentation

lib/phoenix_live_view/test/live_view_test.ex
* Update LiveViewTest docs with `import Phoenix.LiveViewTest`
* Examples using `LiveViewTest.live/1` as `{:ok, view, html} = live(conn)` need import
* Also applies to other functions called without module in the docs
=> Update LiveViewTest docs

lib/phoenix_live_view.ex
This fixes a method name in the documentation.
=> Change `link_link` to `live_link` in Live navigation documentation

lib/phoenix_live_view/router.ex
The example uses the module name for layout as if `scope` were to work like an alias. The layout module needs to be aliased elsewhere or the fully qualified module needs to be used.
=> Update example with fully-qualified namespace

README.md
Closes #260 
We are using `classList` to [add and remove CSS classes](https://github.com/phoenixframework/phoenix_live_view/blob/1e12305ca065f99543fc66db6504cb8c8f30c9fc/assets/js/phoenix_live_view.js#L816-L823) but IE does not support multiple parameters for the add() & remove() methods. Adding the `classlist-polyfill` fixes this issue.
References:
https://caniuse.com/#search=classList
=> Update README.md IE polyfill support

README.md
Also format `import LiveSocket` statement consistently with earlier example.
=> Clarify location of polyfill imports

lib/phoenix_live_view/plug.ex, test/phoenix_live_view/plug_test.exs
```
GET /
Sent 500 in 408µs
Converted error {:case_clause, ["com.facebook.katana"]} to 500 response
[error] #PID<0.15816.0> running WhatcardWeb.Endpoint (connection #PID<0.15815.0>, stream id 1) terminated
Server: some.site.com:80 (http)
Request: GET /?q=something
** (exit) an exception was raised:
** (CaseClauseError) no case clause matching: ["com.facebook.katana"]
(phoenix_live_view) lib/phoenix_live_view/plug.ex:59: Phoenix.LiveView.Plug.live_link?/1
(phoenix_live_view) lib/phoenix_live_view/plug.ex:22: Phoenix.LiveView.Plug.call/2
(phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
(whatcard) lib/whatcard_web/endpoint.ex:1: WhatcardWeb.Endpoint.plug_builder_call/2
(whatcard) lib/whatcard_web/endpoint.ex:1: WhatcardWeb.Endpoint.call/2
(phoenix) …
```
=> Fix error in live view plug when `x-requested-with` header is present.

lib/phoenix_live_view.ex, test/phoenix_live_view/phoenix_live_view_test.exs
Hi Chris,
I want to be able to style `live_link/2`, this PR preserve the opts given to `live_link/2` and overrides the `data-phx-live-link` and `href` attributes if set.
Let me know what you think?
Signed-off-by: Benjamin Schultzer <benjamin@schultzer.com>
=> Preserve opts in live_link/2

assets/js/phoenix_live_view.js
The change validates the type of element on which you are trying to apply the PHX_DISABLE_WITH logic to set a new text.
=> FIXES #234

assets/js/phoenix_live_view.js, lib/phoenix_live_view/channel.ex
1. `onLiveRedirect` should directly change the state since
`handle_params/3` has already been called on the server
2. Preserve "kind" (push/replace) on `onExternalLiveRedirect`
3. Treat `external_live_redirect` as live redirects on replies
=> A couple of proposed changes to the live navigation feature

lib/phoenix_live_view/test/live_view_test.ex
The option key is supposed to be `:connect_params` https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L228
=> Typo in live_view_test.ex

lib/phoenix_live_view.ex
Does what it says on the tin: fixes a small typo :+1:
=> Fix typo in phoenix_live_view docs

lib/phoenix_live_view/channel.ex
Since liveview was updated, I'm having trouble when listening to change events inside a form on elements like multiple_selects because their names (html attribute name specifically) ends with [] (like object[attribute][]). Phoenix multiple_select method creates html elements with names ending in []
I'm using elixir 1.9, phoenix 1.4.10, Erlang/OTP 22.
You can try to reproduce this error using the following template (it won't even reach handle_event("apply_changes") inside the liveview).
```html
<form action="#" phx-submit="submit_form"  phx-change="apply_changes">
<%= multiple_select :object, :attribute, @attribute_values, selected: @object[:attribute] %>
<%= submit "Apply changes" %>
</form>
```
```
name = 'object[attribute][]'
```
```
[error] GenServer #PID<0.857.0> terminating
** …
```
=> Fix crash when name of element ends on []

lib/phoenix_live_view/socket.ex
Solution: define the type, to be usable as `Phoenix.LiveView.Socket.t` instead of `%Phoenix.LiveView.Socket{}`
=> Problem: can't refer to Phoenix.LiveView.Socket as Phoenix.LiveView.Socket.t

lib/phoenix_live_view.ex
`Phoenix.LiveView.Channel` does not seem to handle `:reply` in the `handle_info/2` callback. This also matches the behaviour of GenServer which does not support `:reply` in `handle_info/2`.
=> Make handle_info's typespec more accurate

lib/phoenix_live_view/plug.ex
I believe the two clauses represented no extra information.
Thanks for reviewing.
=> Remove case clauses and use catch-all

lib/phoenix_live_view/channel.ex
The ref argument is always passed with nil value.
=> Remove unused private function case

lib/phoenix_live_view/plug.ex
The session_opts variable was renamed to session_keys in top of the file so I also renamed it in the private function.
The other one is just a refactor that I believe makes the code easier to read.
Edit: it also sets the` :container` key explicitly to `nil` in the keyword list. The calls in the `View` module check for `nil` so the code is correct this way too.
Thanks for reviewing.
=> Small refactors

lib/phoenix_live_view.ex
Currently in LiveView's  callback documentation, the socket param is showing up as `arg_*` and the the `handle_call/3`'s `from` param is showing up as `{}`.
This PR does 2 things:
1. Sets a name for the unnamed `socket` params 
2. Updates the type of the `LiveView.from` type from `binary` to `{pid, reference}` and references this `from` type from the `handle_call/3` callback.
If the `from` type was supposed to be a `binary`, I'd be happy to remove that change and fix name of `handle_call/3`'s second argument in another way.
=> Improve argument names in callbacks

lib/phoenix_live_view/router.ex, test/support/layout_view.ex
If your module looks like `App.Web.Router`, than application doesn't work and there is no way to fix it. Better approach for concatenation would be not to assume how long the prefix is, but just swap the last module name with `LayoutView`.
=> Fix module concat for layout

lib/phoenix_live_view.ex
Thought it would be nice to see all the available binding attributes in one spot.
=> Add table of contents for phx-* binding attributes

lib/phoenix_live_view.ex
I don't believe the raw key codes work any more, so match against the more intuitive named key instead.
It was confusing setting up key events knowing what I'd be getting here,
so provide a more illustrative example of what values are sent back.
=> Improve the key events docs and example

lib/phoenix_live_view.ex
- Ensure all values representing code are formatted as code.
- Format JS code
=> Docs: Format code values lists

lib/phoenix_live_view.ex
All other examples of this call use `/live` as the socket endpoint.
I had a head-scratching moment when trying out hooks and pasted this line in and was met with many error messages about not joining the correct channel. It took me a while to spot the error.
This change would prevent similar mistakes from being made. If on the other hand this is intentional, some explanation would be useful.
=> Make socket endpoint examples consistent in docs

lib/phoenix_live_component.ex, lib/phoenix_live_view.ex
The word "compartmentalize" was consistently but incorrectly spelled as "compartimentalize".
This corrects that for the documentation.
Loving the new live components. :smile:
=> fix consistent misspelling

README.md
When adding LiveView to a Phoenix application located in an umbrella project, the JS and CSS dependency paths are incorrect due to where the `deps` folder is located.
This PR adds the correct paths to the installation instructions. Hopefully it'll save some people five minutes!
=> Add umbrella app specific dependency paths to installation instructions

lib/phoenix_live_component.ex
This updates example in documentation - both previous and next entry refer to `GridComponent`
=> Change TableComponent to GridComponent in docs example

lib/phoenix_live_component.ex
The `action` argument is required for [`Phoenix.HTML.Form.form_for`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/2).
=> Fix examples in LiveComponent documentation

package.json
**Background:**
In generic project `phoenix_live_view` is included into `package.json ` with recommended
package.json entry:
```
...
"dependencies": {
"phoenix_live_view": "file:./deps/phoenix_live_view"
}
...
```
which installs node_module with whole contents of `./deps/phoenix_live_view`.
**The problem:**
Some of devs could prefer to build frontend independently from backend by adding npm package into package.json:
```
...
"dependencies": {
"phoenix_live_view": "0.3.1",
}
...
```
In this case npm includes into install only configured files and does not include live_view.css.
**Solution**
In order to make npm package complete, live_view.css should be included into package files.
=> Add live_view.css into package files

lib/phoenix_live_view/engine.ex
When the extra_clauses in Engine.to_safe are not marked as `:generated`, dialyzer will complain that the compiled ast will never match some of the clauses. Something like:
```
The pattern can never match the type.
Pattern:
_ = %Phoenix.LiveView.Rendered{}
Type:
nil | <<_::56>>
________________________________________________________________________________
The pattern can never match the type.
Pattern:
_ = %Phoenix.LiveView.Component{}
Type:
nil | <<_::56>>
________________________________________________________________________________
The pattern can never match the type.
Pattern:
_ = %Phoenix.LiveView.Comprehension{}
Type:
nil | <<_::56>>
```
=> Mark extra_clauses in to_safe as :generated

lib/phoenix_live_view/plug.ex, lib/phoenix_live_view/router.ex, test/phoenix_live_view/plug_test.exs
If there are multiple routes pointing to the same live view, there is no way for the live view to know which route it came from.  I found this problematic when trying to build a REST inspired live view.
```elixir
scope "/groups" do
live "/", MyApp.Live.GroupControllerLive
live "/:id", MyApp.Live.GroupControllerLive
live "/:id/edit", MyApp.Live.GroupControllerLive
end
```
The problem with this is that `handle_params` can't tell which route was matched, and therefore it can't call the appropriate "action".
This PR allows the `session` option to also accept static values which are injected directly into the live view session.  That allows me to do:
```elixir
scope "/groups" do
live "/", MyApp.Live.GroupControllerLive, session: [action: :index]
live "/:id", MyApp.Live.GroupControllerLive, …
```
=> Implemented static assigns in the `live` router macro

assets/js/phoenix_live_view.js
At the moment hooks `this.pushEvent`calls are going to LiveView instead of a possible component. This PR should fix that.
Please let me know if i should do the PR including the built `priv/static/phoenix_live_view.js`.
=> fix pushEvent for components

lib/phoenix_live_view/utils.ex
This is called for every socket so I guess it can’t hurt being faster 😄 
This is based on https://github.com/phoenixframework/phoenix_pubsub/pull/130 which is based on improvement in Elixir Plug.RequestID https://github.com/elixir-plug/plug/issues/629
=> Improve random_encoded_bytes performance

assets/js/phoenix_live_view.js
In #437 the concept of "main" was added and I suspect is related.  
In my own app that contains a live layout that contains a live_render 
navbar, live_links stopped working (`href on undefined`).  I tracked 
it down to this line.  I'm not sure if this change is fully sufficient or if 
there should be a null check, first try root, then try main, etc.
=> use liveSocket.main.href instead of liveSocket.root.href

lib/phoenix_live_view/controller.ex, lib/phoenix_live_view/static.ex, test/phoenix_live_view/integrations/params_test.exs
I had a use case in a router-rendered LiveView where I wanted to immediately redirect with flash a user passing invalid params.  Using redirect in `handle_params/3` worked great but the flash message was not rendered.  When `handle_params` first runs in disconnected state on the static render any flash set on the socket wasn't persisted. 
It was simplest for me to return the whole `%Socket{}` and pattern match in `Phoenix.LiveView.Controller` to copy any flash into the `conn` but please feel free to modify the implementation or provide feedback if there is a cleaner way to do it.
Also I'm not sure if the third pattern in `Controller.live_render` is ever called outside of tests anymore so I didn't add flash handling there at this point.
=> Support setting flash in disconnected handle_params

lib/phoenix_live_view/test/live_view_test.ex
Fix https://github.com/phoenixframework/phoenix_live_view/issues/482
I'm moving the check to run right before `DOM.find_views/1` is called then we can see the error regarding Floki not loaded.
=> Fix error when floki is not loaded

CHANGELOG.md, guides/introduction/installation.md, lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/controller.ex, lib/phoenix_live_view/plug.ex, lib/phoenix_live_view/socket.ex, lib/phoenix_live_view/static.ex, lib/phoenix_live_view/test/client_proxy.ex, lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/controller_test.exs, test/phoenix_live_view/integrations/components_test.exs, test/phoenix_live_view/integrations/live_view_test.exs, test/phoenix_live_view/plug_test.exs, test/phoenix_live_view/router_test.exs, test/support/live_views.ex, test/support/router.ex
=> Automatically load session and csrf token

lib/phoenix_live_component.ex
Phoenix.LiveComponent appeared to be missing its behaviour when calling `use Phoenix.LiveComponent`. I assume this was unintentional, so I have added it here. Additional related changes:
* Alias Phoenix.LiveView.Socket for callback specs
* Add preload/1 to optional_callbacks list
* Fix params spec in handle_event/3 callback
**Current Docs:**
**Updated Docs:**
=> Add @behaviour to LiveComponent

lib/phoenix_live_component.ex
Heho! 
While getting started with live components and doing some copy & pasting from the docs I stumbled over the `\`. So I made it more consistent to the docs of the `Phoenix.LiveView` and therefore removed the `~S`. When I checked how the `@moduledoc` is used in Elixir for example, I couldn't really figure out when the string sigil is used 🤷‍♂ Cheers!
[Current Docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#content)
Updated Docs
=> Fix moduledoc for live components

assets/js/phoenix_live_view.js
This also provides a mechanism to recover from cold deploys which change the session payload contract.
Closes #351
=> Reload page on connected mount to trigger regular plug pipeline error handling

lib/phoenix_live_view/static.ex, lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/controller_test.exs, test/phoenix_live_view/integrations/live_view_test.exs, test/phoenix_live_view/integrations/update_test.exs, test/support/live_views.ex, test/support/router.ex
Now that LiveView shares its session options with Plug, and the session received in `mount/2` gets string keys from the session, a few regressions popped up that this PR attempts to fix.
**Changes:**
1. Ensure `Plug.Test.init_test_session/2` is called when using `LiveViewTest.live_isolated/3`.
1. ~Convert root-level atom keys to strings for custom session data (mimicking Plug.Session)~
1. Emit a warning when a non-binary session key is provided.
1. Add tests for live_isolated/3 and live_render/3
~I left in the TODO about warning on atom keys -- didn't want to bikeshed on the wording, but I'm assuming that even if we issue a warning, we'd still convert the keys.~
Supercedes #514
=> Warn on mixed session keys, test regression after session consolidation

lib/phoenix_live_view/plug.ex
Previously on 0.4.1 this allowed `key` to always be present in the liveview session:
```
live MyView, session: [:key]
```
In `master` / `0.5.x` this will cause a warning because `:key` is an atom, changing it to a string causes a case match error.
This PR treat single strings as if they were atoms, and sets it in the session restoring the old behaviour with the new string key format. An alternative solution is to cast the key from the atom to a string in the line above, but I'm not sure if that would allow atom keys elsewhere...
=> Allow single string keys in the router

lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/static.ex, test/phoenix_live_view/integrations/live_view_test.exs
An expired session token is currently not accounted for in error handling and passes through to causes a error log entry. This update handles an expired session token in the same way as an outdated token, by reloading with jitter and not logging an error.
=> Reload with jitter on expired session token

assets/js/phoenix_live_view.js
`process.env.NODE_ENV` is "development" in a development webpack build.
`process.env.NODE_ENV` is "production" in a production webpack build.
```js
if (DEBUG) {
// this block will be stripped from a production build by webpack
}
```
We could use this for all sorts of things like detecting duplicate `id`s and deprecating events ref #536
=> DEBUG flag

assets/js/phoenix_live_view.js
This should allow a user to open links in a new tab by doing:
- Control key (to allow users to open in new tab on Windows/Linux/etc.)
- Meta key (to allow command-click for macOS, which is used in lieu of control-click)
- Middle mouse click as an alternative, which is also generally used to do the same
This is in reference to issue #528 and seems to add the desired functionality. I did some quick testing and it appears to work in my use case. Please let me know if there is anything I overlooked or if you see any improvements, I'll be glad to assist.
Thanks!
=> Added overrides for live link navigation

assets/js/phoenix_live_view.js
resolves #493 
It adds `offsetX` and `offsetY` to click event metadata in `phoenix_live_view.js`, which are the click coordinates relative to the clicked element.
**A use case**: when clicking on a big rectangular div where we want to render new elements.
=> Add offsetX and offsetY to click event metadata

lib/phoenix_live_view/controller.ex, lib/phoenix_live_view/static.ex, test/phoenix_live_view/controller_test.exs, test/support/layout_view.ex, test/support/live_views.ex, test/support/router.ex
**Issue**
Although LiveView calculates socket assigns prior to the static layout being rendered, this data is not currently reflected. Data in the socket assigns can be useful for populating SEO fields; i.e. title, meta.
**Resolution**
Socket assigns are now returned as part of `LiveView.Static.render/3`. These are merged with content and passed into `Phoenix.Controller.render/3`.
> Note: This solves only for initial layout availability. The change does not intend to solve for dynamic updating.
@mcrumm
=> Merge socket assigns for static render

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/live_view_test.exs
We don't have a public function in `LiveViewTest` to use with "hook events", the ones that can be triggered from JS code via [ViewHook.pushEvent](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L1316).
This PR adds a `render_hook` helper, which is very similar to other existing functions such as `render_submit`, `render_update`, etc.
=> Add render_hook function to LiveViewTest

lib/phoenix_live_view/helpers.ex
Recent improvements on Elixir master allow to better track columns and
thus produce better stacktraces. For e.g.:
defmodule AppWeb.ThermostatLive do
use Phoenix.LiveView
def render(assigns) do
~L"""
Current temperature: <%= @temperature %><% end %>
"""
end
end
previously we had:
** (EEx.SyntaxError) foo.ex:6: unexpected end of expression <% end %>
but with this change we can know where exactly (which line+column) the
error occurs:
** (EEx.SyntaxError) foo.ex:6:45: unexpected end of expression <% end %>
=> Pass :indentation to EEx

lib/phoenix_live_view.ex
ref #546 
Very slight documentation improvement.  I think this is important because it is easy to miss this when the element in question does not receive focus by default.  Anchor tags, links, buttons, inputs, selects, textareas do.  However, often a `div` is used as the element with `phx-keydown` and if it doesn't have `tabindex="0"`, events like `keydown` will not fire on the element.
=> Add documentation about focus and window key events

CHANGELOG.md, guides/introduction/installation.md
Hello and thank you for LiveView!
While upgrading from 4 to 5 I found that the socket was no longer connecting, and traced it to the socket not being able to read the `csrf_content_tag`... because I had included it in the wrong order!
I hope this helps, let me know if it can be improved :smile: 
This may be related to issue #575
=> Specify location of csrf_meta_tag in docs

assets/js/phoenix_live_view.js
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/575
We don't need to get the URL from any other place than `this.href`. Also, this optional after 07aa098e5526cd1000d6270d40ea98c27f415ed6 and 07aa098e5526cd1000d6270d40ea98c27f415ed6.
=> Properly get URL from live socket

assets/js/phoenix_live_view.js
This pull request makes form `change` events to take it's `phx-target` from `form` tag instead of the input tag. This makes it consistent with `submit` event.
=> on form "change" event take "phx-target" from form instead of input

lib/phoenix_live_view.ex
when live view neither defines mount/3 or /mount2
=> Fix compilation error `undefined function mount/2`

lib/phoenix_live_view/plug.ex, test/phoenix_live_view/plug_test.exs
Stops dialyzer from warning about `unmatched_return` from the `live/3` macro:
```shell
lib/my_app_web/router.ex:13:unmatched_return
The expression produces a value of type:
atom() | {atom(), Keyword.t()}
but this value is unmatched.
```
// @chrismccord
=> Match Plug.opts type for LiveView.Plug

guides/introduction/installation.md
The session_options in the installation docs could need a bit of clarification to make it explicit what a user needs to do to install. I have added 3 steps to make it crystal clear. 
Let me know what you think.
=> clarify docs on @session_options attribute

assets/js/phoenix_live_view.js
blur() and immediately focus() raise virtual keyboard close and
immediately open.
i tested on browsers bromite, chromium, fennec and had problems while
inputing the fist symbol in input field if event rate is frequently than
one per second.
could you please review @chrismccord
=> fix virtual keyboard on mobile browser

lib/phoenix_live_view.ex
I was missing this data attribute which lead to having to ask other folks on the #phoenix channel in Slack, because I am not sure that "For proper form error tag updates" was clear enough about what the result of having/not having the attribute would be. Hopefully this makes it a bit clearer for the next person.
=> Improves explanation of data-phx-error-for

lib/phoenix_live_view/helpers.ex
Fixing a few minor typos in the doc for live_redirect in helpers.ex.
=> Fix typos in docs

lib/phoenix_live_view/test/live_view_test.ex
These mainly fix typos.
There are also two changes to example tests that either make them easier to read (a test that asserts children have been removed should send a `:msg_that_removes_children`, not a `:msg_that_removes_child`) or clarifies the test context (underscore prefix for unused variable).
'side-effect' lost a hyphen to conform with spelling elsewhere. Neither here nor there but now it's consistent accross the project.
Etc.
=> Typos and tiny clarifying changes to LiveViewTest

assets/js/phoenix_live_view.js, assets/test/view_test.js
This PR ensures that a property, if not present in the `source` element, it is removed from the `target` element.
```js
// target
<input checked="true" type="checkbox" />
// source
<input type="checkbox" />
```
=> Ensure mergeAttributes removes extraneous attrs

README.md, assets/js/phoenix_live_view.js, lib/phoenix_live_view.ex, test/phoenix_live_view/integrations/live_view_test.exs, test/support/live_views/general.ex
- Recommend and use `key` instead
- Update tests to use `key` instead of raw numeric codes
`charCode`, `keyCode`, and `which` are all deprecated, poorly supported cross-browser and should not be relied on.
See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Browser_compatibility for more details on this.
For more background see #536. This is also related to #535.
=> Remove deprecated key event fields

lib/phoenix_live_view.ex
- Note that `charCode`, `keyCode`, `which` are all deprecated and should not be relied on see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Browser_compatibility
- Point users to list of valid key codes (so they aren't doing by trial and error like I've done in the past)
- Point users to more info around all key event info including modifier keys and browser support
=> Docs: Add a note about key event values and usage

assets/js/phoenix_live_view.js
Sync checkbox checked props with server attr on updates.
Skip focused select attribute merge because FF has
quirky UI behavior when any setAttribute is called
on the select while in a hover state. Closes #615
// @snewcomer
=> Fix checkboxes and select on updates.

guides/introduction/installation.md
Not sure if y'all still want this file updated (or if it should really point you to install from gh), but `0.6.0` seems like an outdated version to point to.
=> Update installation.md to use latest version

lib/phoenix_live_view.ex
Using `phx-keydown` and `phx-keyup` with `phx-target="window"` has been
replaced with `phx-window-keydown` and `phx-window-keyup` as of `v0.7.0`
=> Add `phx-window-key` events to docs

assets/css/live_view.css, assets/js/phoenix_live_view.js, assets/test/view_test.js, lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex
Closes #569 #89
This likely also removes the need for `phx-disable-with`, though we could still keep it as a convenience. For example, the following css rules in your app.css:
```css
.phx-loading-show { display: none; }
.phx-loading-hide { display: block; }
.phx-loading > .phx-loading-show { display: block; }
.phx-loading > .phx-loading-hide { display: none; }
```
Could replace today's code:
```eex
<div>
<%= submit "Save", phx_disable_with: "Saving..." %>
</div>
```
With:
```eex
<div class="phx-loading-hide">
<%= submit "Save" %>
</div>
<div class="phx-loading-show">
<%= submit "Saving...", disabled: true %>
</div>
```
Slightly more verbose but much more flexible. I am also fine keeping disable-width as a text-only replacement convenience as the css will work either way.
=> Add data-ref with css lifecycle classes

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/static.ex, lib/phoenix_live_view/test/client_proxy.ex, lib/phoenix_live_view/test/live_view_test.ex, lib/phoenix_live_view/utils.ex, test/phoenix_live_view/integrations/live_view_test.exs, test/phoenix_live_view/integrations/params_test.exs, test/phoenix_live_view_test.exs, test/support/live_views/general.ex, test/support/router.ex
=> Allow redirects from mount

lib/phoenix_live_view/channel.ex
I noticed my LiveView client-side would sometimes get messages like `[null,null,"lv:phx-FfXBbBfjffgfdQVi","diff",{}]`
I'm not sure on the full implications, but it seemed safe to skip sending those diffs in my testing of my app? I think the cause in my case was doing some assigns that caused the socket to be changed, but did not ultimately lead to a change in the rendered content. I could put together a reproduction if it's helpful.
Even if my understanding is correct so far, I also wasn't sure if this should be fixed further up the chain.
=> Avoid sending blank diff

lib/phoenix_live_view.ex
The documentation is currently oddly formatted on hexdocs (see image) due to an extra pipe.
=> Fix event overview table in live_view docs

assets/js/phoenix_live_view.js
Function call history[kind + "State"](meta, "", undefined) replaces url to /undefined in IE11 and Microsoft Edge 44.17763.1.0
=> Fix incorrect behavior history.replaceState for IE

assets/js/phoenix_live_view.js
Call of `node.isSameNode(null)` in IE11 leads to an error `Invalid pointer`
`focused` can be null because [document.activeElement can be null](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement)
=> Fix isSameNode check in IE11

README.md
Without a template polyfill I faced with `Unable to get property 'querySelector' of undefined or null reference` error in `formsForRecovery` function in IE11.
=> Add @webcomponents/template polyfill for IE11

lib/phoenix_live_view/router.ex, test/phoenix_live_view/router_test.exs, test/support/router.ex
It is on allowing the same behavior for the metadata key, as phoenix does.
Passing metadata to `Phoenix.LiveView.Router.live/4` set metadata as part of the privates while doing it in `Phoenix.Router.get/4` is merged with metadata key useful to telemetry feeds, as Phoenix documentation says.
=> Support user-defined metadata

lib/phoenix_live_view.ex
> events propagate inwards from the clicked element
Just a minor clarification that the event starts at `window` and goes down the DOM tree to the target element.
=> Improve Event Capturing docs

lib/phoenix_live_view.ex
* correcting some typos: "wiht", "loadng"
* moving the sentence that was interposed in the example after it:
"In the case of forms, when a phx-change is sent to the server, the input element which emitted the change receives the phx-change-loading class, along wiht the parent form tag."
=> improve docs

guides/introduction/installation.md
Not a big change, but my editor compiles the project on save and when following the installation guide I thought I did something wrong in the `:fetch_live_flash` step since the compilation failed and I had to double check.
Inverting these two steps fixes the issue.
=> Invert adding import and fetch_live_flash installation steps

guides/introduction/installation.md
Most common mistake users have when adding LiveView to an already generated project is forgetting about adding the combo `put_root_layout` + `@inner_content` to their project.
`Live Layouts` section of the docs is quite down the page, so I think adding a notice to it in the installation docs might help those that otherwise might spend some time wondering why their LiveView isn't connecting after doing everything in the installation instructions.
I see Phoenix is adding a `phx.gen.live` in the upcoming release which will take care of these things, so this might only be needed temporarily.
=> improve installation.md docs

lib/phoenix_live_view.ex
A few missing space means that we got rendered html instead of the code. That is not what we want i think :smile:
=> Fix indentation in documentation

lib/phoenix_live_view/channel.ex
Notice that the error message doesn't have a space between the view and the rest of the error message.
```because MyAppWeb.DashboardLive.Indexwas not```
=> Add whitespace to the error message

lib/phoenix_live_component.ex
There were a couple of examples where `live_component` is called without `@socket`. As far as I can see this is no longer supported behaviour? This PR updates those two references, and optionally, updates `live_component/2` to `live_component/3` as assigns are given pretty much everywhere.
Originates from a confused person in the liveview channel on elixir slack.
=> Improve `live_component` docs.

lib/phoenix_live_view/engine.ex
Hey @josevalim 👋 
Just fix a typo in the improved error message.
=> Fix typo in error message

assets/js/phoenix_live_view.js, lib/phoenix_live_view/diff.ex, test/phoenix_live_view/diff_test.exs
Various optimizations:
- for a component with a single HTML root, we can skip patching the `data-phx-component` parent node, which requires marking all non-component siblings and skipped when we morph. This avoid traversing unnecessary child nodes
- fixes an issue where a diff for a component-only update caused the entire LV container to be patched
- the server now computes all the component cids that are touched when a diff is calculated, and sends them to the client with a component diff. This allows us to avoid computing LiveView template content that is not part of the component update.
- optimizes append/prepend updates by no longer cloning the entire LV DOM container, walking the children, then converting the computed string for morphdom to re-parse and walk
=> Optimize client rendering

assets/js/phoenix_live_view.js
The `detail` property on click events returns the click count. This value resets after a short timeout, so it's generally `1` for single-clicks, `2` for double-clicks, and occasionally `3` if you click really fast. Support from [IE9+](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail).
It's very useful for detecting double-clicks with a simple pattern-match:
```elixir
def handle_event("click", %{"detail" => 2}, socket) do
end
```
=> Add detail to phx-click metadata

lib/phoenix_live_component.ex
`live_link` is no longer public. In my quick testing both `live_patch` and `live_redirect` work from inside a LiveComponent
=> Fix LiveComponent doc

CHANGELOG.md
Specifically set link to use the 0.10.0 version of the docs so that the link does not get outdated in the future. This will help users in the future who are upgrading LiveView step-by-step.
=> Update Live Layouts link in changelog

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/live_view_test.exs, test/support/controller.ex, test/support/router.ex
Addresses #798 
If the conn passed to LiveViewTest.__live__/2 has a `:sent` state but status code other than 200 or 302, raise ArgumentError with explanatory message instead of treating the request as unsent.
=> Improve LiveViewTest.__live__/2 error

lib/phoenix_live_view.ex
Hi,
There is already a note included for this at the top of the doc, but maybe a reminder in the form section could be helpful for the less experienced members of the community?
Thank you :)
=> Additional reminder to include "use Phoenix.HTML"

lib/phoenix_live_view.ex
The `live_socket_id` is `users_sockets`, while the broadcast clause uses `users_socket`.
=> Fix doc typo on disconnecting live_socket_id

lib/phoenix_live_view/test/live_view_test.ex
Issue: https://github.com/phoenixframework/phoenix_live_view/issues/820
Calling the `live` macro in tests blows up if the session has not been fetched yet. This is a problem if the application is configured to not have any sessions.
Please let me me know if this is the right direction. Also I am struggling to write a test for it. How would I setup the conn without a fetched session?
=> Phoenix.LiveViewTest doesn't work without session

lib/phoenix_live_component.ex
Following the [docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#content) today w/ phoenix 1.5.1 and LV 0.12.1 I found that my components `inner_content` wasn't in assigns and at first I didn't understand why. I thought to add this minor clarification so people who might follow will have a more clear understanding of "where" this `inner_content` comes from.
Here was the original error I ran into for reference
=> Clarification for LiveComponent inner_content

lib/phoenix_live_view.ex
This is not quite the right wording, and I expect it applies to other socket functions, but `put_flash` works inside a component, but only with the local flash in the components socket, its not updated back to the top level.
E.g. in a stateful component you can do:
```
def handle_event("save", %{}, socket) do
{:noreply, socket |> put_flash(:info, "Saved!")}
end
```
And it will display in any `live_flash(@flash, :info)` in the component, but not reach the top level flash.
This came from a slack conversation about this, I think its at least worth mentioning this distinction.
=> Expand put_flash/3 caveats

lib/phoenix_live_view.ex
Super minor issue that fixes the link under https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-bindings for "JS Interop", it was annoying me so I fixed it.
=> Fix JS Interop anchor link

lib/phoenix_live_view.ex
1. `redirect/2` is a reference to `Phoenix.Controller.redirect/2`
and needs to be explicitly mentioned with full module name to be clear
and consistent with how `Phoenix.HTML.link/2` is listed in the previous
sentence.
2. `push_patch/2` and `push_redirect/2` are shown with full module name
to be consistent with the previous sentence.
3. `push_redirect/2` in the example is changed to `push_patch/2` because we are
comparing it with `live_patch/2`
=> Use redirect examples consistently

lib/phoenix_live_view/renderer.ex
This way, when the user creates the template the LV would automatically
be recompiled. (And since live_reload already worked here, the user will
see their template used.)
=> When there is no template or render/1, add `@external_resource template`

assets/js/phoenix_live_view.js, assets/test/view_test.js
Only redirects and live redirects are valid
ways to terminate a LiveView connection and
they already call .leave() explicitly on the
client.
=> Do not allow graceful closes

lib/phoenix_live_view.ex
Added a reminder in docs to import AppWeb.ErrorHelpers when using error_tag/2.
Thank you.
=> Reminder in docs to import AppWeb.ErrorHelpers

assets/js/phoenix_live_view.js
While reading the JS source code I found some JSDoc comments does not represent params correctly. I suppose those should be corrected this way:
- `[opts.hooks]` should be an `Object` instead of `string`
- `[opts.defaults]` should be an `Object` instead of `Function`
=> Fix LiveSocket jsdoc

lib/phoenix_live_view/test/live_view_test.ex
Suggestion on how to improve the docs regarding render_change and metadata values. Related to https://github.com/phoenixframework/phoenix_live_view/pull/854
Maybe the assert on the example may be improved?
I didn't touch render_click docs considering that https://github.com/phoenixframework/phoenix_live_view/issues/819 isn't defined yet.
=> Improve render_change docs to mention metadata values

lib/phoenix_live_view/test/live_view_test.ex
Wrong description in the summary for `render_blur`, probably came from a suboptimal copy paste. 
(this is my first contribution to elixir :D )
=> fix docs typo in live_view_test render_blur

assets/js/phoenix_live_view.js, assets/test/debounce_test.js
If a user interacts with an input with a phx-debounce on it, the timer
is now cleared. This ensures that the debounce will not trigger until
after the user input has stopped.
=> fix(debounce): reset debounce on user input

lib/phoenix_live_view/test/live_view_test.ex
As discussed with @josevalim in #861 I've added some improvements to the docs of a `render_hook/3` function so it would be more clear that you can call it on the `element()` and that the element needs to have a `phx-target` attribute assigned.
I would also like to add an argument type handler to the `handle_params/3`, ([check Jose's reply](https://github.com/phoenixframework/phoenix_live_view/issues/861#issuecomment-624944502)), but since I'm fairly new to Elixir I'm not exactly sure where would be the right place for this improvement to be implemented. I was reading a lot about typespecs and was checking the repo, but still not sure. If you would be so kind to point me in the right direction, I'd be more than happy to implement that as well.
=> Improved docs for LiveTest.render_hook/3

lib/phoenix_live_view.ex
Make it more clear that `send_update/2` operates on a `Phoenix.LiveComponent` and that it can only update components mounted on the parent LiveView.
I also made the mentioned callback links link to the actual callbacks. This makes it more clear exactly which callback is being referenced. Additionally if the documentation was left as it was and a `LiveView.preload/1` function was added, then an improper link would have been created.
I also separated the paragraph that talks about the implementation from the one that talks about the requirements since the combined paragraph would have felt rather long. The paragraph about the implementation was reworded to make it more clear what the subject was (the component being sent the message).
Made it more clear that the `:id` must be passed in the …
=> Update PhoenixLiveView.send_update/2 docs

lib/phoenix_live_view.ex
Keeping the `= _session` in the `mount` example because it makes sense there to clarify to the doc reader that this argument is the session. But adding an underscore since this code would result in a warning otherwise.
Skipping `= _session` in `assign_defaults` examples because it's clear by then that we're dealing with a session.
=> Docs: Fix assign_defaults examples and a would-be warning

lib/phoenix_live_view.ex
As discussed in #909.
Wasn't sure where to put it exactly, but this seemed a reasonable place.
Think it's good for it to have its own header both for linkability and so it stands out a bit.
=> Docs: Add "Avoiding issues by adding a form ID" section

assets/js/phoenix_live_view.js, assets/test/rendered_test.js, lib/phoenix_live_view/application.ex, lib/phoenix_live_view/diff.ex, lib/phoenix_live_view/test/client_proxy.ex, lib/phoenix_live_view/test/dom.ex, mix.exs, test/phoenix_live_view/diff_test.exs
This PR adds static sharing between components, a great idea proposed by @henrik in #912.
In order to support this, the client needs two changes:
1. After every diff, we need to traverse the components keys resolving any integer static that we may find. You can find the code that does this in the [Elixir client here](https://github.com/phoenixframework/phoenix_live_view/blob/jv-share-c/lib/phoenix_live_view/test/dom.ex#L121-L146). Note the static references themselves can nest, so the `find_static` function has to be recursive. Also note this pass is also necessary on the initial render, so it is best to consider the initial render to be the same as: `Diff.merge_diff(%{}, initial_render)`
2. When the client submits the `cids_destroyed` event, the components must only be removed from the …
=> Share component statics

guides/introduction/installation.md
When I first used `liveSocket.enableLatencySim(1000)` it was hard to figure it out that it was still enabled as I did enabled it on the app.js file directly. I did try to disable it with `liveSocket.enableLatencySim(0)`. 😄 
In my case I used the phoenix project generator `--live`. Perhaps, we could add the comment to the `app.js` as well when generated as well.
=> Clarify usage of enableLatencySim in docs

guides/introduction/installation.md
Potentially confusing to show this one without the EEx tags but the “render” with EEx tags.
Also more consistent.
=> installation.md: Clarify @inner_content rendering

guides/introduction/installation.md
“MyApp” and “my_app” is used elsewhere in the docs.
=> installation.md: Clarify name of my_app_web.ex

README.md
Running the provided command currently yields:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "core-js/features/set" as it does not contain a package.json file
```
I'm not sure this is the right fix, but it passes and appears to find the needed `set` polyfill.
=> fix npm polyfill command not referencing right package

lib/phoenix_live_component.ex
I like how the stateless component has this little lifecycle graph and thought it'd be nice here too.
It wasn't clear to me from the docs if `update` was called between the first mount and the first render or not, so I checked and figured I'd clarify.
I was surprised that `preload` was called before `mount`, but that's what my debug output told me.
Line 86 is a bit long but it seemed preferable to breaking it.
=> phoenix_live_component.ex: Clarify stateful lifecycle

package.json
Hello! This is a PR resulting while working with `phx-hook` to understand the ins-and-outs of the JS portion of liveview.
Due to the fact that the current `main` property in `package.json` points to the distributed version with no source maps, it's difficult to perform browser-based debugging.
With the following changes, you will allow other devs to go from:
to this when debugging JS files via browser:
Since we are using webpack to transpile both application and module code, there isn't a need to import the distributed version of the file when bringing in `phoenix_live_view` as a module.
Debuggers do allow pretty-printing options for compressed JS files, but you still lose context since all variables will be named differently.
Thanks for this awesome library - really fun to work with …
=> Retain ES6 syntax when being imported as a module

lib/phoenix_live_view.ex, lib/phoenix_live_view/helpers.ex
...as opposed to `live_redirect` & `push_redirect` that scrolls the window to the top.
=> document that 'live_patch' & 'push_patch' maintain scroll position

lib/phoenix_live_view/test/live_view_test.ex
Just a tiny issue I noticed while browsing the documentation.
=> Fix syntax error in documentation

lib/phoenix_live_view/test/live_view_test.ex
Hello! The event summary is missing an entry for `render_hook` and I overlooked it as I was looking for a more generic "render_event" :joy:. This adds it!
I optionally improved the grammar here, as `event and value and returns` reads a bit weird, I'm happy to drop this commit if you prefer though.
=> Improve docs for render_hook.

lib/phoenix_live_view.ex
Having just come across this myself and not knowing the idiomatic thing to
do, I thought it would be a good idea to change the example.
In the current example, it returns `{:error, reason}` which would raise.
Personally, I think it would be better if Phoenix LiveView offered a
first class way of dealing with errors in mount/3. For now, I would
suggest that we have an example that redirects to an error page or shows
how to render an error.
This change redirects to some random "/error" page. If there is a
suggestion for a better exmaple, I am happy to change it.
=> Change the error example in LiveView mount

package.json
Reverts phoenixframework/phoenix_live_view#961
=> Revert "Retain ES6 syntax when being imported as a module"

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/diff.ex, lib/phoenix_live_view/static.ex, lib/phoenix_live_view/utils.ex, mix.exs, mix.lock, test/phoenix_live_view/integrations/live_view_test.exs, test/phoenix_live_view/integrations/params_test.exs, test/support/live_views/general.ex, test/support/live_views/params.ex, test/support/router.ex, test/support/telemetry_test_helpers.ex
This starts adding telemetry events for #676. It currently adds the following events:
* `[phoenix_live_view, :mount, :start]`
* `[phoenix_live_view, :mount, :stop]`
* `[phoenix_live_view, :mount, :exception]`
Notes
* This only instruments `Phoenix.LiveView.mount/3` and not `Phoenix.LiveComponent.mount/1`. Should we instrument LiveComponent's mount as well? If so, what should the event name be?
* This also uses the unreleased `:telemetry.span/3` function. I can update the PR once the updated telemetry lib is released.
Also, I'm curious what other events would you like implemented?
=> Add telemetry events

assets/js/phoenix_live_view.js
The purpose of this PR is to allow other `popstate` event handlers to be registered in user code before LiveSocket's. LiveSocket currently registers its `popstate` event handler using `window.onpopstate`. The problem with this is it takes precedence over all other event handlers and there can only be one. The solution is to register the `popstate` event handler using `window.addEventListener`, which allows multiple event handlers to be registered and executed in the order in which they were registered.
I have a content editing page implemented as a LiveView. If the user attempts to navigate away without saving their work, I would like to warn them and give them the option to stay on the page.
I tried to address this by creating a `beforeunload` JavaScript event handler in a hook.
I …
=> Register "popstate" event handler using window.addEventListener

assets/js/phoenix_live_view.js
fixes #948
When an activeElement is removed from the page in a particular fashion,
Internet Explorer 11 does not make the body the `activeElement` and
returns `null` instead. This causes failures down in the stack when
something tries to access the element .
This patch chooses the easy approach and guards the usage against
this bug, instead of trying to solve the issue when it occurs. After
IE11 support is dropped, the workaround can be easily removed.
The comments were added to ensure this is not accidentally cleaned
up (according to spec, `activeElement` should never be `null`).
=> work around document.activeElement being null in Internet Explorer 11

assets/js/phoenix_live_view.js
This solves the problem described in issue #969 . This adds calling `beforeDestroy` on the hook of all children being removed when a parent is being removed too.
Just added the call to that function on the iteration that also calls `destroy()`.
Don't know if there are any tests that should be updated too.
=> Call beforeDestroy on children hooks when the element is being destroyed

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, test/phoenix_live_view/integrations/components_test.exs
This wraps `Phoenix.LiveComponent.handle_event/3` in a `:telemetry.span` which adds the following new events:
* `[:phoenix, :live_component, :handle_event, :start]`
* `[:phoenix, :live_component, :handle_event, :stop]`
* `[:phoenix, :live_component, :handle_event, :exception]`
A couple things to note... 
* I added `component` to the event metadata because it didn't seem like I could get the component off of the socket
* `metadata.reason` on the exception case is being returned as `{:case_clause, "boom"}`. It looks like if the subscriber want's the Elixir `CaseClauseError` version, the caller would have to run it through `Exception.normalize/3`.
* I grouped all of the `handle_event` tests in a single describe block. If you want to see the changes to add telemetry to handle_event in …
=> Add telemetry events for LiveComponent.handle_event/3

README.md
Add Erlang/OTP 21+ requirement to README to prevent [`(RuntimeError) Phoenix.LiveView requires Erlang/OTP 21+`](https://travis-ci.com/github/msaraiva/surface/jobs/352364023) when such requirement is not satisfied.
=> add Erlang/OTP 21+ requirement to README

.github/workflows/ci.yml
Quoting @josevalim:
> I would still advise folks to go with:
> * For each Elixir version, add a run with earliest supported Erlang/OTP
> * For the last Elixir version, also test the latest supported Erlang/OTP
Please refer to the original discussion on https://github.com/dashbitco/broadway/pull/188 for the full rationale.
In addition to adhere to @josevalim recommendation, it reduces the number of jobs from 6 to 5, making it more [environment friendly](https://github.com/elixir-lang/elixir/pull/10129#discussion_r446139904).
=> Add recommended Elixir x Erlang combinations to CI

lib/phoenix_live_view/test/live_view_test.ex
Since this was deprecated, aligning it with the newer version
=> use -> import of Phoenix.ConnTest + Plug.Conn

lib/phoenix_live_view/router.ex
`live "/", PageLive, :index, as: :xxx`
would compile with error "** (ArgumentError) could not infer :as option because a live action was given and the LiveView does not have a "Live" suffix. Please pass :as explicitly or make sure your LiveView is named like "FooLive" or "FooLive.Index"
=> fix router when action and :as specified

lib/phoenix_live_view/engine.ex
This PR improves the documentation (and typespec) for `Phoenix.LiveView.Rendered`. The previous documentation did not include changes to the Rendered structure made in the following two commits:
- https://github.com/phoenixframework/phoenix_live_view/commit/41549a5111090a6b39720bcc1d939c4c632134a8
- https://github.com/phoenixframework/phoenix_live_view/commit/aa5d4071e5dc249f982dca20c2c9d76bf875cd15
=> Improve documentation about `Phoenix.LiveView.Rendered`

lib/phoenix_live_view/helpers.ex
If you disagree with the full change, feel free to at least fix the "live_compoment" typo :)
Spotted that typo and then realised I didn't understand the error message, so I read up a little and then wrote something that I think I would have understood better.
=> Error message: fix typo and flesh out

lib/phoenix_live_view/engine.ex
Rendered fine to HTML but looks odd in its raw form.
=> engine.ex: Fix list number in doc

lib/phoenix_live_view/test/dom.ex, test/phoenix_live_view/test/dom_test.exs
This PR fixes a sort of subtle bug in LiveViewTest.
When we have an element with `phx-update="append"` and we update the attributes of a child node, they are not correctly patched
e.g if I try to do a dom patch of 
```html
<div id="foo" phx-update="append">
<div id="bar"></div>
</div>
```
with 
```html
<div id="foo" phx-update="append">
<div id="bar" class="class">something</div>
</div>
```
`DOM.patch_id` will result in the following
```html
<div id="foo" phx-update="append">
<div id="bar">something</div>
</div>
```
I also included some tests including an initially failing test for this particular bug.
=> Fix bug in LiveViewTest's handling of attributes during DOM patching 

lib/phoenix_live_component.ex, lib/phoenix_live_view/helpers.ex
Took me a few seconds to realise "a clause" meant "a function clause", so this could save the next person a few cycles :) Matches the phrasing in #1065.
=> Clarify component docs

lib/phoenix_live_view/helpers.ex
Include the file in compile warnings within the ~L sigil, fixing https://github.com/phoenixframework/phoenix_live_view/issues/1075
Before:
```
warning: trailing commas are not allowed inside function/macro call arguments
nofile:303
```
After:
```
warning: trailing commas are not allowed inside function/macro call arguments
test/phoenix_live_view/diff_test.exs:303
```
=> Display file on compile warning in sigil

assets/test/view_test.js
As I'm making a few PRs that change how we reorder nodes after phx-update=append/prepend, it made sense to factor out the test suite into its own PR.
Hopefully this covers most of the edge cases!
=> Test suite for phx-update node ordering

assets/js/phoenix_live_view.js, assets/test/view_test.js
I noticed that when submitting a form, LV will make all inputs and buttons `readonly` and `disabled` but doesn't care about `textarea` elements.
I didn't test for `select` elements but I guess it's the same issue there? I can add it if needed.
=> Disable texture on form submit

assets/js/phoenix_live_view.js, assets/test/debounce_test.js
There was a bug in the code that handles throttling keydown events, if you set a `phx-throttle` on that event, and continuously press the same key, only the first keypress will be registered, even if you wait past the timeout.
This PR fixes the issue -- we were returning too early from a nested if. I also added a test demonstrating the bug. Please let me know if you'd prefer me to split the commit with the test out so we have a commit with a failing test!
While I was at it, I switched to using `KeyboardEvent.key` instead of `KeyboardEvent.which` in order to track the keys being pressed. MDN says that [which is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which). I'm not sure what LiveView's attitude towards browser compatibility is -- if `which` is the best …
=> Fix bug where throttling keydown events would eat key presses

assets/js/phoenix_live_view.js, assets/test/view_test.js
This PR (mostly) fixes https://github.com/phoenixframework/phoenix_live_view/issues/978
Previously, when doing an append/prepend we would re-append every single child node of the container on each update. Instead, I factored out a class to handle the post-morphdom patching and improved the algorithm.
We now track the elements that were modified, along with their previous sibling, and any new ids added.
We can then fix the ordering by inserting each element next to the correct sibling. Since we are going in the original order they get put back in the right place.
If we are doing an append, our new elements are already at the bottom. If we are doing a prepend, we move them back to the top
I haven't run formal benchmarks, but I enabled profiling in my test game with a 750-element grid and …
=> Refactor appendPrependUpdates

lib/phoenix_live_view.ex
This clears up my confusion from #1091. Thanks!
=> Doc clarification: `assign_new` will not have access to `Plug.Conn` assigns

lib/phoenix_live_view/channel.ex
Similar to issue #324, LiveView is still crashing when an array is present on params. 
For example, when we have an input with [] in name, like below:
```html
<input type="text" name="order_item[addons][][name]" value="<%= addon_type.name %>">
```
LiveView crash on for submission.
```
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.gather_keys/2
(phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:410: Phoenix.LiveView.Channel.gather_keys([%{"name" => nil}], ["addons", "order_item"])
(phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:404: Phoenix.LiveView.Channel.decode_merge_target/1
(phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:395: Phoenix.LiveView.Channel.decode_event_type/2
(phoenix_live_view 0.14.2) …
```
=> Fix crash on array in params

guides/client/form-bindings.md
I've been working with a LiveView form that uses `phx-trigger-action` to forward the form data to a controller that starts a file download. The LiveView stays open after the form was submitted (because there's no browser redirect for the file download), leading to some interesting behavior. I found that any additional subsequent DOM patches in the LiveView would re-trigger the form submit and in my case a new file download.
Ideally, `phx-trigger-action` should only be set for the next DOM patch and unset for any subsequent updates. I was able to fix my problem by putting the `:trigger_action` variable in the temporary assigns.
This PR updates the guides to recommend the user also set `:trigger_action` up as a temporary assigns and provides a little background into why this is helpful. As …
=> Suggest `phx_trigger_action` variable be in temporary_assigns

lib/phoenix_live_view.ex
- It doesn't have to be done in a redirect scenario
Notes: Was asking around and tried it in an app and it seems like it doesn't have to be done in a redirect, so I thought to update the docs to hopefully reflect that. Open to suggestion.
=> Update documentation for put_flash/3

guides/server/security-model.md
This could also be
> If your HTTP requests perform auth[...] on every request[..]
though the double "request" there felt redundant, so I went with this.
=> Fix grammar in docs

lib/phoenix_live_view.ex, test/phoenix_live_view_test.exs
The docs already shows there exists `assign/2`. This should be more obvious as example also given.
=> Clarify assign/2|3 docs details

README.md
hi! while working on another PR for live view with @mveytsman, @7hoenix, and @cthulahoops, I realised that I didn't know how to run Javascript tests. @mveytsman checked and noticed that `mix test` only ran the Elixir tests. he kindly gave me instructions to run the Javascript tests. I've added these instructions to the docs.
thanks in advance for your feedback!
=> Add instructions to run javascript tests

guides/introduction/installation.md
I followed this guide and at the end didn't know the expected location for placing live views. So it seemed arbitrary. At first I considered to call it `live`, but ended up with `live_views`.
During development, I noticed that LiveReload was not working for my live views. I spent some time to figure out why was it so and finally discovered that 'dev.exs' config expects a different directory name.
Communicating this convention might be helpful and hopefully save another person from repeating my mistake.
=> Update installation guide with `/live` location

lib/phoenix_live_view/test/live_view_test.ex
It looks like the "#" is not needed when calling `find_live_child` in tests.
=> Remove "#" from `find_live_child` in documentation

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/controller.ex, test/phoenix_live_view/integrations/live_view_test.exs, test/phoenix_live_view_test.exs, test/support/live_views/general.ex
Invoking `Phoenix.LiveView.redirect/2` during a `Phoenix.LiveView.mount/3` with an external URL causes an `ArgumentError` to be raised during the subsequent render.
```elixir
defmodule MyView do
use Phoenix.LiveView
{:ok, redirect(socket, external: "https://phoenixframework.org")}
end
end
```
`Phoenix.LiveView.redirect/2`when invoked with an external URL, e.g. `redirect(socket, external: url)` causes the the `socket` to be annotated with `{:redirect, %{to: url}` in its `redirected` field, making it structurally indistiguishable from a local redirect as invoked with the `:to` option. The subsequent invocation of `Phoenix.LiveView.Controller.live_render/3` then calls `Phoenix.Controller.redirect(conn, to: to)`, which raises an `ArgumentError` if the …
=> External hard redirects

guides/client/form-bindings.md, guides/server/live-navigation.md, guides/server/security-model.md, guides/server/telemetry.md
Replacing raw function names by actual references to the functions/callbacks in .md files (guides) to make navigation easier and avoid callbacks appearing as `c:mount/3` in the markdown.
I replaced quite extensively, even at some places where it might not have been needed within the context. I figured it couldn't harm, but let me know if this was overkill :wink:
(Sorry, a bit hard to review due to re-arranging line breaks... Maybe better to turn the whitespace diff off or review the rendered markdown)
=> Fix function references in guides

lib/phoenix_live_view.ex
The view has the assign as `@static_change` instead of `@static_changed?`. Fixing the docs to reflect that.
=> Fixing static_change documentation

lib/phoenix_live_view/diff.ex, test/phoenix_live_view/diff_test.exs
Fixes https://github.com/phoenixframework/phoenix_live_view/issues/1125 it's possible live_component would produce `{d: [[]]}` (see component number 4 in test), this should cover all cases tree walker will run into.
=> Fix Diff.to_iodata/3 in case there is dynamic without static part

lib/phoenix_live_view/test/live_view_test.ex
The previous example that was given for `render_submit` and `render_change` can result in making a mistake if you copy/paste the example (it is highly likely that the *hidden_field* is inside the *user* object).
=> Make docs regarding testing hidden fields more consistent

assets/js/phoenix_live_view.js, assets/test/view_test.js, guides/client/form-bindings.md
Once the action is submitted, the current LiveView
terminates, which would be detected as a crash by
the client which would then try to reconnect.
If reconnecting failed (for example, because the
page is a single use token), the form submission
would be cancelled without concluding.
This commit addresses this by always disconnecting
before triggering the action. The current behaviour
can still be achieved with hooks in forms with custom
JS (which already require hooks anyway).
=> Fix race condition on phx-trigger-action

assets/js/phoenix_live_view.js
fixes #1136 
Since `getHashTargetEl` is single purpose, I don't see why the caller should need to provide the argument. This allows keeping the edge case check simple, i.e. it avoids `hash === "" || hash === "#"` (thanks to IE11). 
I have only tested this in the 'raw', non-minified form.
=> remove leading # when looking up hash target through getElementById

lib/phoenix_live_view/channel.ex
#1122 Fixed external redirects during the `mount` phase, but seems to have broken them during the rest of the live_view lifecycle.
To recreate this issue, create a new phoenix app with version 1.5.5, passing the `--live` option, and see that on localhost:4000, external redirects to the dependency hex docs do not work
I resolved this issue by adding a function head for `push_redirect` to change the `external` key to `to`
Alternatively, a case clause could have been added to `handle_redirect/5` at channel.ex:456, but this would have required additional duplicated code.
I was unable to find a sane place to add a test for this, as there is no channel_test.exs file... Happy to add one if someone can point me in the right direction.
=> Bugfix: External Redirects

lib/phoenix_live_view/helpers.ex
Just a tiny fix for a broken link, see the doc for https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Helpers.html#live_patch/2
Disclaimer - I could not figure out how to generate the docs, sorry, I'm very much new to these repos... So this is a "blind" fix but maybe someone could let me know how to generate the docs? Or confirm/fix my change directly if needed, thank you! 🙇
=> Fix handle_params callback link in doc

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/flash_test.exs, test/phoenix_live_view/integrations/params_test.exs
This still breaks one test for me locally (test/phoenix_live_view/integrations/live_view_test.exs:296), but I'm not really sure why it wasn't breaking for the same reason previously.
Closes #1161
=> Replace mount_url with Plug.Conn.request_url

lib/phoenix_live_view/engine.ex
The current form was quite confusing to me the first, as it awkwardly referring to the previous example.
=> Adjust grammar in leex template error messages

lib/phoenix_live_view/test/client_proxy.ex, test/phoenix_live_view/integrations/event_test.exs, test/support/live_views/events.ex, test/support/router.ex
This pull requests intends to allow the use of `assert_push_event/3` to test events pushed during `mount/3`
Given the following `mount/3` implementation
```elixir
@impl true
socket =
if connected?(socket),
do: push_event(socket, "test", %{"foo" => "bar"}),
else: socket
{:ok, socket}
end
```
Right now we are not able to successfully run the following test:
```elixir
test "event in mount", %{conn: conn} do
{:ok, page_live, _disconnected_html} = live(conn, "/")
assert_push_event(page_live, "test", %{"foo" => "bar"}, 2_000)
end
```
=> Allow assert_push_event/3 tests for mount/3

CHANGELOG.md
I simply found a small typo in the Changelog. Thanks for Phoenix LiveView. 🙂 Cheers! ❤️
=> Typo in changelog for 0.15.0

lib/phoenix_live_view/utils.ex
The signing salt should not only be present, but be a binary of
sufficient length.
I have seen a case where, due to a mistake in the build pipeline
setup, the value was a blank string.
=> Ensure the signing salt is a binary of sufficient length

assets/js/phoenix_live_view.js, assets/test/view_test.js
Fixes a tiny regression in 0904444e that prevents a LiveView with a form from completing the initial join.
=> Do not recover forms on first join

guides/server/uploads.md
The example in the uploads guide is missing a `phx-change` binding which is required for uploads to work.
This PR adds the binding, notes that it is required, and provides the minimal implementation for the callback.
This problem was actually called out in #1210 but no one went back and fixed the example in the docs.
=> Fix the server/upload guide so the example works as written.

mix.exs
This PR fix syntax error in mix.exs.
**Before**
```
> mix deps.get
** (SyntaxError) mix.exs:101:7: syntax error before: "Live EEx Engine"
(elixir 1.11.2) lib/code.ex:1172: Code.compile_file/2
(mix 1.11.2) lib/mix/cli.ex:42: Mix.CLI.load_mix_exs/0
(mix 1.11.2) lib/mix/cli.ex:29: Mix.CLI.proceed/1
```
**After**
```
> mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
...
```
=> Fix syntax error in mix.exs

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, test/phoenix_live_view/integrations/components_test.exs
Implementation of #1244 
I did not run the formatter since there was quite a few unformated files and I did not want to pollute the PR.
=> Allow to specify pid for send_update/3 & send_update_after/4 

lib/phoenix_live_view/test/client_proxy.ex
=> Fix case where multiple component ids break `--` (now reflects JS code)

lib/phoenix_live_view/test/live_view_test.ex
Noticed when writing tests for this that you need a list of maps because entries expects multiple files - otherwise you get a pattern match error.
The DOM ID also required a # or it wouldn't find the form DOM node.
=> Fix documentation bug in file_input

assets/js/phoenix_live_view.js
Fix https://github.com/phoenixframework/phoenix_live_view/issues/1139
This commit fix the issue so that textarea has been patched even though is focused.
=> Fix textarea being patched by LV while focused

lib/phoenix_live_view/helpers.ex
I've found this misleading error type in docs and added an example for it.
=> Misleading error type in docs

guides/client/js-interop.md, guides/introduction/installation.md
Per #828, this PR also changes the guides to reference `topbar` instead of `nprogress`.
I copied the changes from this commit: https://github.com/phoenixframework/phoenix/commit/abbd5f0d85100997d8ed075feba440d2b44f8edd
Not sure if the following line should be included in the guide or not. I copied it just to maintain consistency.
```js
topbar.config({barColors: {0: "#29d"}, shadowColor: "rgba(0, 0, 0, .3)"})
```
=> Use topbar in guides instead of nprogress

guides/client/bindings.md, lib/phoenix_live_view.ex
I noticed the documentation was missing `phx-key` in the list of key event bindings.
=> Add `phx-key` to list of bindings in docs

lib/phoenix_live_view/test/live_view_test.ex, lib/phoenix_live_view/test/upload_client.ex, test/phoenix_live_view/upload_channel_test.exs
This is my attempt at fixing: https://github.com/phoenixframework/phoenix_live_view/issues/1269
The issue is that the UploadClient will exit under normal operation, but it's started linked to the test process and kills the test.
In this PR I'm starting it supervised the way we do the client proxy.
I've also removed the `trap_exit`s from the the test as these are no longer needed -- we're monitoring the pids we need and they aren't linked to the test.
There's still one more place where we have a trap exit that I'm not sure about in the tests...
=> Start LiveViewTest.UploadClient Supervised

assets/js/phoenix_live_view.js, assets/test/view_test.js
Closes https://github.com/phoenixframework/phoenix_live_view/issues/1272
This gist is that after we `pushInput` we need to make sure that any error tags for our input that are still present have the `phx-no-feedback` class removed.
=> Add showError to display error tags after a pushInput

assets/js/phoenix_live_view.js, assets/test/view_test.js, guides/client/form-bindings.md
This PR closes https://github.com/phoenixframework/phoenix_live_view/issues/1109. I've tested this with @alexslade's test repo and errors now work as expected.
I realized that https://github.com/phoenixframework/phoenix_live_view/commit/95d5c7ccd0ac66e04b15c7b6128d44b60767e682 inadvertently addressed Jose's comment here: https://github.com/phoenixframework/phoenix_live_view/pull/1113#issuecomment-669501592
If we switch to using input name for phx-feedback-for, we get errors for radio buttons to show up correctly when you focus an element, because `showError` will show any hidden errors after the `pushInput`.
I've also kept support for id for backwards compatibility.
=> Use element name instead of id for phx-feedback-for

lib/phoenix_live_view/test/client_proxy.ex, lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/elements_test.exs, test/support/endpoint.ex, test/support/layout_view.ex
I made two small tweaks to the initial implementation. The first is obviously to implement relative path rewriting for stylesheets. The second is to use the full page html when we get the root LiveView and inject the updated stylesheet tags. This gets us the layout as well.
I'd been toying with this for a minute, but in light of #1279 I definitely wanted to get some feedback :)
Before and after from `mix phx.new --live`:
2020-12-18 Edit: Incorporating @leandrocp changes in #1281 we can rewrite the relative image paths, too :)
|**Before**|**After**|
| :---: | :---: |
| ![screenshot](https://user-images.githubusercontent.com/168677/102564787-01d36980-4091-11eb-8e23-3993c860cdc6.png) |  ![screenshot](https://user-images.githubusercontent.com/168677/102642876-30922400-4113-11eb-9729-630c29ece7 …
=> Open browser with layout and styles

assets/js/phoenix_live_view.js, assets/test/view_test.js
Follow up for [#1277](https://github.com/phoenixframework/phoenix_live_view/pull/1277#issuecomment-748604266). This prevents new hooks from getting `reconnected` callback invoked.
=> Trigger hook reconnected callback only when disconnected before

assets/js/phoenix_live_view.js, assets/package-lock.json, assets/package.json, assets/test/view_test.js
Closes #1288 
The issue is that form elements can belong to a form but be outside of it in the DOM tree if they use the `form` attribute. This updates some query selectors to find elements that are either in the form, or have the correct attribute.
I'm leaving this as a draft because I have two approaches and I'm not sure which is best. 
Initially I wrote some more complicated query selectors to find elements in the form, and with the correct form attribute. You can see this here: https://github.com/phoenixframework/phoenix_live_view/commit/f909261d26fd964258032777a71df567ef2ccb54
I found that `formEl.elements` gives us all of the form's data containing elements, both inside it and outside it (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Accessing_the_forms_elements …
=> Support phx-disable on form elements outside <form> tag

guides/introduction/installation.md
Other guides in this repository use `npm install` to add dependencies. It's a better approach in general.
=> use npm install command for topbar

lib/phoenix_live_view/test/client_proxy.ex, test/phoenix_live_view/integrations/elements_test.exs, test/support/endpoint.ex, test/support/layout_view.ex
Close #1295 - assume the default priv/static if static_url path is empty, otherwise resolve relative to priv dir, in other words:
`static_url: [path: "/static"]` will gerenate:
```
prefix: "/project/_build/test/lib/pulse/priv"
path: "/static/css/app.css"
```
And an empty `static_url` or empty static_url `path` will generate:
```
prefix: "/project/_build/test/lib/pulse/priv/static"
path: "/css/app.css"
```
/cc @mveytsman @mcrumm
=> Fix static_path in open_browser

assets/js/phoenix_live_view.js
The [HTML spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement) refers to the html select type being either a "select-one" or "select-multiple". This PR detects those, while keeping the original "select" to not break any backward compatibility.
=> detect “select-one” and “select-multiple” input types

guides/server/live-layouts.md
The root layout template is .leex now, at least I think :) It could just be that I only ever use --live these days. Apologies if I am mistaken.
=> Change the LiveView root layout explanation

guides/client/uploads-external.md
`done()` no longer exists on `entry`. It was removed in ccb2041ef30abae08c9be838932a8cc0f7e5ef8e.
=> Update uploads-external guide to remove done()

guides/server/using-gettext.md
Hey, thanks a lot for the hard work, I found a small missing comma in the documentation :)
=> adding a missing comma on the documentation

lib/phoenix_live_view/channel.ex
If this plug is not included, the session cannot be verified and will error out. You must include this plug somewhere in your pipeline in order to use Channel sessions.
=> Instructions for protect_from_forgery to be included

assets/js/phoenix_live_view.js
We add the bind-debounce listener to the form from the first element that has debounce binding. If that particular element no longer exists when the form is submitted, the `el.form` will be nil, and we get an exception when calling `new FormData(el.form))`.
Instead, we save the form as it's own variable in the closure, so we can refer to it in the callback even if the element has been removed.
=> Fix bug when form event listener is added from an element that no longer exists on the page.

guides/introduction/installation.md
This should have been on the previous PR https://github.com/phoenixframework/phoenix_live_view/pull/1343. Fixing before it's too late.
=> Update installation doc

lib/phoenix_live_view/helpers.ex
When upgrading the dependencies in the phoenix integration tests, I ran into the same compilation warning that was mentioned in #1330.
```
warning: variable "socket" is unused (if the variable is not meant to be used, prefix it with an underscore)                                                                                 
lib/default_app_web/live/live_helpers.ex:18: DefaultAppWeb.LiveHelpers.live_modal/3                                                                                                        
Compilation failed due to warnings while using the --warnings-as-errors option
```
This updates the macro to assign the unused `socket` param to `_` and fixes the compilation warning.
Fixes #1330.
=> Fix unused variable compilation warning in live_component/4

lib/phoenix_live_component.ex, lib/phoenix_live_view.ex
The docs stated in lib/phoenix_live_view.ex:
```
the optional `preload/1  callback is invoked, then
the updated values are merged with the component's assigns and
`update/2` is called
```
so the flow it stated was:
preload(new_assigns) ->  ?updated_values_are_merged?  ->  update(socket, new_assigns)
I believe this wasn't reflecting the current logic and also I changed the "default implementation"
wording to "not defined" based on what I saw in `Utils.maybe_call_update!/3`.
Thank you for reviewing.
=> Clarify assign update logic in send_update/3 and update/2 docs

lib/phoenix_live_view/test/live_view_test.ex
I was happily trying to write integration tests for the first time for the awesome file uploads when I encountered this error:
```
** (FunctionClauseError) no function clause matching in Phoenix.LiveViewTest.Upload.populate_entry/1
The following arguments were given to Phoenix.LiveViewTest.Upload.populate_entry/1:
{:content, "dummy content"}
Attempted function clauses (showing 1 out of 1):
defp populate_entry(%{} = entry)
code: file_input(show_live, "#script-inputs", :main, %{
```
It was a bit sneaky but compare the [doc of file_input/4](https://github.com/phoenixframework/phoenix_live_view/blob/a4d5353260b14c9c7850570dc83d41b72ff643fe/lib/phoenix_live_view/test/live_view_test.ex#L952-L958) with [the doc of render_upload/3](https://github.com/phoenixframework/phoenix_live_view/blob/a4d5353 …
=> Fix render_upload/3 doc

lib/phoenix_live_view/test/client_proxy.ex, lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/upload_channel_test.exs
Updates the component selector in [`file_input/4`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#file_input/4) to use the `phx-target` from the form input.
This could use a more robust set of tests around targeting.
Unless someone else beats me to it I will write them eventually :)
Closes #1357
=> Get the upload component id from the form's phx-target

guides/server/uploads.md
Updates the uploads guide to capture some additional information:
* Drag and drop support via `phx-drop-target`
* Automatic attributes for `live_file_input/2`
* Entry validation feedback via `upload_errors/2`
* Entry cancelation with `cancel_upload/3`
* Use `:code.priv_dir/1` in the `consume_uploaded_entries/3` callback example
* A complete annotated example of the LiveView module and leex template
=> Add more details to the uploads guide

lib/phoenix_live_view/upload_config.ex, test/phoenix_live_view/upload_config_test.exs
The type of the `:max_entries` option in the `allow_uploads` method is a `pos_integer()`.
https://github.com/phoenixframework/phoenix_live_view/blob/a109746493323fb5eabe2255bcfb8360d36c2674/lib/phoenix_live_view/upload_config.ex#L104
The current implementation does not check the given value of `max_entries` so the following codes do not raise errors:
```
allow_upload(socket, :avatar, accept: :any, max_entries: -1)
allow_upload(socket, :avatar, accept: :any, max_entries: 0)
allow_upload(socket, :avatar, accept: :any, max_entries: "bad")
```
This PR aims to ensure that the value pass through the `:max_entries` option is a positive integer.
=> Raises when invalid :max_entries for allow_upload is provided

lib/phoenix_live_component.ex
Fixes a typo in LiveComponent docs.
"components" should be a _possessive_ plural noun.
=> Fix typo in LiveComponent docs

README.md
Without a polyfill for `URL()` constructor, the IE11 raises an error here:
https://github.com/phoenixframework/phoenix_live_view/blob/cfed0cedacf365cd290e313c57d95088d4f67889/assets/js/phoenix_live_view.js#L1306
=> Add missing polyfill for URL() constructor

lib/phoenix_live_view/upload_config.ex
This PR addresses the compile time warning around the deprecation of `Mime.valid?/1`. The replacement function has been part of `:mime` since before the current version in Live View's lock file so this should be a safe substitution for all supported versions of Live View that follow this change.
=> fixing compile-time deprecation warning

lib/phoenix_live_view/test/live_view_test.ex, lib/phoenix_live_view/test/upload_client.ex
Three small updates related to file uploads and LiveViewTest:
1. Fix the example for `preflight_upload/1` (Related to #1346)
2. Handle `:garbage_collect` messages in `UploadClient` - these show up from time to time as unhandled messages in user-land test output
3. Handle the `ClientProxy` reply for the progress update after a `:chunk` call. This _should_ fix the MatchErrors that continue to plague the CI runs 🙏 even though I still can't reproduce it locally
=> Apply fixes for LiveViewTest with uploads

guides/introduction/installation.md
In order to keep up with the default install from `mix phx.new --live`,
explain the possibility of usage of `phx-track-static` which improves
the DX(Developer Experience) even more.
=> Suggest option to use `phx-track-static`

CHANGELOG.md, lib/phoenix_live_view/channel.ex, test/phoenix_live_view/upload_external_test.exs
The `consume_uploaded_entry/3` function was re-using the upload config from the previous progress message for external uploads which, in turn, lead to inconsistent state for the uploaded entries list.
// @ssbb
=> Always fetch latest upload config from socket

lib/phoenix_live_view/helpers.ex
I'm not 100% how to test this, as I did not found any `upload_errors/2` related tests. The idea is, that calling this function will return the errors for the whole upload conf instead of a particular file, this is especially helpful when dealing with the `:too_many_files` error.
=> Implement Phoenix.LiveView.Helpers.upload_errors/1

lib/phoenix_live_view/test/live_view_test.ex
The `connect_params` opt wasn't passed through to where it was needed, but `put_connect_params/2` works and the API is clear.
Closes #1414.
=> Correct docs for live_isolated/3 (#1414)

README.md
Without a polyfill for `new Event()` constructor, the IE11 raises an error here:
https://github.com/phoenixframework/phoenix_live_view/blob/756ea696cc46f88e03f5c076fe9217cb0a2951a5/assets/js/phoenix_live_view.js#L1058
=> Add missing polyfill for Event() constructor

lib/phoenix_live_view/engine.ex, lib/phoenix_live_view/helpers.ex, test/phoenix_live_view/controller_test.exs, test/phoenix_live_view/diff_test.exs, test/phoenix_live_view/integrations/function_components_test.exs, test/support/controller.ex, test/support/layout_view.ex, test/support/live_views/components.ex
This is the first of a set of PRs intended to improve support for components in Phoenix. 
This first PR introduces a `component/3` macro that should be used to define stateless components based on pure functions. The goal is to be able to create stateless components that can:
1. Be used in controller-based dead views, including layouts
2. Include live components in their inner block
3. Be diff-tracking-aware
The `component/3` macro along with the changes in https://github.com/phoenixframework/phoenix_html/pull/331 are requirements for the next PR which will introduce an HTML tokenizer and engine that will be able to parse an extended version of `EEX` called `HEEX`. This new format will allow injecting components in an HTML-like style (similar to React, Vue, Surface, ...). In addition, it …
=> Support function components via component/3

lib/phoenix_live_view/helpers.ex
Calling `<%= component &hello/0 %>` returns:
```
** (CompileError) [...] expected "assigns" to expand to an existing variable or be part of a match
```
And calling with `&hello/2` or more args returns:
```
** (BadArityError) #Function<... hello/2-"> with arity 2 called with 1 argument (%{name: "WORLD"})
```
Considering that a `var!(assigns)` is always expected, is it safe to assume that `component/3` should enforce arity 1? If so, can we improve the error message?
_With this patch:_
```
** (ArgumentError)   component/3 expected an anonymous function with 1-arity
Please call component with a 1-arity function, for example:
<%= component &func/1 %>
def func(assigns) do
~L"""
Hello
"""
end
```
Makes sense?
/cc @msaraiva
=> `component/3` should warn about wrong func arity?

lib/phoenix_live_view/test/live_view_test.ex
Just adding a small example to `follow_redirect` to illustrate usage with an error_tuple. Not critical, but I thought it would help save others time.
Feel free to edit.
=> In the docs, add an example of follow_redirect with an error tuple

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/elements_test.exs, test/support/live_views/elements.ex
Adds a `follow_trigger_action` macro that triggers an event, submits a form, and returns a conn.
Context: https://github.com/phoenixframework/phoenix_live_view/issues/1436
=> Add follow_trigger_action test utility

lib/phoenix_live_component.ex
Remind the reader the component form must be self-targeted for the
component to receive the event. (Helpful as the example does not show
the form template, and without a self-targeted form the event goes to
the LiveView.)
Explicitly name the view and component more often in the prose to
reinforce what is taking place where.
Tiny typos and consistent naming of `LiveComponent`.
=> Adjust LiveView/LiveComponent source of truth docs

lib/phoenix_live_view/helpers.ex
Since the introduction of `upload_errors/1` the error string `:too_many_files` is not a valid example for `upload_errors/2`.
=> Remove unnecessary error string

assets/js/phoenix_live_view.js, guides/client/js-interop.md
I think this should be the best approach, cause then every other function that calls `withinTargets` can send `this.el` (or any other element)
Closes #1396
=> Allowing to use node elements as the `target` on `pushEventTo`

assets/webpack.config.js
As discussed in https://groups.google.com/g/phoenix-core/c/Dk2AbXVnzeg
When running `npm run build`, this will:
* Add a comment to `priv/static/phoenix_live_view.js` pointing to the sourcemap
* Add a new file `priv/static/phoenix_live_view.js.map`
I have verified that when using webpack in your application, it will incorporate this sourcemap and therefore create better error stacktraces.
=> Add SourceMaps to minified JS

package.json
Similar to https://github.com/phoenixframework/phoenix/pull/4191, allows for ESM bundler support, such as [vite](https://vitejs.dev/) or [snowpack](https://www.snowpack.dev/). Adds the following to the top level `package.json`:
* `module`: [Near standard](https://github.com/rollup/rollup/wiki/pkg.module) way to denote the ESM entry point of a given package.
* `exports`: [Node.js](https://nodejs.org/api/packages.html#packages_package_entry_points) standard for specifying the entry point for when the package is being `import`'ed or `require()`'d (specifying the same as `module`/`main` respectively.)
* `dependencies`: This is a copy of the [runtime deps](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/package.json#L14-L16) specified in the `assets/package.json`. Not …
=> Add exports and dependencies to top level package.json

CHANGELOG.md, lib/phoenix_live_view/test/live_view_test.ex, lib/phoenix_live_view/test/upload_client.ex, test/phoenix_live_view/upload_channel_test.exs, test/support/live_views/upload_live.ex
~Fixes a regression created from fixing the latent errors around chunk replies for uploads in tests (#1409). Essentially I just moved the `receive` block into the chunk function that handles external uploads. This was done to avoid accidentally receiving unexpected messages, such as `:garbage_collect`, from the UploadChannel.~
Provides a proper fix for the sync render replies racing the chunk reply. When consuming uploads in the progress callback, the channel for the uploaded entry is being shut down at the same time we are receiving the reply– this is the expected behaviour, but we need to account for it by catching the shutdown message from the upload channel.
Closes #1432
=> Fix regression in render_upload/3 for channel uploads with progress

guides/server/assigns-eex.md
Add a note to the "EEx Pitfalls" documentation about passing raw assigns through with a temporary assign.
=> Add note about passing raw assigns with temporary assign.

assets/js/phoenix_live_view.js, assets/test/live_socket_test.js
resolves #1460 
This makes it possible to provide replacements for `sessionStorage` and `localStorage` in deployments where you cannot count on access to those APIs.  
Thank you Phoenix team for considering this addition.
=> Allow Storage Overrides

lib/phoenix_live_view/test/live_view_test.ex
The for block above is missing a do.
=> Fix missing do in for in render_upload documentation

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/flash_test.exs, test/phoenix_live_view/integrations/live_view_test.exs
Make the path argument to assert_patch optional.
Add a path call to get the current liveview path.
This is useful when you're testing a create form which is going to patch you to a path for the created resource
and you don't know in advance what the id is going to be.
For example:
```elixir
render_click(view, "save")
assert_patch view
assert path(view) =~ r/\/compose\/\d+/
```
Co-authored with @mveytsman
=> Allow testing with assert_patch where the path isn't known in advance.

lib/phoenix_live_view/test/live_view_test.ex
Why are typos invisible until the PR merges?
(cc @mveytsman)
=> Fix timout typo introduced in assert_redirect docs.

guides/client/js-interop.md
Also makes it more clear that `push_event` is a function on the server and not
the client.
=> js-interop guide add link for Phoenix.LiveView.push_event/3

CHANGELOG.md
Reading up through the change log to upgrade my local live view it was a bit confusing to not find any mention of `0.15.7` and I started reading the changes for 0.16 until I realised it was missing, this just pulls in the short change log from `0.15.7`
=> Add missing changelog for 0.15.7

lib/phoenix_live_view/helpers.ex
Considered "first and only" but this seems better to me.
=> Fix doc typo [skip ci]

guides/client/uploads-external.md
Heya,
I have followed the guide for [External File upload](https://hexdocs.pm/phoenix_live_view/uploads-external.html) and kept getting **500** from AWS on Preflight CORS request.  As result no files were uploaded from the browser due to CORS request not returning.
I copied request to CURL I noticed that it returns redirect instead of CORS headers directly. 
According to my understanding of [S3 documentation](https://docs.aws.amazon.com/general/latest/gr/s3.html) the endpoint `s3.amazonaws.com` can only be used for `us-east` region.
After adding the region prefix the issue is gone and files are uploading as expected.
=> Specify region for non us-east s3 buckets

lib/phoenix_live_view/html_engine.ex, test/phoenix_live_view/html_engine_test.exs
There's still one thing missing in this PR. 
Currently, if the user provides a non-matching pattern in `let` (due to a typo or something similar), like:
```
<.func
value="aBcD"
let={%{ittem: item}}>
...
</.func>
```
this would be raised, pointing to the initial line where the component was injected:
```
** (CaseClauseError) no case clause matching: {%{ittem: "the item"}}
```
Ideally, it should provide a more assertive message pointing to the line of the `let`, something like:
```
cannot match arguments sent from `render_block/2` against the pattern in `let`. 
Expected a value matching `%{ittem: item}`, got: `%{item: "the item"}`.
```
=> Support let to bind args sent from render_block/2

lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/plug.ex, lib/phoenix_live_view/route.ex, lib/phoenix_live_view/router.ex, lib/phoenix_live_view/session.ex, lib/phoenix_live_view/static.ex, test/phoenix_live_view/integrations/lifecycle_test.exs, test/phoenix_live_view/plug_test.exs, test/phoenix_live_view/router_test.exs, test/support/live_views/lifecycle.ex, test/support/router.ex
Follows #1490 and #1511 to allow `on_mount` at the router via `live_session`.
=> Add on_mount option to live_session

assets/webpack.config.js
* introduced in #1385
* removed again in #1474
* mailing list https://groups.google.com/g/phoenix-core/c/Dk2AbXVnzeg
* `phoenix` counter-part https://github.com/phoenixframework/phoenix/pull/4276
=> re-enable production source maps

test/phoenix_live_view/integrations/live_components_test.exs, test/support/live_views/components.ex
This is a followup to https://github.com/phoenixframework/phoenix_live_view/pull/1534 that fixes some more tests to use the new ~H sigil.
=> [test] Update LiveViewTest.StatefulComponent to use ~H sigil.

test/phoenix_live_view/diff_test.exs
Followup to my previous PRs to attempt to change the tests to use `~H`/heex.
=> [test] Update DiffTest to use ~H sigils.

guides/introduction/installation.md
This will fix the issue of Webpack complaining about:
```
Uncaught TypeError: phoenix_live_view__WEBPACK_IMPORTED_MODULE_6___default() is not a constructor
```
=> fix: Update installation guides

lib/phoenix_live_view/upload_config.ex, test/phoenix_live_view/upload_config_test.exs
According to the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept), an accept-input may be:
> A valid **case-insensitive** filename extension, starting with a period (".") character. For example: .jpg, .pdf, or .doc.
This PR simply downcases the incoming file extension before it compares it to the allowed file extensions.
=> make the upload file extension check case insensitive

assets/js/phoenix_live_view/dom.js
We may sometimes call `DOM.all()` on elements that have already been destroyed.
This closes #1532
=> Add a null check to DOM.all

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/integrations/live_view_test.exs
Adds test utilities that refute whether a redirect happened (optionally, to a given path; also optionally, within a given timeout). 
PR also includes a test that uses the test utility, which I guess is how you would write a test for a test utility? ¯\\\_(ツ)_/¯
Issue: https://github.com/phoenixframework/phoenix_live_view/issues/1539
If it looks good, I can do the other `refute_*`s too.
=> Add refute_redirect test utilities

assets/js/phoenix_live_view/dom.js, assets/js/phoenix_live_view/dom_patch.js
When a `<select>` input has focus during a DOM patch, we only force an update if the innerHTML has changed. However due to the internal state of the form control, the innerHTML may already differ from what the server sent and therefore we may always patch. For instance, given then following HTML:
```html
<select>
<option>A</option>
<option>B</option>
<option>C</option>
</select>
```
The `innerHTML` will evaluate as follows:
```
fromHtml=
<option selected="">A</option>
<option>B</option>
<option>C</option>
toHtml=
<option>A</option>
<option>B</option>
<option>C</option>
```
> Chrome is the only browser to exhibit a "flash" when the DOM is patched, but all browsers tested produced the same innerHTML fragments in this example.
~This PR will instead use the …
=> Stabilize patching focused select elements

lib/phoenix_live_view.ex
The title of the linked page was already changed to `Assigns and HEEx templates`, but it seems the link was missed.
=> Replace LiveEEx with HEEx in link

lib/phoenix_live_view.ex
Now that `LiveView.send_update/3` can send an update to a LiveComponent that is mounted in another LiveView the docs need to be updated to match.
I also experimented with some wording to clarify the related earlier paragraph:
>   If this call is executed from a process which is not a LiveView
nor a LiveComponent, the `pid` argument has to be specified.
Attempt 1:
>  If this call is executed from a process which is not the LiveView that this
LiveComponent is mounted within or a LiveComponent mounted within that
LiveView, then the `pid` argument has to be specified.
Attempt 2:
>   When sending an update to a LiveComponent that is mounted in another LiveView,
then the `pid` argument needs to be specified.
But I wasn't happy with those two proposed wordings. But I think the current text is a …
=> Update send_update docs

guides/server/live-layouts.md
This is related to #1565 as `Phoenix.LiveView.Router.live/4` no longer supports the `layout` option.
=> Remove `live` layout option from docs

CHANGELOG.md
:wave: Prior to `0.16` the default export (in javascript terms) of `phoenix_live_view` was `LiveSocket`. This meant that this:
```
import LiveSocket from "phoenix_live_view";
```
Worked fine, and that `0.16` broke this, leading to WebPack complaining about a missing default but compiling anyway, and the browser console mildly complaining. Standard LiveView tests did not catch this because they don't actually run any JS.
Fixing this is as simple as doing:
```
import { LiveSocket } from "phoenix_live_view";
```
But there was no documentation about this in the changelog, so, this PR warns about this for the future people caught out by this 😂
=> Warn about changes to the `LiveSocket` JS export

lib/phoenix_live_view/helpers.ex, test/phoenix_live_view/helpers_test.exs
The current documentation for `Phoenix.LiveView.Helpers.form/1` states: 
> for "post" requests, the form tag will automatically include an input tag with name _csrf_token. When set to false, this is disabled
Currently, even if the method is not set to "post", a CSRF token is generated, unless `csrf_token={false}` is explicitly set. This PR adds a check of the method before generating the token.
=> Fix - form helper generating CSRF token for non-POST forms

CHANGELOG.md
As a fix for #1572 @josevalim (in 6c0d642a939de4bd84a8b8b13cdd842588ef660c) added the ability to render functional components in tests, this mentions this in the change log for `v0.16.1`
=> Mention changes for testing functional components

lib/phoenix_live_component.ex
The use of `phx-click="<%= @click %>"` in markup of a `~H` sigil or a HEEX template results in an invalid syntax.
=> Update simple LiveComponent function example

CHANGELOG.md, guides/server/uploads.md, lib/phoenix_live_view/router.ex, lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_live_view/helpers_test.exs, test/phoenix_live_view/html_tokenizer_test.exs
_Mostly_ documentation, because of the little double space in `router.ex`.
=> Fix a few small typos in (mostly) documentation

lib/phoenix_live_view/html_tokenizer.ex, test/phoenix_live_view/html_tokenizer_test.exs
Otherwise the tokenizer emits a warning for things like:
```html
<svg>
...
<linearGradient ...>
...
</linearGradient>
...
</svg>
```
=> Relax html tag validation

lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/lifecycle.ex, lib/phoenix_live_view/static.ex, lib/phoenix_live_view/utils.ex, test/phoenix_live_view/hook_test.exs, test/phoenix_live_view/integrations/lifecycle_test.exs, test/support/live_views/lifecycle.ex, test/support/router.ex
This PR provides the following updates to the lifecycle flow:
* Lifecycle hooks for mount/handle_params will be called whether or not the LiveView module defines the callback.
* Lifecycle hooks for mount/handle_params are always invoked within their respective calls to `:telemetry span/3`.
* `attach_hook/4` will raise when attaching a `:handle_params` hook on a LiveView not mounted at the router.
Fixes #1563, Closes #1601
=> Update mount/handle_params lifecycle calls

guides/server/assigns-eex.md
A function component tag used a `%>` ending but I think it needs a `/>` ending.
=> Fix typo in assigns.md

CHANGELOG.md, lib/phoenix_live_view.ex, lib/phoenix_live_view/lifecycle.ex, mix.exs, test/phoenix_live_view/integrations/lifecycle_test.exs, test/phoenix_live_view/router_test.exs, test/support/live_views/lifecycle.ex, test/support/router.ex
Closes #1630
Also if the argument checks are too much we can pare them down and move the brackets `[[]]` back to userland :)
Draft PR as it's based on #1633
=> Accept extra args for on_mount hooks

lib/phoenix_live_view/test/live_view_test.ex
Fixes a typo with a variable name and adds the `~S` sigil to properly
render the regex in ExDoc.
Closes #1648
=> Fix docs for assert_redirect

assets/js/phoenix_live_view/view.js
I had some troubles with "legacy" file uploading next to LiveUpload. 
If I had an `<input type="file" multiple>` in my form, its `files` property would be empty on first pop, but populated on second try. I also got a JS error in the console:
```es6
upload_entry.js:17 Uncaught TypeError: Cannot read properties of null (reading 'split')
at Function.isActive (upload_entry.js:17)
at live_uploader.js:83
at Array.filter (<anonymous>)
at Function.activeFiles (live_uploader.js:83)
at Function.serializeUploads (live_uploader.js:42)
at View.pushInput (view.js:783)
at live_socket.js:676
at View.withinTargets (view.js:204)
at live_socket.js:354
at LiveSocket.owner (live_socket.js:345)
```
so it seemed that Phoenix would track inputs that were not LiveUploads, and the file input's `files` would end up …
=> Ensure tracked file input is a LiveFileUpload

lib/phoenix_live_view/helpers.ex, test/support/live_views/components.ex
Once upgrading to phoenix_live_view 0.16 we were expecting to get the warning based on the changelog but we weren't getting any.
It appeared that the warning was not appearing because of the patterns not matching. Are template assigns represented with a different tuple now?
I added a new pattern based on the tuple pattern I saw when debugging the issue.
Not sure this is the best course of action, or even if the original pattern must continue to be there or not.
Thanks!
=> Fix non-appearance of deprecation warning for live_component(@socket, ...)

guides/client/uploads-external.md
UpChunk requires a property called `endpoint`, not `entrypoint` for its `createUpload` method. (https://github.com/muxinc/upchunk#then-in-the-browser)
=> docs: Fix UpChunk example

test/phoenix_live_view/router_test.exs, test/support/live_views/lifecycle.ex, test/support/router.ex
Ensuring live_session with the `:on_mount` option supports lists of Module and/or {Module, arg}.
=> Add regression tests for live_session on_mount

CHANGELOG.md
1. Markup module and function names as code.
2. Fix capitalisations, punctuations, typos and grammar.
=> Improve CHANGELOG.md

guides/server/security-model.md
LiveView 0.17 updated the way that `on_mount` hooks are invoked, update the example in the security model guide to match.
=> Update security-model.md for LiveView 0.17

guides/server/telemetry.md, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/static.ex, lib/phoenix_live_view/utils.ex, test/phoenix_live_view/integrations/live_view_test.exs
Include the URI in the `[:phoenix, :live_view, :mount, *]` telemetry (when applicable). This allows logging the URI as a client navigates between liveviews alongside the session metadata.
=> add uri to mount telemetry metadata

lib/phoenix_live_view/controller.ex
In the example the variable name in use was incorrect. Instead of id it should be thermostat_id.
=> Fix example documentation

lib/phoenix_live_view.ex, lib/phoenix_live_view/channel.ex, lib/phoenix_live_view/utils.ex, test/phoenix_live_view_test.exs
This closes #1665 as it uses the full uri for searching the router instead of just the path passed to push_patch.
=> Push patch route verification deeper down to the root view

lib/phoenix_live_view/test/live_view_test.ex
Hello,
I noticed what I suppose is a typo in the doc for `Phoenix.LiveViewTest.assert_patch/3`, fixed by this PR.
Hope this may be useful :)
=> Fix typo in assert_patch/3 documentation

guides/server/live-layouts.md
While the `:layout` option to the `live` macro was partially removed
from the Live layouts guide in #1566, the sentence that is the subject
of this PR was overlooked.
If the preference would be to simplify the guide by removing any reference
to overriding the layout, then I can update this PR accordingly. However
as a newcomer to Phoenix who was just poking around to see how to set a
different root layout for a `live` route, this guide seems like a reasonable
place to discover that information.
If the PR reviewer agrees, then I will follow up with a second PR suggesting
changes to the paragraph that starts:
> "The "root" layout is shared by both "app" and "live" layouts.
=> Update Live layouts guide re: root layout change

lib/phoenix_live_view/engine.ex
When upgrading Phoenix.HTML, we needed to convert instances of `~E` in our codebase to `~H` as the former is now deprecated. Many of our existing `~E` invocations take the form:
```elixir
def welcome_message do
~E"""
<h2>Welcome to <%= app_name() %>!</h2>
"""
end
defp app_name do
Application.get_env(:my_app, :name)
end
```
Changing this to HEEx required introducing an `assigns` variable. The template requires no bindings, so I tried setting `assigns` to `%{}` or `nil`; e.g.
```elixir
def welcome_message do
assigns = %{}
~H"""
<h2>Welcome to <%= app_name() %>!</h2>
"""
end
```
However, this produced the following Dialyzer error message:
```
Warning: The pattern can never match the type.
Pattern:
%{}
Type:
nil
```
I have set up an [example LiveView …
=> Fix for Dialyzer issue with HEEx and empty assigns

lib/phoenix_live_view/test/live_view_test.ex, test/phoenix_component_test.exs
This PR adds two conveniences to `render_component` in testing.
1) Allows you to test a component without assigns 
```elixir
assert render_component(&hello/1) == "Hello World"
```
2) Adds the `:__changed__` key to assigns if not present. Both `assign` and `assign_new` require that key to be present, so before this change to test a component that used `assign`, you would have to do:
```elixir
assert render_component(&hello/1, name: "World!", __changed__: %{}) == "Hello World!"
```
now it's just
```elixir
assert render_component(&hello/1, name: "World!") == "Hello World!"
```
=> Improve `LiveViewTest.render_component`'s handling of assigns

lib/phoenix_live_component.ex
I believe that is what was meant there.
Thank you for reviewing.
=> Use "action" attribute to set URL of form in docs

guides/client/js-interop.md
Change the client hooks link to "#client-hooks-via-phx-hook" instead of "client-hooks".
=> Update client hooks link in js-interop guide

lib/phoenix_live_view/helpers.ex
=> Fix typo in render_slot docs

lib/phoenix_live_view/helpers.ex
The code fragment in the `live_component` doc isn't rendering correctly when output as HTML.
Before:
https://hexdocs.pm/phoenix_live_view/0.17.5/Phoenix.LiveView.Helpers.html#live_component/2
After:
=> Fix HTML rendering of doc for `live_component`

lib/phoenix_live_view.ex
`{:cont, socket}` is invalid unless `_socket` becomes `socket`
=> Fix on_mount doc

lib/phoenix_live_view/test/live_view_test.ex
These 2 examples from the docs would throw compilation errors if executed as they are now.
Related to: #1798
=> Corrected examples that throw compilation errors

lib/phoenix_live_view/js.ex, test/phoenix_live_view/js_test.exs
This would allow calling `JS.dispatch/3` without the `opts` (since both of them are optional).
e.g.: `JS.dispatch("event")` instead of `JS.dispatch("event", [])`.
See: https://github.com/phoenixframework/phoenix_live_view/issues/1684#issuecomment-989512243
=> Allow dispatch without opts

guides/server/uploads.md
This adds a note as a code comment to the live upload guide explaining that for `File.cp!` to work, the destination directory must exist.  While it does give a "no such file of directory" os error, I spent a good frustrated few minutes thinking it was the uploaded file that didn't exist.
This PR is just looking to save others the same potential small setback in what is otherwise a great experience of trying out example code that JustWorks.
=> Add Clarifying code comment to live upload guide

lib/phoenix_live_view.ex
Simple fix so it doesn't just render as `arg1` in the docs
=> Name parameter in callback for docs rendering

assets/js/phoenix_live_view/constants.js, assets/js/phoenix_live_view/live_socket.js
When a heavily loaded service restarts or crashes, clients need to retry.  This
can create problems where a "thundering herd" of clients can hammer a site into
oblivion.  Similarly, crashes also can create a tight-loop of reconnections if
preventative measures are not put in place.
Phoenix Live View implements a backoff mechanism that provides an initial
series of retries, spread out randomly.  Should these initial retries not
re-establish the connection, it "backs off" for a much longer period.
To date, these settings have been constants.  This can be limiting in
situations where developers have unique requirements.  This patch allows
overriding of four constants for use in such situations.
This is done through new options to the LiveSocket constructor, as follows:
* `maxReloads`: number …
=> provide options to adjust reload settings

assets/js/phoenix_live_view/live_socket.js
This looks like it resolves the issue mentioned here: https://github.com/phoenixframework/phoenix_live_view/issues/1808#L590
By forwarding `el` it `JS.exec` will use the element that has `phx-target` attribute. Right now, in master, it is sending the closest `phx-click` element or the element that has been clicked. 
I am not 100% sure convinced that this is the correct fix for it, but it did solve it in my test scenario. I was also not sure if `this.eventMeta` should then also be updated to use the correct target element or not.
~However, as I commented in the issue as well, I noticed a new behaviour in `master` where the private `click-ref` tracking can get in the way when you have more than 1 element with `click-away`. It ends up blocking regular clicks (not `click-away`'s). Maybe this …
=> fix the target element for click-away

lib/phoenix_live_view/test/client_proxy.ex, test/phoenix_live_view/integrations/live_components_test.exs, test/support/live_views/component_and_nested_in_live.ex, test/support/router.ex
This bug was found in the current project I'm working. There is a LiveView which initially has 2 live components and 1 child liveview. There is a button that doesn't re-render these chilren so components are destroyed as well as the child liveview. The problem was while testing this LiveView: I always got this error:
```
** (EXIT from #PID<0.5100.0>) an exception was raised:
** (KeyError) key :cids not found in: %{}
(phoenix_live_view 0.17.5) lib/phoenix_live_view/test/client_proxy.ex:641: anonymous fn/3 in Phoenix.LiveViewTest.ClientProxy.patch_view/3
...
```
While debugging this problem I got the following messages on re-render (inspecting a message in `ClientProxy.push/4` private function):
```
push message: %Phoenix.Socket.Message{
event: "cids_will_destroy",
join_ref: 0,
payload: …
```
=> Update state on phx_leave live_view event in Phoenix.LiveViewTest.ClientProxy

lib/phoenix_live_view/test/live_view_test.ex
I think it meant to be `button` as correct tag reference
=> Use correct reference for the button tag

lib/phoenix_live_view/html_tokenizer.ex
We started to build a Heex formatter that relies on this function to format the Heex input. Not really sure if that was supposed to be public but I'm adding docs to the current version of it.
=> Add docs to HTMLTokenizer

guides/client/js-interop.md
Was reading the JS Interoperability docs when I happened to notice that line 147 of `js-interop.md` contains a typo when referencing the name of the `JS.transition`, it reads `highligh` but should read `highlight`.
=> Fix typo in JS Interop docs concerning JS commands

guides/client/bindings.md
On https://hexdocs.pm/phoenix_live_view/bindings.html, when I click `Static tracking` link I was redirected to: https://hexdocs.pm/phoenix_live_view/%60Phoenix.LiveView.static_changed?/1
Before:
After fixed locally, when I put my mouse on top of the `Static tracking` link:
When I clicked I was redirected to [file:///.../phoenix_live_view/doc/Phoenix.LiveView.html#static_changed?/1]()
=> fix typo static tracking link

lib/phoenix_live_component.ex
Added an id attribute to the live component in the Slots example to distinguish it from the regular Phoenix.Component and to avoid confusion for the reader.
=> Updating example code for consistency

assets/js/phoenix_live_view/live_socket.js
`LiveSocket` is a named export not the default export of the module `"phoenix_live_view"`.
=> Fix error message when phxSocket is not a Socket

assets/js/phoenix_live_view/live_socket.js
When an anchor tag exists inside an SVG, the href is not a string but an [SvgAnimationObject](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString). This PR recognizes this and digs into the SvgAnimationObject to get the underlying href.
=> Fix issue with determining href for anchor tags inside an SVG

assets/js/phoenix_live_view/live_socket.js
LongPoll does not give an event argument to onClose. This is making it so you can't use LongPoll as a transport at all.
See: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/longpoll.js#L116
=> fix issue with LiveView and LongPoll

lib/phoenix_live_component.ex
- This sentence wasn't completely clear about the fact that the element ID must be set manually
- Fixed code indentation
=> Clarify component ID instructions

guides/server/error-handling.md
There is no module named `Ecto.NotFoundError`.
=> Correct name of Ecto exception in docs

lib/phoenix_live_view.ex
Fix typo: remove redundant "the".
Thank you for reviewing.
=> Fix typo: remove redundant "the"

lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
This commit changes `attrs={"value"}` to `attrs="value"` when the value is just a string
=> Removes brackets from string values

lib/phoenix_live_view.ex
Making even more explicit how `conn` assigns are shared with initial render of a `LiveView`
=> Minor assign_new/3 documentation update

lib/phoenix_live_view/test/live_view_test.ex
I was going through the docs for testing liveviews, and I came across this example, which is matching in a way it won't even compile. Changing it to an equality check sounds like the right thing here.
=> Fix assertion in test example

CHANGELOG.md, README.md, guides/client/js-interop.md, guides/introduction/installation.md
After `v0.17.5` some codeblocks specifying javascript as language were introduced in the markdown guides.
Current docs:
After this diff:
=> Fallback to default lexer

lib/phoenix_live_view/router.ex
Solves the issue described in [phoenix#4721](https://github.com/phoenixframework/phoenix/issues/4721)
Now since phoenix respects `:log_module` in metadata (see [phoenix#4723](https://github.com/phoenixframework/phoenix/pull/4723)) we can set it in here.
=> set LiveView module as a `:log_module` metadata to show in the routes

guides/client/js-interop.md
Hi,
I noticed this example was still using the deprecated LEEx attribute interpolation, while the rest has been migrated to HEEx.
=> Use HEEx interpolation in guide

lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
Related to https://github.com/phoenixframework/phoenix_live_view/issues/1950
Before this PR, the following input:
```
<div>
Should not <%= "line break" %>.
But it does.
</div>
```
wrongly, would out put this:
```
<div>
Should not <%= "line break" %>
.
But it does.
</div>
```
This commit fixes that.
=> Fix intentional line breaks after eex expressions

lib/phoenix_live_view/channel.ex, test/phoenix_live_view/test/dom_test.exs
- using `Enum.map_join` instead `Enum.map |> Enum.join`
- remove redundant last clause in `with`
=> Refactoring codes

lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
Trying out the new HEEx formatter I found a case where it isn't keeping single quotes delimiters on the final rendered template, eg:
It's changing `data-labels='["1", "2"]'` to `data-labels="["1", "2"]"` causing a compilation failure.
The tokenizer can handle it so I suppose the formatter should follow, right? https://github.com/phoenixframework/phoenix_live_view/blob/917b90e68577165aabc73eee030969bf3e490742/test/phoenix_live_view/html_tokenizer_test.exs#L412-L416
=> Preserve single quote delimiter on attrs

lib/phoenix_live_view/router.ex
As [suggested](https://github.com/phoenixframework/phoenix/pull/4748#issuecomment-1093135759) by @chrismccord in https://github.com/phoenixframework/phoenix/pull/4748, add `log_function` in addition to `:log_module` to liveview metadata informations.
=> Add :log_function info to router metadata

lib/phoenix_live_view/html_engine.ex, test/phoenix_live_view/html_engine_test.exs
Fix #1892
A template like
```elixir
<.function_component_with_single_slot>
<%= if true do %>
<:sample>
<p>inner</p>
</:sample>
<% end %>
</.function_component_with_single_slot>
```
is tokenized as
```elixir
tokens: [
{:tag_open, ":sample", [], %{column: 2, line: 3}},
{:text, "\n   ", %{column_end: 4, line_end: 4}},
{:tag_open, "p", [], %{column: 4, line: 4}},
{:text, "inner", %{column_end: 16, line_end: 4}},
{:tag_close, "p", %{column: 16, line: 4}},
{:text, "\n ", %{column_end: 2, line_end: 5}},
{:tag_close, ":sample", %{column: 2, line: 5}}
]
```
The `no case clause matching` happens due to the parsing of `{:tag_close, "p", %{column: 16, line: 4}}` which tries to set an unexpected root. So seems like the fix is to check if that tag is inside a named slot and no slots have been parsed …
=> Handle tag_close inside named slots

lib/phoenix_live_view.ex
In the example, the server was sending "scores" event, but frontend was handling "points" event.
=> Fix code example for push_event

lib/phoenix_live_view/html_formatter.ex, test/phoenix_live_view/html_formatter_test.exs
Running the formatter I noticed that https://github.com/phoenixframework/phoenix_live_view/pull/1964 may have introduced a bug.
Consider a line length of 25 and the template `<%= some_function("arg") %><span>content</span>`, it's rendered as:
```elixir
<%= some_function("arg") %><span>
content
</span>
```
Which is expected because the whole inline element doesn't fit on the line, but the problem is if you run mix format again you end up with:
```elixir
<%= some_function("arg") %>
<span>
content
</span>
```
Which is also expected because the inline element's meta is parsed with `newlines: 1` after the first pass.
_So currently it's like you have to run mix format twice to get the "final" version_
One possible solution is to force that inline element to be parsed with a newline on the first …
=> HTMLFormatter - Preserve inline element on the same line when followed by a eex expression without whitespace

lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
Without this change the example on test is rendered as:
```
<ul class="root" phx-no-format><%= for user <- @users do %>
<li
class="list"
>
<div class="child1">
<span class="child2">text</span>
</div>
</li>
<% end %></ul>
```
Note how the `li` attrs gets pushed back even though there's still room on the line (limited to 100). I believe that's because the current code does not reset nesting when the `context` is `:preserve`, which is done only when `meta` is set to `preserve`. So seems like when either context or meta is set to `preserve` it could reset nesting to generate a nicer output.
=> Respect nesting of children when phx-no-format is present

CHANGELOG.md, lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
We should also preserve the format in case there aren't whitespaces
among inline elments.
```
<b>foo</b><i><span>bar</span></i><span>baz</span>
```
=> Fix inline elements without whitespaces among them

guides/server/security-model.md
Hello, 
it seems that in the doc examples(v0.17.9), they were some unused function params without underscore.
I am sure if it was intentional.
My changes just add those ones.
=> Add underscore to unused function params

lib/phoenix_live_view/html_formatter.ex, test/phoenix_live_view/html_formatter_test.exs
The formatter is correctly breaking inline elements into new lines if it doesn't fit into a single line:
```
iex> input = """
...> <p>long line of text <span>span 1</span> more text <span>span 2</span></p>
...> """
iex> IO.puts Phoenix.LiveView.HTMLFormatter.format input, line_length: 45
<p>
long line of text <span>span 1</span>
more text <span>span 2</span>
</p>
```
So one would expect that running the formatter again on that formatted template would not change the outcome, but that's not the case:
```
iex> input = """
...> <p>
...>   long line of text <span>span 1</span>
...>   more text <span>span 2</span>
...> </p>
...> """
iex> IO.puts Phoenix.LiveView.HTMLFormatter.format input, line_length: 45
<p>
long line of text
<span>span 1</span> more text
<span>span 2</span>
</p>
```
Which …
=> HTMLFormatter - keep inline element if starts with \n

guides/client/bindings.md
Hi folks!
Wanted to propose a small documentation addition to convey that it is possible for key events to be triggered without the `key` field present in the value map sent to the server.
The code sample provided already covers this possibility with the catchall pattern match clause at the end, but wanted to explicitly state it since the current documentation makes it sound like there will always be a `key` field available to check.
I just ran into this issue personally so guessing others might too!
This may be a good use-case for an admonition block, LMK, happy to add/tweak wording.
Thanks so much for making LiveView & for taking the time to review!
=> Documentation: add note about possibility of key events being triggered with no key field present

lib/phoenix_live_view.ex, test/phoenix_component_test.exs, test/phoenix_live_view_test.exs
Would like input. 🙏
The idea is simply to provide access to the new assigns in the fn of assign_new 
Example. 
```
assigns = assigns
|> assign_new(:foo, fn  -> "foo")
|> assign_new(:bar, fn %{foo: foo} -> foo <> "bar")
```
=> Provide new assigns to fn in assign_new

guides/introduction/installation.md, guides/server/security-model.md, guides/server/using-gettext.md
Since setting the locale on a LiveView is something that will commonly need to be done for every LiveView in an application, I've added examples to the Gettext docs using the `on_mount` hook to apply the locale.
I've also replaced all the instances of `<%= web_namespace %>` in the doc examples with `MyAppWeb`, to be a bit more consistent with the rest of the documentation.
Please let me know if you have any suggestions. Thank you!
=> Add `on_mount` examples to Gettext docs

lib/phoenix_live_view/html_algebra.ex, lib/phoenix_live_view/html_formatter.ex, test/phoenix_live_view/html_formatter_test.exs
That's an attempt to improve and close #2001 
Ref https://github.com/phoenixframework/phoenix_live_view/issues/2001#issuecomment-1113645932
I had to fine tune the inline break rules a bit to deal with all possible cases, and we can add more tests if you have other edge cases in mind.
/cc @feliperenan thanks for commenting about that `flex_break`
=> HTMLFormatter - Improve inline and eex tags break

lib/phoenix_live_view/html_algebra.ex, test/phoenix_live_view/html_formatter_test.exs
An attempt to fix #2008
The core issue with those examples is they get into an "incomplete" state on the first format, causing `mix format --check-formatted` to fail. A couple of examples on master:
```
iex> input = """
...> <span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span> |
...> <span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>
...> """
iex> IO.puts formatted = Phoenix.LiveView.HTMLFormatter.format(input, [])
<span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span>
| <span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>
iex> IO.puts Phoenix.LiveView.HTMLFormatter.format(formatted, [])
<span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span> |
<span><%= link("Back", to: …
```
=> HTMLFormatter - text between inline elements

CHANGELOG.md, guides/client/form-bindings.md, lib/phoenix_component.ex, lib/phoenix_live_view/helpers.ex, lib/phoenix_live_view/html_engine.ex, test/phoenix_component_test.exs, test/phoenix_live_view/diff_test.exs, test/phoenix_live_view/helpers_test.exs, test/phoenix_live_view/html_engine_test.exs
Add support for `:let`. We still are going to support `let` but soon it will be deprecated. That is because new special attrs are coming such as `:for`, so we are using this `:` prefix to differentiate from normal HTML attrs.
=> Add :let attr

assets/js/phoenix_live_view/live_socket.js
This is change ensures the `InMemoryStorage` example code returns `null` when a key is not found.
LiveView stores data in localStorage in JSON, and a missing key will return `null`. The current `InMemoryStorageClass` example will return `undefined` which is not valid JSON and causes an exception.
Note: `null` is considered [valid JSON in browserland](https://stackoverflow.com/questions/46464447/json-parse-allows-null-as-value)
=> Update sessionStorage docs InMemoryStorage example

CHANGELOG.md, lib/phoenix_live_view/helpers.ex, lib/phoenix_live_view/html_engine.ex, test/phoenix_live_view/html_engine_test.exs
Closes https://github.com/phoenixframework/phoenix_live_view/issues/2017
This PR adds the sugar `:for` as you can see below:
```eex
<table id="my-table">
<tr :for={user <- @users}>
<td><%= user.name %>
</tr>
<table>
```
=> Add :for attr 

assets/js/phoenix_live_view/upload_entry.js
In order to ensure failed entries do not interfere with
further form actions, entries stop listening for update
events once error() is invoked.
Closes #2037
=> Cleanup after upload entry error, closes #2037

lib/phoenix_live_view.ex
As any sane developer I copied the example to be able to send my component an update asynchronously. It took me a fair while before I realised why it didn't work. My process received `{Reference.t, msg}` instead of `msg` because there was no `Task.await` in the example meaning that the result would be send to the process starting the task. Since the example is trying to update itself asynchronously I think `Task.start` is a better fit for the example. It also makes the examples when copy-pasted Just Work ™️ .
I almost got concerned that liveview didn't have the feature I was looking for. So I'm really happy it's there 👍
=> Make the examples for async updating a component work by default

lib/phoenix_live_view.ex
The second is slightly prettier and more informative.
=> docs: redirect(socket, arg2) -> redirect(socket, opts \\ [])

guides/client/form-bindings.md
Using the anonymous function version of `Phoenix.HTML.Form.inputs_for` will break if LiveComponents are used within the nested input. This update adds a section to the form bindings guide to that effect.
See https://github.com/phoenixframework/phoenix_html/pull/292 for further information.
=> Add reference to inputs_for in form bindings guide

lib/phoenix_component.ex, test/phoenix_component_test.exs, test/support/live_views/components.ex
Relates to #2016 
Adds the `:doc` option to `Phoenix.Component.attr/3` to support documentation generation for declarative attributes.
=> Support component attr :doc for documentation generation

assets/js/phoenix_live_view/dom.js, assets/test/view_test.js
Since `Phoenix.HTML.multiple_select/4` generates a select tag
with a name attribute containing a trailing `[]` to capture multiple options,
these elements should also be found when processing the
feedback elements with a `phx_feedback_for` attribute.
The value of the `phx_feedback_for` attribute is typically set with
`Phoenix.HTML.input_name/2` (as generated in the
`MyAppWeb.ErrorHelpers.error_tag/2` module), which does not add these
trailing square brackets, and hence the mismatch without this fix.
=> `phx_feedback_for` without trailing `[]` for multiple_select should also be processed when adding the `phx-no-feedback` class.

lib/phoenix_live_view/html_tokenizer.ex, test/phoenix_live_view/html_formatter_test.exs, test/phoenix_live_view/html_tokenizer_test.exs
Without this fix, the formatter will thrown an match error because the
HTML comment token doesn't contain the `:comment_end` in this case. This
commit aims to fix that.
=> Fix formatter when there is HTML + EEx expressions

lib/phoenix_live_view/html_engine.ex, lib/phoenix_live_view/html_tokenizer.ex, test/phoenix_live_view/html_formatter_test.exs
I changed the HTML tokenizer to emit the lines breaks since the Formatter knows how
to deal with them already. It also required to change HTML Compiler to not render the
lines breaks to keep it working as it is intended to.
=> Formatter - Keep intentional lines for slots

CHANGELOG.md
Noticed these when reading about all the upcoming 0.18 goodness!
=> Fix tiny typos in Changelog

assets/js/phoenix_live_view/live_uploader.js, assets/js/phoenix_live_view/upload_entry.js, lib/phoenix_live_view/upload_config.ex, test/phoenix_live_view/upload/channel_test.exs, test/phoenix_live_view/upload/config_test.exs
Now you can do this:
`<%= live_file_input @uploads.files, webkitdirectory: true %>`
and get `%UploadEntry{}` with a relative path.
One of the drawbacks of this implementation is that you cannot drag and drop folders, you than need some more javascript to make it work. (https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree)
But I think this is an important feature as is.
Another drawback is that this not supported on most mobile phones, but should not be a problem anyway.
(https://caniuse.com/?search=webkitdirectory)
There is a reported issue on this: #1482
=> Add relative path to upload if webkitdirectory attribute used

.formatter.exs, lib/mix/tasks/compile/phoenix_live_view.ex, lib/phoenix_component.ex, lib/phoenix_live_view/helpers.ex, lib/phoenix_live_view/html_engine.ex, test/mix/tasks/compile/phoenix_live_view_test.exs, test/phoenix_component_test.exs, test/phoenix_live_view/helpers_test.exs, test/phoenix_live_view/integrations/live_components_test.exs, test/support/live_views/components.ex
=> Declarative Slots & Literal Type Validations

assets/js/phoenix_live_view/live_socket.js
Hello 👋 I might be missing some context, but while updating the TS type definitions for this library I stumbled upon this instance of `cancelTimeout`. I can't find any other mention of `cancelTimeout` except in the JS for the `phoenix` package - however there it takes 0 arguments rather than the timer ID. Should this be [clearTimeout](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout) instead?
=> Use clearTimeout when calling reset() on TransitionSet

lib/phoenix_component.ex, test/phoenix_component_test.exs
See https://github.com/phoenixframework/phoenix_live_view/issues/2128
=> Raise an error if a declarative slot and a declarative attr share the same name

lib/phoenix_component.ex
- Expand the explanations a bit
- Fix: pass `entries` in the pattern matching example
- Show that `:let` defines the variable name for the block
-  Show how to conditionally render a slot
=> Clarify slots documentation

assets/js/phoenix_live_view/live_socket.js
This PR removes a single line:
`console.log(simulating ${latency}ms of latency from server to client)`
The latency simulator is really helpful for debugging, but this line absolutely trashes the console when debugging JavaScript applications with a LiveView backend, the point where I think this amount of logging is actually having a performance impact on the application beyond the latency, and it making debugging in the console a lot harder.
It's really not necessary, as there is already `latency simulator enabled for the duration of this browser session. Call disableLatencySim() to disable` announcement in the console when it starts, so everything after that is redundant. It should just do its job and not announce itself every time it's called.
=> Remove Latency Sim Console Log

assets/js/phoenix_live_view/live_socket.js
Follow up to #2142. I missed that these lines happen in both directions in the previous PR. Sorry about that. This removes the other call.
=> Remove Latency Simulation Console Logger (Again)

guides/server/telemetry.md
I just removed a couple of words that were not necessary for the description of the telemetry event.
=> Remove extra words from sentence in telemetry guide

lib/phoenix_component.ex
Two minor accidents and a tweak which may (or may not) read better.
=> Fix grammar when describing component :default option

lib/phoenix_component.ex
Some other accidents.
Also unsure if line 167 is correct (not included in patch):
```diff
- Global attribute can define defaults which are merged with attributes provided by the caller.
+ Global attributes can define defaults which are merged with attributes provided by the caller.
```
It's unclear to me whether it should be *attributes* - plural, which probably reads better -  or if you may only define one and we're talking about *the* global attribute for the component.
Since the `:global` type seems to act as a "splat" or `assigns_to_attributes` without an exclude list, it doesn't make much sense to me to define it more than once. I couldn't see that explicitly outlined in the docs but maybe I missed it. Perhaps that should be *The global attribute can ...* but that also feels a bit …
=> Fix spelling in Phoenix.Component docs

lib/phoenix_component.ex, test/phoenix_component/components_test.exs
This broke recently when I set the default value of `csrf_token` to `false`, causing `Keyword.pop_lazy/3` to never be called to generate a token 🙃 
This PR fixes that bug and adds a test verifying that functionality.
=> Fix `form/1` csrf_token generation

lib/phoenix_component/declarative.ex
=> Doc generation: add missing dash separator before "Accepts attributes"

guides/introduction/installation.md, guides/server/live-layouts.md
2 documentation pages still mention `live_title_tag` and need to be updated.
Current installations break on this, so it should be mentioned in the changelog too (not included).
=> Doc: replace live_title_tag with live_title

assets/js/phoenix_live_view/live_uploader.js
For some reason the `serializeUploads` method did not pass the uploaded file's modification timestamp, so `last_modified` in `%UploadEntry{}` would always be `nil`.
before:
```elixir
%Phoenix.LiveView.UploadEntry{
cancelled?: false,
client_last_modified: nil,
client_name: "privacy.html",
client_relative_path: "",
...
}
```
after:
```elixir
%Phoenix.LiveView.UploadEntry{
cancelled?: false,
client_last_modified: 1660645834947,
client_name: "privacy.html",
client_relative_path: "",
...
}
```
=> Set last_modified for upload's serializer

guides/client/form-bindings.md
How to reproduce
```sh
$ mix phx.new myapp && cd myapp/ && mix ecto.create
$ mix phx.gen.live Accounts User users name:string
$ mix ecto.migrate
```
Now, 
- remove `id` attribute from a form in `lib/myapp_web/live/user_live/form_component.html.heex`, 
- start the server, 
- visit `/users/new` 
- and type something into the form's field, 
- restart the server.
The form's state wouldn't recover.
=> Only forms with `id` attribute are recovered

test/phoenix_live_view/integrations/flash_test.exs, test/support/live_views/flash.ex
The current `Phoenix.LiveViewTest.FlashComponent` does not target the `lv:clear-flash` actions to itself and the test is passing due to a false positive. More info at https://github.com/phoenixframework/phoenix_live_view/issues/1842#issuecomment-1099729676
It does not address the case explained at https://github.com/phoenixframework/phoenix_live_view/issues/1842#issuecomment-1018569574 but AFAIK this test is supposed to be about clearing the flash of the component itself so the changes here are just to fix this specific scenario.
=> Fix lv:clear-flash tests on components

lib/phoenix_component.ex, test/phoenix_component/components_test.exs
I noticed that auto-uploads have not been working on the master branch - after a bit of digging I found the issue and this change should resolve it.
The `live_file_input/1` data attributes were inlined in https://github.com/phoenixframework/phoenix_live_view/commit/4f2d5550a93391d3aca9e5b33a981b70ec31740b and the `data-phx-auto-upload` attribute was given an underscore rather than a hypen.
=> Use the correct data attribute for auto upload on `live_file_input/1`

lib/phoenix_component.ex, lib/phoenix_component/declarative.ex, test/phoenix_component/declarative_assigns_test.exs, test/phoenix_component/verify_test.exs, test/support/live_views/components.ex
=> Support `:examples` and `:values` for declarative attributes

lib/phoenix_live_view/html_tokenizer.ex, test/phoenix_live_view/html_formatter_test.exs
The tokenizer would duplicate `[:comment_end and :comment_start]` if there were multiple comments in a row:
```
```
would emit:
```
[
{:text, "\n\n",
%{column_end: 1, context: [:comment_start, :comment_end, :comment_start, :comment_end], line_end: 3}}
]
```
That would break the HTML formatter.
This commit makes sure the comments metada token are unique so now it would emit like this:
```
[
{:text, "\n\n",
%{column_end: 1, context: [:comment_start, :comment_end], line_end: 3}}
]
```
=> HTML Tokenizer - Fix tokens emitted for comments
